### ISSUE TITLE
Fix location of GeoJSON JSON-LD @context

### ISSUE THREAD

**Issue by zimeon** [IIIF/iiif.io#1001]
The GeoJSON `@context` used in the [Linking to External Services](http://iiif.io/api/annex/services/#geojson) document and copied into the [Image API Complete Example](http://iiif.io/api/image/2.1/#complete-response), `http://geojson.org/contexts/geojson-base.jsonld`, now gives 404.

What should it be? We should fix for Image 2.1.1

Reported by John Howard on [iiif-discuss](https://groups.google.com/forum/#!topic/iiif-discuss/sjpsXQlkUHA).

**Comment by mikeapp** [comment]
`http://geojson.org/geojson-ld/geojson-context.jsonld` ?

**Comment by azaroth42** [comment]
Thanks @mikeapp. Will make a PR to fix in both places.
