### ISSUE TITLE
make call info for groups an include

### ISSUE THREAD

**Issue by srabun** [IIIF/iiif.io#1002]
@srabun You might consider making this an 'include'. See, e.g., at the end of this section. The line {% include copyright.md %} corresponds to the file source/_includes/copyright.md, which gets copied in when the site is built. It keeps you from having to maintain the info in multiple places. You could make something like call_info.md and do similar.

**Comment by glenrobson** [comment]
Transferred to: https://github.com/IIIF/iiif-root-website/issues/20
