### ISSUE TITLE
Refer to Content Search API in Presentation API Intro, not "a future IIIF specification"

### ISSUE THREAD

**Issue by zimeon** [IIIF/iiif.io#1003]
The [Objective and Scope](http://iiif.io/api/presentation/2.1/#objectives-and-scope) section of prezi intro says:

> The following are not within scope:
> 
>  * The discovery or selection of interesting digitized objects is not directly supported; however hooks to reference further resources are available.
>  * Search within the object is not supported by the Presentation API; however this will be covered by a future IIIF specification.

The second bullet should link to the [Content Search API](http://iiif.io/api/search/) since that now exists!

 * [x] fixed on 2.1.1 branch
 * [ ] merged to master

**Comment by jpstroop** [comment]
* [ ] fixed on 2.1.1 branch
 * [ ] merged to master

**Comment by zimeon** [comment]
Was addressed by https://github.com/IIIF/iiif.io/pull/979/commits/4603113fc1d7c58cf72a8fbca30c8850f66fd924
