### ISSUE TITLE
Unclear if Ranges can have empty Member list

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#1016]
__Issue:__  

From the current (2.1) Presentation API specification, it is unclear in [Section 5.6](http://iiif.io/api/presentation/2.1/#range) if all three of `canvases`, `ranges` and `members` can be empty.  Can there be a Range that has no child resources?

__Proposal:__

Following from the previous decision about empty collections, I propose that it should have the equivalent text:

> An empty range, with no member resources, is allowed but discouraged.

As this is essentially an editorial clarification, I think it can go in 2.1.1. 

__Background:__

Discovered by @joshuago78 and @alyxrossetti in mapping our EAD finding aids to the partially digitized collections, currently managed in Rosetta as METS. The pattern used is to have a Manifest at the highest component level that has digital content in Rosetta as a METS file, and to use Ranges to describe sub-structures.  For content that has not yet been digitized we know from the EAD that there is something there, but not even how many images will result from the digitization (6 letters, 2 folders etc is unhelpful!) and hence can't reasonably mint empty canvases.

**Comment by tomcrane** [comment]
> An empty range, with no member resources, is allowed but discouraged.

👍 
The publisher could provide a label that maybe hints at why it's empty:

```
"label" : "Not digitized yet, come back later..."
```

**Comment by azaroth42** [comment]
:+1: on a human readable label, or description. 

We were also considering a URI `viewingHint` to make it machine processable as well.  That would be at best 2.2 as a new feature if it was seen as broadly useful ... I'll raise a separate issue.

**Comment by jpstroop** [comment]
Separate issue, but I'm surprised to see EAD components modeled as Ranges rather than Collections. Those could be some huge Manifests, knowing how things typically go w/ EAD.

**Comment by azaroth42** [comment]
We also model higher level components as Collections, until we hit something that was considered a "digital object" according to Rosetta. We then merge the EAD descriptive metadata with the METS structmap and other info. That is indeed just as much fun as it sounds.

**Comment by zimeon** [comment]
I much agreement: currently unclear in 2.1 so clarification OK for 2.1.1 as non-breaking, agree that empty should be allowed, agree that suggesting a label also good. (No comments on EAD.)

**Comment by jpstroop** [comment]
> We also model higher level components as Collections, until we hit something that was considered a "digital object" according to Rosetta. We then merge the EAD descriptive metadata with the METS structmap and other info.

There's some sense to that, though FWIW I'd probably prefer to map the logical component type consistently (maybe EAD collections, series and subseries etc. are IIIF collections, and EAD files on down are Manifests) rather than 'this is where the pictures start'.

**Comment by mikeapp** [comment]
:+1:

**Comment by jpstroop** [comment]
I agree that we should be consistent w/ Collections. Should we `MUST` a `label` or `metadata`?

**Comment by azaroth42** [comment]
Is a `MUST` here a breaking change though?

**Comment by mikeapp** [comment]
We agree that `members` can be empty.  `MUST` is a breaking change so not for this release.
