### ISSUE TITLE
Intentionally-Left-Blank viewingHint?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#1017]
__Issue:__ The UX challenge of empty canvases, collections and ranges (per #1016) might tempt viewer developers to simply skip over them. However, there may be valuable annotations or descriptive properties that the user should be presented with so they understand the context.

__Proposal:__ We could create an "intentionally-left-blank" `viewingHint` to highlight that the resource is intentionally empty, but important.  This could distinguish it from resources that are in the process of being filled in an editor environment, but might be hidden in a public rendering interface.

__Discussion:__ This could also be overkill, and if the viewer sees `metadata` or similar properties, it could render the resource as normal.  Close WontFix is an acceptable outcome, but we thought we'd float the idea and see if it sinks or swims.  (@joshuago78 @alyxrossetti)

**Comment by jpstroop** [comment]
`intentionally-left-blank` feels too specific. I think there are legit use cases here, but that they could extend to, e.g., known but missing leaves in a manuscript as well (I think catalogers might use the word "wanting", but that doesn't cover the intentional use case) or missing sections of a reel of film or tape that you want to account for on a time axis. :+1: to the concept, but we need a better label for a thing that either (1) exists but we don't have an image or (2) exists but is blank or otherwise not interesting. Or does a UI care about that distinction beyond what can be surfaced in metadata?

**Comment by zimeon** [comment]
I think @jpstroop has the two key cases in comment above, I agree that there term `intentionally-left-blank` is wrong -- it seems both too specific in some cases, too vague for others. I might suggest something along the lines of (1) `no-image-available` and (2) `blank`. If we feel that case (1) is too specific to warrant a special term then got with just a very general (2).

**Comment by azaroth42** [comment]
How about `empty`?  That would cover collections / ranges without children, and canvases without content?

**Comment by zimeon** [comment]
I like `empty`

**Comment by mikeapp** [comment]
+1 to `empty`

**Comment by jpstroop** [comment]
I was thinking of something like null, nil, or none, but agree that `empty` is better than those, but I think we can do better or should at least think for a while. `void`? `vacant`? `bare`? `unfilled`?

I'm also still wondering if there are any UI use cases that require the ability to to distinguish between `missing` and `boring`. The only ones I can think of can be solved with `label` or `metadata`.

**Comment by sdellis** [comment]
So use cases for ignoring are `missing`, `boring` and `unpublished`? All of those contain some big assumptions.  Why not intend for everything to be  rendered unless it has a viewing hint such as `ignore`?

**Comment by tpendragon** [comment]
Not an editor, but I vote this is overkill and a good viewer renders the canvases that have stuff attached to it.

**Comment by jpstroop** [comment]
Fair points. From this angle, you should trust the data, and the server should return something that reflects its intentions. If a canvas doesn't have an image or a service but does have dimensions, a label, metadata, etc., a UI should be able to handle it that without any new hints. If a range or collection has no children, then there's just nothing to show below (whatever that means to the client/UI). If the server doesn't want you to show these thing (blank canvases, empty collections/ranges), then it probably shouldn't include them in the first place.

**Comment by sdellis** [comment]
Completely agree, @jpstroop. @azaroth42 makes a good point that one may want to annotate a blank canvas for various reasons.  Re-reading @tpendragon's comment, I take back my thumbs up.  A good viewer should render blank members to the degree that it can have metadata and one can use it as an annotation target.

**Comment by azaroth42** [comment]
Propose close wontfix -- viewers shouldn't need a hint to do the right thing.

**Comment by mikeapp** [comment]
OK with close wontfix, agree that the client UI will have to handle it (and approaches there may vary).

**Comment by tomcrane** [comment]
Agree wontfix. The publisher has provided a canvas and given it an id. It's a thing. Why it's blank could be conveyed through `label` etc.
