### ISSUE TITLE
Acknowledgements sections

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#1031]
Two questions:

1.  To what extent does Mellon now support the production of specifications?  It clearly did for the first four, and supports the BL's AV grant (but that isn't for IIIF nor the specifications directly).  We don't ack (for example) MOMA, Europeana, Vatican, etc for hosting WG meetings so I don't think that the BL grant would qualify Mellon for the acks?  I don't think there is any obligation for discovery specifications?

2.  To what extent does the IIIF Consortium support the production of specs? With Sheila being so excellent in supporting the work of the community, I think IIIF-C does deserve an ack.

**Comment by zimeon** [comment]
IIIF-C publishes the specs so I don't think it makes sense to also acknowledge the consortium

**Comment by azaroth42** [comment]
I don't think the *consortium* publishes them? It's not like the W3C where we need to get director's approval to change status. We published specs before the consortium, and if the consortium were to fold due to lack of people paying in to it but the community was still healthy in general, we would continue to publish specs after its untimely demise.

**Comment by zimeon** [comment]
??? _Copyright © 2012-2017 Editors and contributors. Published by the IIIF Consortium under the CC-BY license, see disclaimer._

**Comment by azaroth42** [comment]
True! Okay, agreed no need to ack the consortium :)

**Comment by azaroth42** [comment]
Propose close, invalid :)

**Comment by zimeon** [comment]
Closing as issue creator suggests
