### ISSUE TITLE
Follow Linked Data Principles

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#1037]
We conform to Linked Data standards, follow the web architecture and relevant specifications as defined by the W3C and IETF.  Although we do not require an RDF based stack, it must be possible to implement using one, and to transform representations back and forth between triples and the JSON serialization without loss, but not necessarily without custom code.

**Comment by julsraemy** [comment]
👍

**Comment by zimeon** [comment]
Avoiding "we", suggest: _"IIIF specifications should conform to Linked Data standards, follow the web architecture, and relevant specifications as defined by the W3C and IETF. They should not require an RDF based stack to implement, but it must be possible to implement using one. It should also be possible to transform representations back and forth between triples and the JSON serialization without loss, but not necessarily without custom code."_

**Comment by zimeon** [comment]
Agreement on 2017-03-15 community call.
