### ISSUE TITLE
Design for JSON-LD First

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#1038]
We focus on JSON-LD as the primarily serialization to make development easier. The abstraction provided by JSON-LD contexts is important.

**Comment by zimeon** [comment]
Stronger: The use of JSON-LD contexts and framing to is important to allow IIIF JSON-LD documents to be generated and used by plain-JSON applications.

**Comment by julsraemy** [comment]
👍

**Comment by azaroth42** [comment]
Refer to: http://json-ld.org/spec/latest/json-ld-api-best-practices/

**Comment by zimeon** [comment]
Discussion on the 2017-03-15 community call about whether there should be a more detailed comment implementation technologies such as RDF stores. Conclusion that intention/meaning is correct so leaving.

**Comment by workergnome** [comment]
I think that the question that I was trying to raise (quickly) on the call was if we are designing a JSON api that happens to resemble a RDF serialization, or if we are designing a RDF API designed to serialize well into JSON-LD and to work well with web infrastructure.  My take from the call was that we were doing the second, which I am in agreement with.  I'd be interested in talking more about it if we're talking about the first.

**Comment by zimeon** [comment]
OK, sorry, I was too hasty to close...

IMO, the Presentation API is clean RDF model/data which we expose as JSON-LD. However, we consider it essential that it is easy to implement clients that read this data as JSON. The plain-JSON requirement for both server and client seems even more important for the Image API where almost all servers and clients aren't RDF-based, but we still want the data to play nicely with Presentation API and other RDF data.

**Comment by workergnome** [comment]
(copied in from Slack)

What I was trying to express in regard to the Design Patterns that one should be able to:

1. Take a IIIF resource.
2 De-serialize it into a graph.
3. Use a standard RDF technique (like SPARQL) to query for and serialize that graph.
4. Use a JSON-LD frame to reconstruct the IIIF resource as JSON.

I agree that most clients are JSON-based, and optimizing for a clean JSON serialization is essential.  I just want to make sure (and I'm pretty sure that <http://patterns_tweaks.iiif.io/api/annex/notes/design_patterns/#follow-linked-data-principles> states), that it should be *possible* to generate directly from RDF, using native RDF tools, without post-processing.   I'd be willing to add a tiny bit more complexity to the JSON pipeline to preserve the possibility of an RDF pipeline, but if the construct either requires the creation of terrible JSON or eliminates an RDF pipeline, we should reconsider that design decision.

**Comment by azaroth42** [comment]
@workergnome @zimeon What do we need to do to close the issue out?

**Comment by workergnome** [comment]
I think this is fine to close—if there's an issue, it's on #1037, and I think we're in agreement on that one.

**Comment by azaroth42** [comment]
Great :) Thanks @workergnome!
