### ISSUE TITLE
Use Existing Standards Where Possible

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#1040]
We aim to be consistent with and use existing standards when possible.  This is tempered by the need for ease of understanding and implementation ... a bad standard with an ISO number is still a bad standard.

**Comment by julsraemy** [comment]
👍

**Comment by zimeon** [comment]
Avoiding "we", not bashing ISO, suggest: _"IIIF specifications should be consistent with and use existing open standards when possible. This is tempered by the need for ease of understanding, implementation, and the timing of standards evolution and updates."_

**Comment by zimeon** [comment]
Agreement on 2017-03-15 community call.
