### ISSUE TITLE
Select Solutions That Are as Simple as Possible, and No Simpler

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#1041]
We aim to reduce the complexity to the lowest possible point at which the use cases can be accomplished.  Also, make the simple things easy, and the complex things possible ... build up from the MVP / simplest in stages to incrementally allow more complex use cases.

**Comment by zimeon** [comment]
Avoiding "we", suggest: _"IIIF specifications should be designed to reduce the complexity to the lowest possible point at which the use cases can be met. They should make simple things easy, and complex things possible. They should allow implementers to build up from a minimum viable product in stages, to incrementally allow more complex use cases."_

**Comment by sdellis** [comment]
As mentioned in the REST principle discussion #1036 (as well as past discussions), complexity is often a trade-off. "Simpler" choices from a specification point of view (or from a server-side implementation) can be quite complex to client-side developers and vice versa. So if the intent is to make things simple for one segment of the community and push the complexity off to another, the "as simple as possible and no simpler" principle should be specific about who has privilege in deciding what "simple" means.

**Comment by zimeon** [comment]
Not all cases of simple are trade-offs, in many cases simplicity applies to both server and client sides such as simply not including a feature that isn't required to support the use cases.

In the case of things that are trade-offs I don't think it makes any sense to privilege client or server side in principles. The community decides (as with everything) and must weigh client complexity vs server complexity in each case.

**Comment by azaroth42** [comment]
I could see spelling that out a little more explicitly in the principle.

Suggest adding a new sentence to the end:  
> Simplicity is often a trade-off between parties, and must take into account the generation and publishing of the data on the server side, and the consumption and processing of the data on the client side.

**Comment by zimeon** [comment]
Discussed on 2017-03-15 community call, suggested addition above highlighted, support expressed and no objections -> should add this.

**Comment by zimeon** [comment]
Addition now live in http://iiif.io/api/annex/notes/design_patterns/#select-solutions-that-are-as-simple-as-possible-and-no-simpler
