### ISSUE TITLE
Define Success, Not Failure

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#1042]
We define what should be expected to work, not what should not work.  Any pattern that is undefined is undefined, not verboten. This allows for future api extensions and experimentation.

**Comment by zimeon** [comment]
Avoiding "we": _"IIIF specifications should define what is expected to work, not what should not work. The handling of unspecified patterns is undefined. This allows for experimentation and for future API extensions."_

**Comment by jpstroop** [comment]
I think this needs to be expanded, but I'm struggling to come up with better language. Should we use the words "prescriptive" and "restrictive"? Or add an explicit example? This is important, and I'm worried that it won't be clear to the general community without a little more explanation.

**Comment by azaroth42** [comment]
Expanded and added hopefully clarifying example.

**Comment by zimeon** [comment]
Agreed on 2017-03-15 community call.
