### ISSUE TITLE
Follow the IIIF Community Process

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#1043]
We follow the community process as defined in the note.

Not sure if this is a real design principle, but may a "process" section? Or just a note in the introduction?

**Comment by zimeon** [comment]
I think this isn't/shouldn't be a design principle, but it would be nice to link in the intro to the community process as a companion document .

**Comment by zimeon** [comment]
I realize that in my earlier comment I'd lateched onto the wrong community process document. I think we should mention in the intro both the  [IIIF Community Framework](http://iiif.io/community/groups/framework/) and the [IIIF Editorial Process](http://iiif.io/api/annex/notes/editors/) which includes the [Community Process](http://iiif.io/api/annex/notes/editors/#community-process).

**Comment by jpstroop** [comment]
Agree that we shouldn't make this one of the high-level principles, but instead link to other documents on the site at a more granular level as supporting evidence/criteria as needed. See, for example,  #1053

**Comment by zimeon** [comment]
Have discussed patterns document on 2017-03-15 and agreed to move ahead with it.
