### ISSUE TITLE
Use the Service Pattern for Extensions

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#1045]
As per services.

I think we leave this one out for now, as it's under discussion for 3.0 as to what to do about services.

**Comment by zimeon** [comment]
Agree to leaving out. We note already that be defining success and not failure there are other options for extension too.

**Comment by jpstroop** [comment]
:+1: to leaving out for now. Tagged w/ `defer`.

**Comment by zimeon** [comment]
Have discussed and agreed design patterns document on 2017-03-15 community call, now going to close this as won't be added (in this round at least)
