### ISSUE TITLE
Separate Concerns

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#1047]
(ties into loose coupling, expresses the boundaries)

In the well established pattern of doing one thing well, IIIF specifications try to separate areas of concern as much as possible.

The Image API is a service that can be used to gain access to representations available from a single (abstract) Image. The JSON-LD description describes how to obtain those representations by using the parameters defined, not about the content of what those images depict. The Authentication API allows fine grained control over rights management.

The Presentation API is a description of how to lay out multiple resources, either in sequence or in a single space. It includes text to be rendered to humans, not descriptive metadata.  Descriptive metadata is outside the scope of IIIF work, and referenced from the Presentation API.  The Search API is an information management tool to allow clients to find annotations remotely, without downloading all of the annotation lists to filter through.

Discovery of available resources is a separate concern.

**Comment by zimeon** [comment]
Suggestion for "The Presentation API..." onward:

The Presentation API supports description of how to lay out and relate multiple resources, either in sequence or in a single space. It also supports text to be rendered (with internationalization support), annotations, links to other resources (including metadata for discovery), and links to related services. 

The Search API allows clients to find annotations efficiently, without downloading all of the relevant annotation lists. It also provides a related service for the auto-completion of unknown search terms in the given context.

Neither the Presentation API nor the Search API provide direct support for discovery metadata or discovery processes. Discovery of available resources is a separate concern being addressed by the [Discovery Working Group](http://iiif.io/community/groups/discovery/).

**Comment by jpstroop** [comment]
Versioning is another reason this is important: specs that cover too many broad areas are more difficult to manage and make incremental changes difficult for editors and implementers alike.

**Comment by azaroth42** [comment]
I agree with Jon that this is very very similar to #1039.  Have tried to merge them.  In retrospect I don't think that describing the boundaries of the APIs in the principles is appropriate -- the APIs should define their own boundaries, and the editors and community should be watchful to enforce the scopes.

**Comment by zimeon** [comment]
Have discussed patterns document on 2017-03-15 community call and agreed to move ahead with it (consider covered by the merged "Separate Concerns, Loosely Couple APIs" #1039 principle).
