### ISSUE TITLE
Don't Break Caches

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#1048]
(Ties into level 0 and web architecture)

IIIF specifications are designed to work seamlessly with modern web caching infrastructure.  Specifications will ensure that the representations delivered can be trivially cached by intermediate systems without loss of fidelity or functionality. This is critical for performance.

**Comment by zimeon** [comment]
Yes, 👍

**Comment by julsraemy** [comment]
👍

**Comment by glenrobson** [comment]
Do web caches work with https?

**Comment by zimeon** [comment]
Agreement on 2017-03-15 community call.
