### ISSUE TITLE
Scope Through Use Cases

### ISSUE THREAD

**Issue by zimeon** [IIIF/iiif.io#1050]
Our reliance upon use cases to indicate what complexity is justified is mentioned in #1041 but I wonder whether it is useful to explicitly call out use cases as the way we scope work? Could have a principle along the lines of:

_Documented use cases should be used to scope IIIF specification work and to decide what features to include or prioritize._

**Comment by jpstroop** [comment]
+:100: I think this is one of the key reasons for IIIF's success; people will invest time implementing specifications that solve real (as opposed to speculative, imagined, abstract) problems to which they can relate. I wonder if we should take it a step further and list some criteria that define a well-formed use case? 

(Cf. https://github.com/IIIF/iiif-stories)

**Comment by zimeon** [comment]
No further discussion from review on 2017-03-15 community call
