### ISSUE TITLE
Follow Semantic Versioning

### ISSUE THREAD

**Issue by jpstroop** [IIIF/iiif.io#1053]
Occurred to me while commenting on #1047.

I don't know that we should say "semantic versioning" in the principles because we've applied some interpretations/modifications, but at least a reference to the [Versioning of APIs](http://iiif.io/api/annex/notes/semver/) doc seems like a good idea. Could say something along the lines of:

###  Manage Changes Carefully

Frequent changes to specifications hinders adoption and reduces interoperability. Follow the guidelines described in the [Versioning of APIs](http://iiif.io/api/annex/notes/semver/) note and the [Frequency of Releases](http://iiif.io/api/annex/notes/editors/#frequency-of-releases) section of the [IIIF Editorial Process](http://iiif.io/api/annex/notes/editors/).

**Comment by azaroth42** [comment]
Seems like a process point, like #1043?  Agree it's worth calling out ... but perhaps only via a pointer to the relevant docs?

**Comment by jpstroop** [comment]
Sure, that's fine

**Comment by zimeon** [comment]
Have discussed patterns document on 2017-03-15 community call and agreed to move ahead with it.
