### ISSUE TITLE
Avoid Technology Dependencies

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#1055]
From #1044:

IIIF specifications should avoid placing value on one technology (or format, etc) over another unless there is a clear benefit and it does not pose a significant barrier to entry, e.g., it makes sense to call out jpg as a level 0 requirement because it is beyond ubiquitous, but even implicitly requiring a jp2 on the server side in order to get to level 2 compliance in the image API would be a Bad Thing (™️).

We've done a good job of this to date by abstracting concepts (e.g. we have "scale factors" 1, 2, 4, 8, and 16 not "decomposition levels" 1-5), but it would be great to have a place to point to that explains why that was the approach.

**Comment by zimeon** [comment]
Agreement on 2017-03-15 community call.
