### ISSUE TITLE
community list update

### ISSUE THREAD

**Issue by srabun** [IIIF/iiif.io#1092]
University of Glasgow [gla.ac.uk link] (Historical Music of Scotland [hms.scot link])

**Comment by srabun** [comment]
University of Alberta Libraries	https://www.library.ualberta.ca
Huygens ING (KNAW)	https://www.huygens.knaw.nl/
Hill Museum & Manuscript Library (HMML)	https://www.vhmml.org/
Library of Congress	https://www.wdl.org
NGA	www.nga.gov

**Comment by srabun** [comment]
Cooper Hewitt Smithsonian Design Museum www.cooperhewitt.org

**Comment by mikeapp** [comment]
Nationalmuseum Sweden http://www.nationalmuseum.se
