### ISSUE TITLE
Use rightsstatements.org for license/rights examples in Image API

### ISSUE THREAD

**Issue by zimeon** [IIIF/iiif.io#1094]
Clone of #960 to separate Image API case from Presentation API  case. We agreed that we should use examples from rightsstatements.org as these are likely good statements for our community. In Image API 2.1 we have two examples that include `license` (to be renamed `rights` in v3 #644):

  * http://iiif.io/api/image/2.1/#rights-and-licensing-properties -- example currently has `"http://example.org/rights/license1.html"`
  * http://iiif.io/api/image/2.1/#complete-response -- example currently has `[ "http://example.org/rights/license1.html", "https://creativecommons.org/licenses/by/4.0/" ]`

Tasks:
 * [x] fixed on 2.1.1 branch
 * [ ] merged to master

**Comment by zimeon** [comment]
I propose that we change the first example to use just http://rightsstatements.org/page/InC-EDU/1.0/ , and the second to have http://example.org/rights/license1.html & http://rightsstatements.org/page/InC-EDU/1.0/

**Comment by azaroth42** [comment]
:+1: to proposed solution

**Comment by azaroth42** [comment]
Ready, modulo #1104, fixed in #1105.

**Comment by aisaac** [comment]
Hi, it's great what you've done here!
Just wondering: would it help the reader if more context is given, about where such URIs come from? I was thinking of updating the table at the top of 5.4, replacing 
"A link to an external resource that describes the license or rights statement under which content obtained from the Image API service may be used."
by 
"A link to an external resource that describes the license or rights statement under which content obtained from the Image API service may be used. For example, the standardized licenses and rights statements available at https://creativecommons.org/licenses/ and http://rightsstatements.org/en/statements/"
@anarchivist do you think it would be appropriate on our side?

**Comment by anarchivist** [comment]
As noted on the 12 April 2017 call:

* I'm -1 on **`SHOULD`** for using CC or RS.org statements specifically
* I'm +1 on **`SHOULD`** for recommending that the rights statement identified by URI come from some sort of controlled source of vocabulary

**Comment by aisaac** [comment]
Continuing on noting the discussion on 12 April 2017 call: there is reluctance (especially from @zimeon ) on adding the example in the normative part (table at the top of section 5.4). 
I can very much understand this. I suggested an addition to the table as it was the first, natural place that occurred to me. But I will be equally happy if the sentence giving context for the URIs is added in the body of the text between the table and the example.

**Comment by aisaac** [comment]
I also agree with @anarchivist : For 2.1, I am very fine with the current spec draft, which makes only a suggestion about the use of URIs like the ones of CC and RS.org, not a stronger recommendation.

**Comment by workergnome** [comment]
:+1: for using stating that the URL should be from a machine-readable/dereferencable/from a controlled vocabulary/etc statement.
 :-1: for explicitly SHOULD to any specific vocabularies.
 :+1: to adding a description of CC/RS.org in the _non-normative_ section of the text.
