### ISSUE TITLE
Add thumbnail declarations to the canvas and image resource examples in presentation API specifications

### ISSUE THREAD

**Issue by aeschylus** [IIIF/iiif.io#1098]
It is very beneficial to have thumbnails pre-generated at the canvas level, but it is currently in the "MAY" category. This makes sense, but we might encourage more implementers to provide thumbnails for these nodes if they are featured in the canonical documentation. I'm thinking of the statements here: http://iiif.io/api/presentation/2.1/#thumbnail being given corresponding examples here: http://iiif.io/api/presentation/2.1/#canvas, http://iiif.io/api/presentation/2.1/#image-resources

**Comment by zimeon** [comment]
Examples are certainly a good way to provide a gentle steer. It seems we currently (2.1) have `thumbnail` in just one example: http://iiif.io/api/presentation/2.1/#manifest . Of course the trade-off is size/complexity of examples. In this regard, the [canvas example](http://iiif.io/api/presentation/2.1/#canvas) is currently just a skeleton so it would seem unreasonable to add a whole Image API service object as a thumbnail, would it be helpful or counter-productive to add a simple image URI as thumbnail?

For the [image resources example](http://iiif.io/api/presentation/2.1/#image-resources), wouldn't the `thumbnail` simply be the same Image API service as the image being painted? And thus redundant?

**Comment by tomcrane** [comment]
@zimeon @aeschylus I think it would be helpful to add a halfway house:

```
"thumbnail" : {
   "@id" : "http://example.org/thumbs/mythumb.jpg",
   "@type": "dctypes:Image",
   "width": 150,
   "height: 250
}
```

..from recent work in this area I think thumbnails that don't tell you how big they are aren't much use to real clients. 

On the other hand, my ideal thumbnail looks something like this:

```
"thumbnail": {
  "@id": "https://dlcs.io/thumbs/wellcome/1/8ac70935-b55b-4c6f-89ca-33e6ab9bb161/full/100,62/0/default.jpg",
  "@type": "dctypes:Image",
  "width": 100,
  "height: 62
  "service": {
      "@context": "http://iiif.io/api/image/2/context.json",
      "@id": "https://dlcs.io/thumbs/wellcome/1/8ac70935-b55b-4c6f-89ca-33e6ab9bb161",
      "protocol": "http://iiif.io/api/image",
      "width": 1024,
      "height": 631,
      "sizes": [
         { "width": 100, "height": 62 },
         { "width": 200, "height": 123  },
         { "width": 400, "height": 246  },
         { "width": 1024, "height": 631 }
      ],
      "profile": [ "http://iiif.io/api/image/2/level0.json"  ]
  }
}
```

... and that's inline, for each canvas in a manifest. It offers a choice of known fast sizes and doesn't require an additional HTTP request for an info.json. It allows VERY fast UI (as long as you can serve up the thumbs). But... that's way too big and distracting to go in the example for Canvas in the spec.

**Comment by zimeon** [comment]
Seems that adding the static image thumbnail with size to the Canvas example would be reasonable.

**Comment by zimeon** [comment]
This is low hanging fruit so we should decide for prezi 2.1.1...

**Comment by azaroth42** [comment]
:+1: to adding in the examples for 2.1.1

**Comment by aeschylus** [comment]
To the point about example bloat, I agree it's a tradeoff in general. I wonder if we could work toward having an "additional examples" link beneath each example that directs to a page with more examples curated and thoroughly explained by the community. For example, it is hard to put into words how immensely helpful the d3.js community's [attitude toward](https://bost.ocks.org/mike/example/) [examples](http://christopheviau.com/d3list/gallery.html) has been for me and others over the years.

@edsilv recently created a repo on viewdir to keep the SDIG's jsbins together, and some examples were attached to the most recent workshop gitbook, but perhaps this is another area where community curation can help respond to the "what if..."s, "how do I..."s, and "does it do..."s in a more scalable way (linked from the documentation).

**Comment by tomcrane** [comment]
I hope to have a conversation about thumbnail best practice in the Edinburgh session tomorrow (which is, I think, like a day-long face to face community call for Europeans). Thumbnails seem like a minor detail, but when it comes to building interesting user experiences, they are everything. You don't need to interact with lots of tile sources at once (and if you do, you can do tricks with thumbs until you zoom in far enough) but you do need to present lots of thumbs at once. And they must be fast!

And yes, cookbooks for the win.

**Comment by tomcrane** [comment]
Not sure what a good URI for the thumbnail would be.

**Comment by jpstroop** [comment]
We use a canned image API request, but I can see that confusing users. For the example, I think any old URI is fine
