### ISSUE TITLE
Wrong URI for rightsstatements (vocab, not page)

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#1104]
@anarchivist:
just saw https://github.com/IIIF/iiif.io/commit/5ea386828ef44a7428ef8c4826899704ed0a4ac6 get merged - the rightsstatements.org URI should be `http://rightsstatements.org/vocab/InC-EDU/1.0/`, not `http://rightsstatements.org/page/InC-EDU/1.0/`

**Comment by aisaac** [comment]
Just a warning: the same problem (use of http://rightsstatements.org/page/NoC-NC/1.0/) is also still in the Presentation API http://prezi_211.iiif.io/api/presentation/2.1/#manifest
