### ISSUE TITLE
Update deprecation warning for Ranges

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#1118]
That ranges are likely to change significantly in 3.0?

**Comment by zimeon** [comment]
If we added warning on Ranges, would we also put warnings on other changes related to A/V - such as `images`+`otherContent` -> `content`?

**Comment by azaroth42** [comment]
We do have a deprecation warning already (in http://iiif.io/api/presentation/2.1/#range), and it is opinionated about the outcome of the ranges discussion. Not suggesting that we put in all of the changes, but the current warning is likely no longer accurate.

**Comment by zimeon** [comment]
Ah, indeed. So, should we go with something very simple along the lines of:

> **Deprecation Warning** The `canvases` and `ranges` properties are likely to be changed or removed in version 3.0. Feedback on this [discussion](link) is requested.

(and perhaps have an extra issue to be target of link and aggregate other discussions?)
