### ISSUE TITLE
Current validator cannot handle some UTF-8 content.

### ISSUE THREAD

**Issue by aeschylus** [IIIF/iiif.io#1142]
Today we tried to validate the following manifest: http://demos.biblissima-condorcet.fr/iiif/metadata/florus-dispersus/manifest.json

We received this error: 
![screen shot 2017-04-18 at 15 50 44](https://cloud.githubusercontent.com/assets/145874/25156359/dfc75b74-244e-11e7-9d61-3acdd03d40c0.png)

@versae notes that this is probably a Python 2 error. Are there other utf-8 manifests for which this fails, or is there something wrong with this manifest?

**Comment by zimeon** [comment]
I have tested this manifest locally against the current master branch with python 2.7.11 and 3.5.1 and both report the following error instead:

> Validation Error: Can't add a canvas to a range that is not in the sequence: (http://www.e-codices.unifr.ch/metadata/iiif/sl-0001/canvas/bge-lat0016_0010v.json)

I think the first thing that needs to happen is to get the live validator at http://iiif.io/api/presentation/validator/service updated

**Comment by azaroth42** [comment]
I downloaded, and the above issue that @zimeon reports seems to have been corrected in the mean time as it reads with no problem:

```
>>> from iiif_prezi.loader import ManifestReader
>>> fh = open('unicode_manifest.json')
>>> d = fh.read()
>>> fh.close()
>>> import json
>>> js = json.loads(d)
>>> r = ManifestReader(js)
>>> mf = r.read()
>>> r.get_warnings()
[]
```

Agree the validator needs to be on automated deployment, likely once we get a technical coordinator.
The other issue is whether the representation is being served with the correct HTTP headers for its character set.

**Comment by azaroth42** [comment]
Can someone validate (ha!) that this fixed please?

**Comment by azaroth42** [comment]
Assume that it is.
