### ISSUE TITLE
Typo in Presentation API 2.1 for Image profile URI

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#1170]
Spotted by @regisrob, in two examples the URI for the Image API profile level is `http://iiif.io/api/image/2/profiles/level2.json` rather than what it should be: `"http://iiif.io/api/image/2/level2.json`

Thanks Regis!

**Comment by regisrob** [comment]
:wink:

**Comment by zimeon** [comment]
Thanks @regisrob !
