### ISSUE TITLE
switch all calls to zoom

### ISSUE THREAD

**Issue by srabun** [IIIF/iiif.io#1182]
IIIF Call connection info beginning July 1:
·         IIIF Bi-weekly Community Call - https://stanford.zoom.us/j/356715389
o   Meeting ID: 356 715 389
·         A/V https://stanford.zoom.us/j/538552143
o   Meeting ID: 538-552-143
·         Discovery: https://stanford.zoom.us/j/829945399
o   Meeting ID: 829-945-399
·         Museums https://stanford.zoom.us/j/633505839
o   Meeting ID: 633-505-839
·         Manuscripts: https://stanford.zoom.us/j/674108679
o   Meeting ID: 674-108-679
·         Newspapers: https://stanford.zoom.us/j/948530998
o   Meeting ID: 948-530-998
·         Software devs: https://stanford.zoom.us/j/641742844
o   Meeting ID: 641-742-844
·         Mirador call: https://stanford.zoom.us/j/168558439
o   Meeting ID: 168-558-439
·         Mirador Developers Standup - https://stanford.zoom.us/j/340409741
o   Meeting ID: 340 409 741
·         Text Granularity – TBD – please complete the doodle poll for scheduling: http://doodle.com/poll/e49ru9sk4hwanavy

**Comment by srabun** [comment]
Branch: changing_to_zoom

**Comment by zimeon** [comment]
Fixed by #1184
