### ISSUE TITLE
Is manifest.structures ordered?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#1193]
The `structures` property of a Manifest in 2.x is described as a list, because it was a flat array of the named ranges. In the context it is given as `@container:@list`.  But what is the reason for the ordered-ness?

I believe that it should be just `structure` and `@container:@set` -- there's no semantics for the ordering of the ranges as referred to from the manifest described anywhere.

**Comment by zimeon** [comment]
I agree that `structures` should be described as a set in the text and defined as `@set` in the context for 3.0.

I think the impact of this is that if there are multiple `Ranges` with `"viewingHint": "top"` (see [notes](http://iiif.io/api/presentation/2.1/#viewinghint)) defined within `structures` then a linked-data client would have no order defined to use to present the choice of navigation structures to the user. That seems like a real edge case so the simplicity of `@set` is better.

**Comment by mikeapp** [comment]
I believe the need for predictable order when there are multiple `"top"` elements may be more than an edge case.   For example, @jeffreycwitt is contributing tables of contents to a repository.  The repository owner may wish to place their locally-produced structural information before or after Jeff's.   In some of the AV cases we've discussed the need for physical and logical ordering (side A/B  vs. Act 1, 2, etc.), and I suspect publishers will have a preference as to which appears first.

**Comment by azaroth42** [comment]
Seems like a good answer to me :) We should document the expectation that the order will be used for prioritizing, similarly to the order of Sequences.

**Comment by azaroth42** [comment]
Leaving as it is. Closing `invalid`.
