### ISSUE TITLE
Typo in Prezi 3.0 Alpha Draft

### ISSUE THREAD

**Issue by julsraemy** [IIIF/iiif.io#1211]
In 4.4 there is a typo in french: 

> "fr": ["Voici le description de l'objet en français"]

Should be (as 'description' is a feminine word)

> "fr": ["Voici **la** description de l'objet en français"]

PS: I'm sorry if this isn't the standard way of creating issues on this repo.

**Comment by azaroth42** [comment]
Thanks! Fixed :)
