### ISSUE TITLE
News index page features?

### ISSUE THREAD

**Issue by jpstroop** [IIIF/iiif.io#148]
It's just a list right now. Things to consider:
 * category filters
 * date filters
 * paging
 * should there be an excerpt?

**Comment by azaroth42** [comment]
Propose that we close this and leave it up to any future website redesign/review to make progress or not.

**Comment by jpstroop** [comment]
:+1:

-Js

Sent via mobile. Please excuse typos, brevity, etc.

**Comment by azaroth42** [comment]
I guess as non-spec, that's sufficient to close :) Can re-open if there's objections.

**Comment by zimeon** [comment]
belated :+1:

**Comment by tomcrane** [comment]
:+1:
