### ISSUE TITLE
Search API examples import Prezi3 context, which doesn't have OA mapping

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#1973]
The example AnnotationList in Search 1.0 (https://iiif.io/api/search/1.0/#simple-lists) uses the Presentation 3 API context, as it pulls in the site wide presentation major version variable.  However this is not valid, as Prezi3 does not use the Open Annotation model, nor AnnotationLists and so forth. 

It should be updated as part of the search TSG ... but should it also be fixed to point to v2 in the 1.0 documentation?

**Comment by azaroth42** [comment]
c.f. #1888

**Comment by glenrobson** [comment]
Issue caused by page variables e.g.:

```
"@context":"http://iiif.io/api/presentation/{{ site.data.apis.presentation.latest.major }}/context.json",
```
and should be hard coded to 2

**Comment by digitaldogsbody** [comment]
_All_ links to presentation API should point to 2.1 for consistency.
