### ISSUE TITLE
find new term for `label` in the Search API Auto Complete Response

### ISSUE THREAD

**Issue by mixterj** [IIIF/iiif.io#2052]
The Search API Auto Complete (https://preview.iiif.io/api/search-v3-alignment/api/search/2.0/#autocomplete) Response data (https://preview.iiif.io/api/search-v3-alignment/api/search/2.0/#response) defines the use of `label` as a string which conflicts with its use as a language map. In this situation it is more than likely just a string. To avoid conflict, we need to define a new term for `label` in this context.

**Comment by mbennett-uoe** [comment]
TSG call: Can we update this to use a language map with `@none` when the language is unknown?

**Comment by digitaldogsbody** [comment]
Related to discussion in #2054 about redefining terms used

**Comment by azaroth42** [comment]
Discussion about label of resource being separate for alternate form of the match value.

**Comment by azaroth42** [comment]
Related language issue https://github.com/IIIF/api/issues/513

**Comment by digitaldogsbody** [comment]
Remaining changes:

- Update example to convert string to array for none.
- Update sentence about label to indicate usage of language map pattern (Prezi3 4.4)
