### ISSUE TITLE
incorrect context in Search 1 section 3.3.3

### ISSUE THREAD

**Issue by mixterj** [IIIF/iiif.io#2056]
The context in the Search API section 3.3.3 (https://iiif.io/api/search/1.0/#target-resource-structure) should be the Prezi3 context - http://iiif.io/api/presentation/3/context.json - which is used in the other normative examples

**Comment by mbennett-uoe** [comment]
Echoing my [comment on the PR](https://github.com/IIIF/api/pull/2057#discussion_r727573023) - my recollection is that I left this with just the Search context pending working out how we were going to treat the clashing definitions of `label` in Prezi3 and the WebAnno spec.
