### ISSUE TITLE
Bounds for annotation rendering

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#207]
Should be able to specify when an annotation is appropriate to render.
Eg at a certain zoom depth or viewport size.  This would solve the issue of transcriptions being rendered on thumbnails or larger-than-thumbnail-but-not-large-enough-to-read-the-text images.

Other use cases would be medical imaging, electronic PCB images with rich annotations, or just commentary on small sections of images.

**Comment by azaroth42** [comment]
Interesting but no one is clamoring for it, no viewers ready to implement and no providers ready to include in manifests. Pushing to 2.2

**Comment by azaroth42** [comment]
Propose `close` `wontfix` until someone at least attempts an implementation. This seems very unlikely to hit two implementation requirement ever.

**Comment by zimeon** [comment]
:+1: on `wontfix` until we have clear use cases

**Comment by azaroth42** [comment]
Discussion at the Hague that there's no implementation and any implementation would be client side anyway. Closing, wontfix
