### ISSUE TITLE
Additional REST API Features

### ISSUE THREAD

**Issue by jpstroop** [IIIF/iiif.io#21]
Decision: Incubate, possibly as an extension or annex to the spec. See [here](https://github.com/IIIF/specifications/blob/master/image_api/rest_extension.md) for a start.

**Comment by azaroth42** [comment]
Discussion at the Hague was to continue to defer C/U/D of IIIF resources.

**Comment by jpstroop** [comment]
Six years on, closing as use cases have not emerged and those that have seem to be covered by Discovery and Content State.
