### ISSUE TITLE
Presentation "Lite" profile?

### ISSUE THREAD

**Issue by jpstroop** [IIIF/iiif.io#222]
Indicates that the server supports a limited amount (i.e the most common, TBD) of Presentation API features, maybe uses some shorthand or requires the client to makes some assumptions, etc.

cf. #76.

**Comment by azaroth42** [comment]
Un-defer or push to 2.2?

**Comment by zimeon** [comment]
push to 2.2

**Comment by jpstroop** [comment]
+1

**Comment by azaroth42** [comment]
See proposal to close #76 and #99.

**Comment by jpstroop** [comment]
Sorry, you're suggesting we close  #76 and #99 in favor of this issue? If so, that's fine w/ me.

**Comment by azaroth42** [comment]
I suggest closing all of them.

**Comment by zimeon** [comment]
I agree, close all. Not driven by use case or informed by sufficient experience

**Comment by mikeapp** [comment]
👍 to closing all

**Comment by jpstroop** [comment]
:+1: to close. I remember the the conversation around this and I don't think it's relevant anymore.

**Comment by zimeon** [comment]
Discussion at The Hague: We think that "lite" profiles will be different for different content/formats and are likely best done as best practices by interest groups. Do not think that formal levels can be generally specified. Close wontfix.
