### ISSUE TITLE
Add ability to flip/invert/mirror image

### ISSUE THREAD

**Issue by jpstroop** [IIIF/iiif.io#228]
Do with a bang on rotation. Use cases: negatives, reflection, bleed through of ink.

Optional.

**Comment by puik** [comment]
But still, what about **inverting colors**?
Often there are negative images (of for instance glass plates negatives) in repositories and it would be very useful to make the images _human readable_ by inverting these.

**Comment by zimeon** [comment]
@puik -- Your comment seems a separate issue, have created #1161 instead of using this closed thread
