### ISSUE TITLE
Encourage a PHP implementation

### ISSUE THREAD

**Issue by doktorbro** [IIIF/iiif.io#252]
Related to my [unanswered question](https://github.com/IIIF/image-api/issues/1) I would like to have a PHP implementation of the image resizer. This would push things forward, because _everybody_ could use it. My PHP skills are limited, so I can’t implement it.

There are many resizers in the wild with arbitrary apis. We could create a new repo `iiif/image-php` and invite some of these authors to work together on this one. The most notable project to start of is [Imagine](https://github.com/avalanche123/Imagine) maintained by @romainneutron.

What do you think about it?

**Comment by mistcat** [comment]
Is this implementation the latest and greatest PHP one?  https://github.com/digirati-co-uk/iiif-php
