### ISSUE TITLE
Call Notes Section?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#264]
Should we have a section for call notes?
Currently there's a call notes item in news, but that would generate a lot of news items.  I'd prefer to keep news for actual news, and discussion summaries and links elsewhere.

We could:
* Create a new section that has links to iiif-discuss, any irc channel that's actually populated, plus call notes and so on.
* Just put the call notes on iiif-discuss which has enough links to it already.

Thoughts?

**Comment by azaroth42** [comment]
Propose linking to the google drive folder from the site in the Community page.

**Comment by zimeon** [comment]
Can we have a procedure where we freeze the notes to read-only after a few days (or when we remember at the next call)?

**Comment by jpstroop** [comment]
Yes, we should try to do that to keep the notes from getting spammed.
