### ISSUE TITLE
Criteria for IIIF/ repositories

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#275]
Other than the iiif.io website, the IIIF organization should have criteria for which projects it can or should host.  At the moment, there's a mixture of community and personal IIIF specific repos, some related things, and demo code.

The currently proposed criteria are:
- Implements IIIF APIs
- Expressed intent is to provide complete support, not partial
- Expressed intent is to keep up with the latest version of the APIs as they evolve
- Has at least two community members actively contributing, preferably three or more
- Welcomes additional contributors, particularly from within the community
- Generally reusable rather than being tied to specific platforms or local concerns
- Responsive to issues and pull requests, regardless of their source
- Open source and uses an agreed upon, common license
- Recognized to be of sufficient quality by "IIIF committers"

Once decided, the information should be promoted on the website.  Before that it should also be discussed on iiif-discuss as well as here.

**Comment by azaroth42** [comment]
Ping. I think this is becoming more important with the expansion of the community and the formalization of IIIF-C.  Secondly, I think most of the current repos under IIIF do not come close to meeting the requirements, including Mirador (no expressed intent to keep up with anything) and my python reference implementations (only one committer).

**Comment by zimeon** [comment]
One could write some expectations (weaker word than criteria) for new requests, but then grandfather existing repos

**Comment by azaroth42** [comment]
Propose close no-one-else-cares-enough.

**Comment by jpstroop** [comment]
:+1: I hate to wait for an issue to surface, but I don't have any clear ideas around what the scope should be at this point.

**Comment by azaroth42** [comment]
I suddenly care more about this :stuck_out_tongue_closed_eyes:

**Comment by zimeon** [comment]
I favor a minimalist approach to what is added under IIIF/ -- focus on thing owned/managed/done-under-the-auspices-of the IIIF. This would include from the current list: iiif.io, iiif-stories, showcase, at least the validators in image-api and presentation-api, parts of auth, newspapers.

I think the correct approach to publicizing for other work is a clear set of instructions for suggesting PRs to add/update a list on the website. Eds that handle accepting/rejecting based on a criterion of "of likely interest/use for IIIF implementers or users",

**Comment by mikeapp** [comment]
I agree with @zimeon that it is best to keep IIIF/ focused on what's owned/managed and maintained with a long term commitment by the organization, and that this implies the repos above.

**Comment by jpstroop** [comment]
I agree in principal, but I also think there's a distinction to be made between well tested, production-ready code that is broadly useful, and experimental implementations made for intent of testing and developing the APIs. To me this is a slightly broader category.

My selfish concern is for osullivian (the iiif-presentation gem). I can move it back to my own repo, but I have a feeling it would get less attention there, and a lot of people are using it at this point, even though I'm not necessarily in a place to maintain it.

**Comment by azaroth42** [comment]
I think this can be closed? IIIF/ is now only iiif community work, and no implementations.  Should _that_ decision be documented somewhere?

**Comment by zimeon** [comment]
Agree close, "has been fixed elsewhere". I think you just did document the current practice

**Comment by azaroth42** [comment]
Okay, closing. Issue rendered invalid :)
