### ISSUE TITLE
Feedback from Google:  Compression necessary

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#294]
In a discussion with a Google image specialist, the use cases for compression were discussed.

* Speed, speed, speed. Products have a latency threshold over which they're not allowed to launch.  Very important for mobile, and rural internet.
* Internal use of the APIs also important, not just inter-institution. 
* Some objects can have much better experience with non standard compression, for example, a book cover as distinct from the book pages.

The parameter must be optional and format specific.  PNG doesn't have a compression feature, for example, and different formats have different capabilities and semantics.  The recommendation was not to try and come up with a format neutral value, but instead to tie it explicitly to the output format.

A possible method might be to have a non "/" delimiter after format. That could be ? and then regular CGI params, as they're optional anyway, or it could be baked into the URL structure.

The google Image function documentation is interesting:
   https://developers.google.com/appengine/docs/python/images/functions
Having an implementation that uses this would be another good thing to do.

**Comment by azaroth42** [comment]
Editors agree it should include in 2.1 with one of two options:
 * "low" as a fifth quality
 * multiply the current 4 qualities by adding "Low" to the end

**Comment by azaroth42** [comment]
To be discussed in DC.

**Comment by jpstroop** [comment]
locolor and [logray](http://img3.wikia.nocookie.net/__cb20130422035557/starwars/images/3/3b/LograyHS-ROTJ.png)? :wink:

**Comment by jpstroop** [comment]
Feedback from tech group @ GW:
 * Use cases are weak
 * W3C responsive images work may help inform
 * Other APIs to have a notion for compression
 * What compliance level?
 * ~3/4 of the room preferred one new quality approach

Bring this up on IIIF-Discuss

**Comment by anarchivist** [comment]
Related links: 

* [Responsive Image Community Group](http://responsiveimages.org/) use cases, especially http://usecases.responsiveimages.org/#user-control-over-sources
* [Review of apps that use network information](http://www.w3.org/TR/netinfo-usecases/) from [W3C Web and Mobile IG](http://www.w3.org/Mobile/IG/)

**Comment by azaroth42** [comment]
Links are good ... but don't actually ever refer to compression for images with any real use cases.  Maybe it's taken for granted as a good idea, but I'd like to hear from real IIIF users as to what they need it for.

**Comment by tomcrane** [comment]
Use case for high resolution plus high compression JPEGs: https://groups.google.com/forum/#!topic/iiif-discuss/XN3NeA0-jB0

I think this is a compelling use case that asks for pixels that would probably not be the default.jpg tiles you'd want to show in your library or museum discovery viewer, but are not grey or bitonal either.

**Comment by jpstroop** [comment]
I tend to agree w/ @tomcrane. It's a lot more URIs for caches, but probably won't get tons of use. so:

default
color
gray
bitonal

default.low
color.low
gray.low
bitonal.low (?)

default.high (or .best?)
color.high
gray.high
bitonal.high (?)

I'm not sure what compression does to bitonal images. I'll try to run some tests later today, but can't promise I'll get to it.

**Comment by zimeon** [comment]
It still seems that we don't have multiple use cases for the same sort of compression so it is not clear to me that `low` will do the job, and then we have awful trouble parameterizing. I assume that we imagine a client grabbing `info.json` before attempting to get a compressed image. With that in mind, what about having the possibility of a more complex and extensible parameterization _in `info.json`_ mapping to a new quality term of the server's choosing? (This might also be extended to account for the case of linking to an alternative image (ala auth) at a different resolution.) Could be something like:

```
  "qualities" : [ "color", "gray", 
                       { "quality": "trans", \\ required, maps to request
                         "formats": [ "jpg" ], \\ optional, if specified applies only to listed formats
                         "use": "High-resolution low-quality for transcription work", \\ optional
                         "jpeg_compression": "80", \\ optional params, could be specific to formats
                         "profile": "https://iiif.io/low" \\ optional, could have some defined profiles for given uses
                       } 
                     ]
```

and then support `/0,0,1024,1024/full/0/trans.jpg`. Of course, if one bloats `info.json` too much then that could be an issue...

**Comment by jpstroop** [comment]
I have two problems w/ this:
 * `use` would not be possible to extract from the image (we've bent this a little bit by adding rights information, but at least that _could_ be in IPTC metadata.
 * `"jpeg_compression" : "80"` is meaningless. 80 whats? And 80 whats relative to what (e.g. if the source image was already compressed)?

**Comment by zimeon** [comment]
I guess I should not have given specific examples, but to generalize around your comments:

  * I put `use` to suggest that one could allow an optional description of the compression regime
  * I put `jpeg_compression` to illustrate a format specific parameter. Although perhaps not realistic, a possible internally consistent meaning could be that this quality is 80 times smaller than the `default` quality (as `jpg`).

I kinda hope we might find terms for describing compression from somewhere else, but I don't know where.

**Comment by jpstroop** [comment]
There are so many factors w/ compression, I think it's going to be tough to be very specific. Some images compress better than others (drawings and etchings tend to compress badly, for example), what a number or quality like 'high', 'medium', 'low'; actually means is fuzzy (based on [this article](http://www.imaging.org/ist/resources/tutorials/inside_jpeg.cfm) I think it informs a scale factor for the quantization table).

Having the value...whatever it turns out to be...be relative to `default` is a good way to keep from breaking our semantics (i.e. it can't be relative to the source image since that doesn't exist) is good idea. :+1: to that!

**Comment by zimeon** [comment]
API review at The Hague, issue stale and without compelling use cases or experimentation. Close wontfix
