### ISSUE TITLE
Dynamic Annotation List Service

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#39]
Requested Feature:  A service profile that allows a manifest to record dynamically generated annotation lists, or lists of lists.  The service could determine the user, and present further annotations that they have access to but are not part of the "official" facsimile.  

The response would be an sc:AnnotationList, as currently defined, or like "otherResources" in the canvas.

Questions remain as to:
Should there be one service per canvas, and if so does the current spec not suffice?
Should there be one service per Manifest, and if so:
Should it be called once per Canvas (and if so, what's wrong with current spec beyond having to repeat the same field per Canvas?)
Should it be called once per Manifest, with the response containing annotations for all of the Canvases?
Are there additional parameters or requirements for the call that need to be added?

Notes:
 * Agreed for further discussion

Action:
 * Discuss on IIIF-Discuss

Proposal:
```
service: {
  "@id" : "http://.../service?canvas=asdf", 
  "profile" : "http://.../annotationListService"
} 
```

**Comment by azaroth42** [comment]
Propose that this, like audience, is just search, and should be discussed in that context.

**Comment by azaroth42** [comment]
Decided it is just search.

**Comment by azaroth42** [comment]
So we broke it...

**Comment by aeschylus** [comment]
Agreed that it is best left search-based. As an outcome of the design meeting last week, we will be implementing a layer-based interface in Mirador for transcription next week, in which the user "opens" a "layer" for viewing, and advancing to the next canvas keeps the associated list from that layer displayed. To clarify none of this is "dynamic" in the search sense, but we'll report back here as to limitations we bump up against using layers and annotation lists.

One conceptual problem we encountered was how to associate a list with a page. The layers field can have a list of lists contained in that layer, but one must then filter the contents of those lists to extract the annotations pertaining to different parts of the manifest. This requires dereferencing and parsing all lists before any summary of their association can be rendered for the user (such as an indication of which canvases have annotations). An approach we developed, which may be wrong, is to list annotation lists on each canvas and use the "within" property to point to the associated layer. This makes it possible to populate the interface without dereferencing anything until its full content is needed.

I'm not sure how which of the dynamic list services would best mitigate this summary problem of needing to know what exists at an overview level.

**Comment by azaroth42** [comment]
@aeschylus Canvas -> AnnotationList -> Layer, like in the example in the docs? :wink:
See: http://iiif.io/api/presentation/2.0/#layers

**Comment by azaroth42** [comment]
I think this is now closed by search. @mikeapp?

**Comment by mikeapp** [comment]
I agree, we can close.
