### ISSUE TITLE
two-up viewing hint?

### ISSUE THREAD

**Issue by jpstroop** [IIIF/iiif.io#419]
Can't believe I didn't think of this earlier...

We have several volumes from our art library with illustrations that span two pages (verso of one, recto of the following), e.g. "Image 20" and "Image 53" here:

http://pudl.princeton.edu/boundart.php?obj=pg15bd93g

Rotation issues aside, this item could be presented in a page turner interface if we could account for the "two-ups" (as our studios call them), similar to the way we account for duplicates and whatever other weirdness that occurs with the "non-paged" viewing hint.

We don't have another solution for this, do we?

**Comment by zimeon** [comment]
Examples:

1. Case above occasional center-fold scanned pages
2. Princeton east Asia books are all digitized as front cover, double-pages, back cover

Why not create separate canvasses for the left-side page and right-side page of a double page scan? Except for the optimization/convenience issue, the key reason is that often double page scans are not perfectly aligned with the centre and thus cannot be accurately split.

**Comment by azaroth42** [comment]
Proposal:
"viewingHint": "facingPages"

Applies only to paged resources.

**Comment by jpstroop** [comment]
[Don't do this](http://pudl.princeton.edu/viewer.php?obj=kh04dr094&vol=v1phys&log=v1log#page/21/mode/2up). :+1: to facingPages

**Comment by regisrob** [comment]
That's definitely useful. The BnF has several cases of course, e.g. for maps covering two pages in some manuscripts:
http://gallica.bnf.fr/ark:/12148/btv1b6000547t/f7.planchecontact
http://gallica.bnf.fr/ark:/12148/btv1b55002477x/f1.planchecontact
If I understand well "facingPages" could not be applied to documents that are fully "non-paged" (for instance double-page digitized documents like this one: http://bvmm.irht.cnrs.fr/consult/consult.php?reproductionId=5661). In this case all the canvases should be treated as "individuals"? Am I correct?

**Comment by azaroth42** [comment]
@regisrob Yes, if all of them are doubles, then just use individuals, as you can never do page turning.

**Comment by regisrob** [comment]
ok thx! :+1: to facingPages, only for paged documents

**Comment by jpstroop** [comment]
:+1: from Tech group @ GW

**Comment by jpstroop** [comment]
Closed by _some_ commit
