### ISSUE TITLE
SharedCanvas Zones in IIIF

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#42]
Requested Feature:  MITH use Zones extensively in the Shelley Godwin Archive from the Shared Canvas ontology.  These are not available in the IIIF Metadata specification, and hence are preventing them from adopting it.  University of York also need it (2/26)

Notes:
- Zones are separately manipulable regions (like a mini-canvas on top of another canvas) - think spinners, volvels, parts of letters, paste-downs, fold-outs, etc.
- Discussion is required as to whether, and if so how, to do this.
- IIIF _should_ engage with this issue
- Defer further discussion. Rob will put forward proposal “sooner” than next IIIF meeting.

**Comment by azaroth42** [comment]
Propose to discuss with @edsu as the representative of MITH, who have the most compelling use case.

**Comment by azaroth42** [comment]
Given current thinking of removing Zones completely and just allowing canvases to be annotated onto canvases ... I propose `close` `wontfix`.

**Comment by jpstroop** [comment]
:+1: Do we need a SharedCanvas label?

**Comment by azaroth42** [comment]
@IIIF/editors Other +1s to closing the issue?

**Comment by azaroth42** [comment]
AV Call on 8/8/17:  Propose to close (+1s all round, including @azaroth42 @mikeapp) Unless @jpstroop @zimeon @tomcrane object?

**Comment by jpstroop** [comment]
👍 close wontfix

**Comment by azaroth42** [comment]
Closing in favor of #1191.
