### ISSUE TITLE
How to get a square with the aspect ratio preserved?

### ISSUE THREAD

**Issue by jpstroop** [IIIF/iiif.io#425]
i.e. make square thumbnails without getting the info.json first. SUL and Klokan have the use case. There isn't a way to do this presently.

**Comment by zimeon** [comment]
Discussion on IIIF Discuss call:
  * Want to be able to get square thumbnail without having to first get info.json
  * Proposal: have named region ‘square’ which preserves short edge, server choice of position on long image (probably centre if no better info available on server)
  * Question about why current !w,h does not meet the need for a good square thumbnail: can’t do nice    CSS to get a good square for unknown source, and bad results with very long-thin images like scroll. 
  * Discussion on better use of background-size:cover in CSS to give good results… not clear that this can get around not getting inso.json
  * Would have to be level2+ compliance to avoid being a breaking change
  * Some +1’s, no -1s => agreed to add in Image API 2.1

**Comment by klokan** [comment]
The summary of the related discussion from the different sources is available at:
https://github.com/IIIF/iiif.io/issues/450

**Comment by klokan** [comment]
I am sorry for the confusion. This ticket is suggesting to:

Extend the **Region** (http://iiif.io/api/image/2.0/#region) paragraph of the Image API with:

Form | Description
---- | -----------
`square ` | Return a square image that preserves the short edge of the content. The square is centered at a point of the server's choosing.


The alternative approach changing **Size** via `~w,h` is described at: https://github.com/IIIF/iiif.io/issues/450

**Comment by azaroth42** [comment]
Slightly different wording, but the same idea:
    http://image-auth.iiif.io/api/image/2.1/#region

**Comment by jpstroop** [comment]
Tech meeting @ GW approves. What level of compliance?

**Comment by azaroth42** [comment]
I propose required at level 2.

**Comment by zimeon** [comment]
I'm torn between level 1 and level 2. Perhaps required at level 2 for now with the option to reconsider later if this turns out to be widely used.

**Comment by jpstroop** [comment]
Making it anything other than optional is a breaking change. I'm OK w/ level 1 in 3.0.0

**Comment by azaroth42** [comment]
Hrm.  I guess this is the trouble with only having MUST at different levels and not SHOULD.

Perhaps we can clarify our interpretation of semver a bit.  We're not breaking anything backwards ... everything that you could do in 2.0 is the same in 2.1, you just have another requirement that 2.1 servers MUST support at level x compliance.  So I don't think it's a breaking change, as everything is *backwards* compatible ... just not forwards compatible in that a 2.0 server will not fulfill all of the requirements that a 2.1 server has.

We could annotate new requirements in the compliance doc as to which version they were introduced at.

**Comment by zimeon** [comment]
@azaroth42 - yes, this is the way I like to think about what a breaking change is: In going from x.y to x.(y+1) we expect that any x.y client will work with any x.y or x.(y+1) server. I think this is what our statement "MINOR version increment indicates addition of functionality in a backwards-compatible manner" means. Any addition of functionality means that a client assuming/needing the new functionality will not work with an older server.

In this model, adding a requirement for support of the new feature doesn't seem breaking, but somehow the notion of changing the compliance levels perhaps still is...? or is at least fuzzy?

**Comment by azaroth42** [comment]
Pinging thread...

@azaroth42:  2
@zimeon: 1 or 2
@jpstroop: Optional in 2.x, 1 in 3.0

@mikeapp @tomcrane Others?

**Comment by jpstroop** [comment]
@jpstroop reiterates that anything other than optional in the 2.x.x series introduces a breaking change.

**Comment by azaroth42** [comment]
Re-reading #470 where we agreed on Optional due to compliance being major only... and thus changing my opinion to follow @jpstroop.  From that thread @zimeon also seemed okay with it too. 

Barring additional input, I propose that we run with it.

**Comment by barmintor** [comment]
Just wanted to thank the editors for taking this up: We've been using a local extension to the 2.0 spec for this (we call the named region 'featured', but it's the same). In addition to scrolls, it's been useful to name algorithmically generated thumbnail regions for smaller objects photographed on light tables, book pages with large amounts of whitespace, etc.

**Comment by jpstroop** [comment]
Closed in 9ac188dc31259acd133e2181f2536adb7c46c17a
