### ISSUE TITLE
indexingHint

### ISSUE THREAD

**Issue by jpstroop** [IIIF/iiif.io#438]
I'd like to be able to have my rich client include schema.org tags, or just enough semantic information to do simple indexing:

```javascript
"metadata": [
    {
        "label":"Author",
        "value":"Anne Author",
        "indexingHint": "schema:author" // or ["schema:author", "dc:creator"]
    }
]
```

**Comment by azaroth42** [comment]
Is indexingHint value a string or a resource? If it's a resource, then we would need to include at least schema in the context.  If it's a string ... how does a machine know what "schema" refers to.  Just stuff a bunch of common ontologies into the context and list them in the documentation?

**Comment by jpstroop** [comment]
Resource. We should import schema, probably already have dcterms.

-Js

Sent via mobile. Please excuse typos, brevity, etc.

**Comment by zimeon** [comment]
+1 to must be a resource.

If author is string then dcterms:author would not be correct (range is resource), would have to be dc: or schema:

**Comment by jpstroop** [comment]
Yes, `dc:` and not `dcterms:`. Although I think we should stay as silent as we can I what properties to use (we'll need to provide an example so we can't stay completely silent, and I would tend toward using `schema:` in the example).

However, I don't know that `"value"` is implicitly the object of the a triple built using `"indexingHint"` as a predicate, and therefore I'm not sure that the string in `"value"` has to adhere to the range of the `"indexingHint"`.

Maybe it does...thoughts?

**Comment by azaroth42** [comment]
Use cases:
  * insert schema.org into the display for the resource
  * discovery after harvesting manifests with local search service (lightweight indexing)

**Comment by zimeon** [comment]
Ref in spec for current description of `metadata`: <http://iiif.io/api/presentation/2.0/#descriptive-properties>

**Comment by azaroth42** [comment]
Merging pairs can be solved by using the same label for each pair and client side re-merge. And fallback is that you get the label repeated a bunch of times which is not ideal but not wrong.
Local links are out of scope for interop.
Discovery is out of scope for presentation api, you should use seeAlso pointing to a real metadata record with real semantics.
Schema.org is part of HTML -- google aren't consuming the JSON directly, so it could be added internally and then ignored by clients.

So decision is defer until working demos and further requirements.

**Comment by azaroth42** [comment]
Given #442 I propose to close this, wontfix.

**Comment by jpstroop** [comment]
I still think the schema.org case is compelling. I'm happy to defer until a use case other than mine surfaces (and/or I actually get around to implementing it), but I'd like to see us keep this on the back burner rather than closing.

**Comment by anarchivist** [comment]
Use case from DPLA: providing indexing hints to map existing metadata to elements in the DPLA MAP, to help define a predictable way to expose just enough descriptive metadata in a manifest to allow for harvesting once work proceeds on #465.

**Comment by anarchivist** [comment]
(FWIW, the DPLA MAP mostly pulls descriptive metadata terms either from DCTERMS or DCMES.)

**Comment by zimeon** [comment]
@anarchivist - wouldn't your use case be better served by a link to the plain DCT/DC metadata or data already expressed according to DPLA MAP? I see the presentation API metadata as (typically) derivative metadata selected to drive the viewing experience and not well suited to harvesting use cases.

I also note that the DPLA MAP has properties with cardinality >1, such as creator. Although I don't see any discussion in the current presentation API document my sense is that for a multi-author image, the best practice would be to have one metadata entry like:

```
"metadata": [
    {"label":"Authors", "value":"A Author and B Author"}
]
```

rather than 

```
"metadata": [
    {"label":"Author", "value":"A Author"},
    {"label":"Author", "value":"B Author"}
]
```

**Comment by azaroth42** [comment]
Re cardinality, I think we are intentionally silent, as it's intended for
humans.  If one institution wants to have them displayed as Author: A, and
Author: B ... great.  If another wants them to be Author: A and B, then
great, they can do that too.

So I don't think there is a best practice for one or the other.

**Comment by jpstroop** [comment]
Indeed! Let's stay silent (thus enforcing clients to type-check, but I think that's OK). I would have done:

```json
"metadata": [
    { "label" : "Authors", "value" : [ "A Author", "B Author"] }
]
```

**Comment by zimeon** [comment]
Yes, I was not suggesting that we should be anything but silent! However, I would also group things as Jon suggests because of likely better rendering to the user... so this impacts connection with @anarchivist's use case.

**Comment by azaroth42** [comment]
Given discussion re discovery in Ghent, is this still defer, or close wontfix?

**Comment by anarchivist** [comment]
I'm feeling less sanguine about this meeting my intended use case, so I'm actually fine with `wontfix`.

**Comment by zimeon** [comment]
I agree that the drive from discovery discussion in Ghent is that there will need to be links to "real metadata" (tm) to meet many of the use cases described. I thus also lean toward `wontfix` as `indexingHint` would not get us far enough to meet the discovery use cases

**Comment by azaroth42** [comment]
Propose close wontfix, that we can agree that the seeAlso pattern covers the use cases.

**Comment by zimeon** [comment]
I remain on the side of close wontfix -- while it is an appealing trick that would get us part way there with little effort/infrastructure, I think it would create an nasty path dependency that would leave us _stuck part way there_.

**Comment by mikeapp** [comment]
:+1: close wontfix
