### ISSUE TITLE
Make non-painting annos SHOULD for @id

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#439]
So they can be replied to.

**Comment by zimeon** [comment]
Based on implementer comment from reading spec that non-painting annos would have and @id, coming across ones that didn't caused problems... need clarity

**Comment by azaroth42** [comment]
Editors agree. Add sentence in 7.7 to this effect, noting reason why it's NOT also for other (painting) annotations.

**Comment by jpstroop** [comment]
Consensus from tech group @ GW preferred a MUST, but this would be a breaking change. SHOULD for now, MUST in 3.0.

**Comment by jpstroop** [comment]
Closed by e1b32579a428f32439e51e31875413469f80f258
