### ISSUE TITLE
Scale Factors should be *positive* integers

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#446]
Rather than just vanilla integers. /0 is not your friend.

**Comment by zimeon** [comment]
nor -1.

I agree that adding *positive* to the current spec would be an improvement of clarity (but note that this might change depending on #447 )

**Comment by jpstroop** [comment]
+1 from tech meeting @ GW

**Comment by zimeon** [comment]
Was fixed in cc188c69fe27c3a3ddac4013b2120757923e6553
