### ISSUE TITLE
Mention protocol-less relative URLs as explicitly legal

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#448]
You can omit the protocol from a relative URI and it's legal according to 3986.  This solves the HTTP/HTTPS issue of not having to create multiple representations that are identical other than the protocol in absolute URIs.

Need to experiment but the links below make me think this is both legal and supported.

References:
- http://tools.ietf.org/html/rfc3986#section-4.2
- http://www.w3.org/TR/json-ld/#iris
- http://www.w3.org/TR/ldp-bp/#use-relative-uris
- http://stackoverflow.com/questions/3583103/network-path-reference-uri-scheme-relative-urls

**Comment by azaroth42** [comment]
I think we need to solve this along with the mixed passive content issue for images.  Premature at this stage to introduce protocol-less URIs... we would at least need some significant testing.  Propose defer.

**Comment by jpstroop** [comment]
To clarify, this does not solve passive-mixed-content issues

**Comment by jpstroop** [comment]
Discussion at GW: agreement to defer for now but would be good to do some more experiments to better understand the issue

**Comment by azaroth42** [comment]
Propose that we can instead recommend that clients try a HEAD on HTTPS once per host to see if it responds. If so, s/http/https/ for all URIs that have that host.
Then we close wontfix this issue.

**Comment by azaroth42** [comment]
Further comments on close wontfix?

**Comment by azaroth42** [comment]
Discussion on call 08/02/17: Now considered an anti-pattern with the broader availability of https.  

Closing, wont fix.

**Comment by mejackreed** [comment]
Paul Irish's original advocation of protocol relative URL's and the reversal: https://www.paulirish.com/2010/the-protocol-relative-url/
