### ISSUE TITLE
mandatory jpg support prevents any compliance

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#449]
As you can't set any level of compliance if you don't support .jpg, then you can't generate a conforming info.json response, and hence can't be a IIIF implementation at all.

Do we need a level "null" below zero that has no requirements at all, just to let implementations state what they do support?

**Comment by azaroth42** [comment]
Propose:  WontFix.  

The implication is that level 0 MUST use jpgs. This is beneficial, otherwise you would have to retrieve the info.json just to get a thumbnail. Especially when you want to get lots of thumbnails.

The situation when this is harsh is if you have the image info embedded in a manifest, so the client would simply pick the format that is supported without retrieving the info.json.  This was possible in 1.1, but not in 2.0 forwards.

A nasty workaround would be to provide a gif (or whatever is supported) when the .jpg extension is used, either straight away or more graciously after a redirect.  The viewer will likely do the right thing regardless that it asked for a different format.

**Comment by jpstroop** [comment]
Big :+1: to wontfix

**Comment by zimeon** [comment]
+1 from me too

**Comment by mikeapp** [comment]
+1 don't fix

**Comment by jpstroop** [comment]
Confirmed as wontfix in tech meeting @ GW
