### ISSUE TITLE
Scale to fill with ~w,h size

### ISSUE THREAD

**Issue by klokan** [IIIF/iiif.io#450]
During the discussion about the Square thumbnails in #425 and in the related [iiif-discuss thread](https://groups.google.com/forum/#!topic/iiif-discuss/nAvjXlaGf-g) the following idea for extension of IIIF Image API has been formed collaboratively:

Extend the **Size** (http://iiif.io/api/image/2.0/#size) paragraph of Image API with:

Form | Description
---- | -----------
`~w,h` | Fill the width and height (w,h) with the previously specified region while maintaining the aspect ratio of the image.

This means an illustration could be added as Example no. 7:

![tilda](https://cloud.githubusercontent.com/assets/59284/7233941/3d1d84ec-e784-11e4-996e-4e6c4d1d6a9c.png)
```
size=~255,100
.../full/~255,100/0/default.jpg
```

With this request the typical photo lab "Fill in" approach is implemented: 
http://www.connsphotolab.com/2009/01/26/fill-in-and-fit-in-explained/

This approach allows to define the fast and proper thumbnails without previous request to `info.json` and without CSS hacks. Such thumbnails are often used in the applications for displaying large number of images or results of search (example applications mentioned in the discussion above).

The advantages of the suggested syntax:
- A character used as a prefix does not break existing parsers and is easier to implement as an alternative to existing "!" prefix.
- The "~" character choice: it is correctly accepted without URL encoding as part of an address - and not only Google Groups then make the mentioned links clickable :-)
- The specification allows beautiful thumbnails of pages of books / manuscripts with non-centered approach - if required by an application.

Notes from Rob (@azaroth42) slightly modified by @klokan:

Some examples:

1. Square, centered in full image:
    http://dlss-dev-azaroth.stanford.edu/services/iiif/f1rc/full/~200,200/0/default.jpg

    That may look good for photos and maps, but not for a page from a book or a manuscript.

2. Square, centered in top 80%:
    http://dlss-dev-azaroth.stanford.edu/services/iiif/f1rc/pct:0,0,100,80/~200,200/0/default.jpg

    Looks much better :) Same would apply to most pages, IMO.

3. Non Square, centered in full:
    http://dlss-dev-azaroth.stanford.edu/services/iiif/f1rc/full/~300,100/0/default.jpg  

    Useful for banners in wide but short displays ... like most screens.

4. And again in the top part of the image:
   http://dlss-dev-azaroth.stanford.edu/services/iiif/f1rc/pct:0,0,100,50/~300,100/0/default.jpg

5. Square thumb just of illumination (or other crop) ...
   http://dlss-dev-azaroth.stanford.edu/services/iiif/f1rc/100,220,1900,1200/~200,200/0/default.jpg 

By using percentages, the region can remain centered, and the center moved around.  It won't be as good as specifically picking top/left versus top/right, but makes URL patterns simpler.

--
Klokan Technologies Gmbh (http://www.klokantech.com/) is implementing this specification into IIIFServer powered by the latest IIPImage, which is auto-compiled with the latest Kakadu JPEG2000 library into .deb, .rpm and .exe installers and also available as a high-performance Docker container.

A patch with the implementation is going to be submitted as a pull request to IIPSrv repo.

**Comment by azaroth42** [comment]
Recent discussion on this topic gained consensus on a different approach.  The current proposal is to have a region called "square" that means "Return a square image that preserves the short edge of the content. The square is centered at a point of the server's choosing."

This clearly doesn't fulfill the banner use case, but does fulfill the original request more easily than managing size.  Is the banner case important for Klokan?  If not, I think we should go with "square".  If there is support for the non-square fill-in method, we should go with the ~w,h pattern (IMO)

@jpstroop? @zimeon? @mikeapp?

**Comment by klokan** [comment]
I am sorry for the confusion - I have missed the last call and the voting.

The original ticket #425 is updated - with a clearly visible result of discission.

KlokanTech is keen to implement whatever was agreed on by the IIIF community.
Square region is fine for our use-case as well. Closing - feel free to reopen if required.

**Comment by azaroth42** [comment]
@klokan -- no problem! glad that the square region fills your requirements. Seems like a simpler solution :)
