### ISSUE TITLE
Continuous viewing hint doesn't fulfill use cases

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#451]
The current description for the "continuous" viewing hint is that each canvas is one side of a scroll, rather than each canvas is a segment that should be rendered continuously rather than page turned or presented individually.

This seems like a bug?

**Comment by azaroth42** [comment]
In a bind:
 * The meaning of "the canvas is all of one side of a scroll" is a bit pointless. It's just an individual at that point, as it's not a 'page'.
 * The meaning of "the canvas is part of one side of a scroll" is useful, but does not allow both sides of the scroll to be present within the same manifest.

I think the latter interpretation is more useful overall, as the first can be just individuals without any loss.

**Comment by azaroth42** [comment]
Solution for two sided scroll: The manifest has individuals, and continuous is on two ranges of canvases, one for each side.  In favor of changing the definition.  While a change, I don't think this warrants a 3.0 as we haven't seen any usage yet... other than Jon's polyptich (sp?) which uses the latter definition anyway

**Comment by jpstroop** [comment]
Tech group @ GW: :+1: to fixing the definition. We acknowledge that this is a breaking change, but it was unlikely to be implemented based on the current definition, so OK to fix in the 2.x.x series.

**Comment by zimeon** [comment]
Agree OK to fix in 2.x series. Although technically a breaking change, this does not seem to apply in a meaningful sense for something not implemented

**Comment by zimeon** [comment]
Closed by https://github.com/IIIF/iiif.io/commit/2a8532a4f85f93e919abf18406557cc6efa8e473
