### ISSUE TITLE
What is the recommended way to represent the creator of an annotation?

### ISSUE THREAD

**Issue by aeschylus** [IIIF/iiif.io#455]
In Mirador, we use a custom field "annotatedBy" with a name field and an email field. In the interface, we want to display this, but obviously not from some crazy field we invented. What is the standard way of representing this? Are annotations expected to use the provenance namespace/vocabulary for this somehow?

**Comment by azaroth42** [comment]
That /is/ the standard way of representing it :)

http://www.openannotation.org/spec/core/core.html#ProvAgents

On Thu, Apr 30, 2015 at 2:15 PM, aeschylus <notifications@github.com> wrote:

> In Mirador, we use a custom field "annotatedBy" with a name field and an
> email field. In the interface, we want to display this, but obviously not
> from some crazy field we invented. What is the standard way of representing
> this? Are annotations expected to use the provenance namespace/vocabulary
> for this somehow?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IIIF/iiif.io/issues/455>.
>



-- 
Rob Sanderson
Information Standards Advocate
Digital Library Systems and Services
Stanford, CA 94305

**Comment by azaroth42** [comment]
Closing, sufficient references to the OA spec in section 7.
