### ISSUE TITLE
Add column in requirements table for whether or not @id must resolve

### ISSUE THREAD

**Issue by jpstroop** [IIIF/iiif.io#457]
Cf. #456 #439

**Comment by zimeon** [comment]
See also post from Markus Enders from 2014-11-05: <https://groups.google.com/forum/#!searchin/iiif-discuss/markus/iiif-discuss/POzUTedr1Ns/BJWemK8nV94J>

**Comment by zimeon** [comment]
In GWU meeting we agreed to add an extra column in the requirements table to make this clear.  Resolvability requirement will be for the Manifest and Canvas ids.

**Comment by jpstroop** [comment]
Closed by https://github.com/IIIF/iiif.io/commit/3f67bd2c3218821182581fdba221cffbf072a9f3
