### ISSUE TITLE
Enable association of PDFs for the Sequence or Range

### ISSUE THREAD

**Issue by zimeon** [IIIF/iiif.io#458]
Issue was mentioned in relation to #80. Goal is to enable associating PDFs of the sequence or range, as well as comments about them in a way that's consistent with existing usage.

**Comment by jpstroop** [comment]
Proposal: import `dcterms:hasFormat` as another linking property (next to http://iiif.io/api/presentation/2.0/#linking-properties) for linking to renderings of the thing the manifest is about. Should be an object, similar to that of the pdf service in the Sequence here: http://wellcomelibrary.org/iiif/b18035978/manifest

**Comment by jpstroop** [comment]
allowed on Manifest, Sequence, Range, Annotation, Layer

**Comment by azaroth42** [comment]
Propose to add Canvas, use case being "Download this page as a PDF"? where there's text and images to be combined.

**Comment by tomcrane** [comment]
A quick check - does this look right?

```javascript
  "sequences": [
    {
      "@id": "http://local.wellcomelibrary.org/iiif/b18035978/sequence/s0",
      "@type": "sc:Sequence",
      "label": "Sequence s0",
      "rendering": {
        "@id": "http://local.wellcomelibrary.org/pdf/b18035978/0/b18035978_0.pdf",
        "format": "application/pdf",
        "label": "Download as PDF"
      },
      "viewingHint": "paged",
      "canvases": [
```

**Comment by zimeon** [comment]
@tomcrane's example looks good

**Comment by jpstroop** [comment]
Closed by bc0a16195aa24ded95c7356ccd5cb9f4cace5acc

**Comment by tomcrane** [comment]
Sorry to reopen - had a question on the UV mailing list.

Should "rendering" be allowed at the canvas level too (as well as sequence and range)? A user of the Universal Viewer has one OCR text file per canvas that he would like to make available for download. As a text file is both human- and machine- readable, seeAlso could be used; but it seems that "rendering" is a good signal for a viewer to make links available as download options for human consumption. A context-sensitive download menu could use "rendering" on the current sequence, range and canvas to generate its contents.

**Comment by azaroth42** [comment]
Per http://prezi-21.iiif.io/api/presentation/2.1/#linking-properties:

A canvas MAY have one or more external rendering resources.
(As can anything else, for that matter)

**Comment by tomcrane** [comment]
...and per 

https://groups.google.com/d/msg/iiif-discuss/FqLmrUmxDWg/BNNdEawV1wcJ
and
https://github.com/IIIF/iiif.io/issues/488

(Unexpectedly tying these two questions together! - wasn't sure where to ask this but here felt best)

How would you feel about using "rendering" on the canvas for a manifest that wants to supply the source TIFF? The API deliberately has no semantics for original image, but if "rendering" assertions drive a download menu in a viewer, then the label on the rendering can let the user know that this is the original. A TIFF is not "human-readable" in the sense we were talking about above but it could be the object of dcterms:hasFormat ("A related resource that is substantially the same as the pre-existing described resource, but in another format") and is certainly "human-viewable".

e.g., on a canvas:

```javascript
      "rendering": [
      {
        "@id": "http://example.org/..../canvas-99.txt",
        "format": "text/plain",
        "label": "Text of this page (plain text file)"
      },
      {
        "@id": "http://example.org/..../canvas-99.tiff",
        "format": "image/tiff",
        "label": "TIFF original of image 99 (14.8 MB)"
      }
     ]
```
