### ISSUE TITLE
Make some/most of the examples of the use of seeAlso include the recommended profile and format properties

### ISSUE THREAD

**Issue by zimeon** [IIIF/iiif.io#459]
The specification of [seeAlso](http://iiif.io/api/presentation/2.0/#linking-properties) says:

> ... The `profile` and `format` properties of the document should be given to help the client to make appropriate use of the document.

yet at the moment only one [example of use is the spec](http://iiif.io/api/presentation/2.0/#complete-example-response) has a `format` property, no examples have a `profile`.

**Comment by jpstroop** [comment]
Closed by e90d948fe5d31024bc54628a57d33106788aeb60
