### ISSUE TITLE
Consider OpenSearch Suggestions extension for autocomplete suggestions

### ISSUE THREAD

**Issue by zimeon** [IIIF/iiif.io#460]
Specification response format at <http://www.opensearch.org/Specifications/OpenSearch/Extensions/Suggestions/1.1#Response_format>. Minimal response format is JSON array with query term repeated and an array of suggestions:

```JSON
["sea",
  ["sears",
   "search engines",
   "search engine",
   "search",
   "sears.com",
   "seattle times"] ]
```

there are optional addition parallel indexed arrays for human readable descriptions and query URIs.

**Comment by zimeon** [comment]
Discussion at GWU: the opensearch format is plain JSON and not JSON-LD so use of this format goes against our recommendation that services SHOULD use JSON-LD (<http://iiif.io/api/annex/services/#requirements>).

**Comment by azaroth42** [comment]
Also, does not allow internationalization of the middle section which is a requirement for any string intended for humans.
URLs in the final section make it complex but not impossible to merge with further search requirements.

**Comment by zimeon** [comment]
By the time we think about this as an almost trivial but non-internationalizable format I'm not sure that there is much benefit to import from OpenSearch here. We note also that in order to add the final section it is mandatory to have the middle section. We might as well come up with a format that support internationalization, better search specs, while still having the dumb down to the simple list of auto-complete suggestions.

**Comment by azaroth42** [comment]
:-1: to OpenSearch response format. As per @zimeon it's not internationalizable, it's kludgey for extension (add new lists, rather than extending resources), it's not JSON-LD-able (no lists of lists) and so forth.

**Comment by jpstroop** [comment]
Agree. It would be nice to find a standard, but this isn't it.

**Comment by azaroth42** [comment]
Considered it, didn't like it. --Eds
