### ISSUE TITLE
embed iiif-discuss google forum in a page on iiif.io

### ISSUE THREAD

**Issue by tomcramer** [IIIF/iiif.io#461]
to increase access to Forum and apparent participation level of IIIF community.

https://support.google.com/groups/answer/1191206?hl=en

**Comment by azaroth42** [comment]
Propose: close wontfix

We already have the link to -discuss on the community page, and we wouldn't embed it there, so people might as well just follow the link to the full forum rather than a crippled embedded version.

**Comment by jpstroop** [comment]
:+1: I think linking out is fine.

**Comment by tomcrane** [comment]
+1
