### ISSUE TITLE
add a blog to iiif.io

### ISSUE THREAD

**Issue by tomcramer** [IIIF/iiif.io#462]
to give a place for narratives on use cases, recent devs, etc.

**Comment by azaroth42** [comment]
and allow static importing of other blog posts at site compile time [per 2015-05-13 community call]

**Comment by azaroth42** [comment]
Propose close wontfix, no one has time to write blog posts and the news section is good enough.

**Comment by jpstroop** [comment]
:+1:

**Comment by zimeon** [comment]
post action - agree wontfix
