### ISSUE TITLE
Explore client-side driven approach to auth using an open info.json with links to login/logout/degraded

### ISSUE THREAD

**Issue by zimeon** [IIIF/iiif.io#463]
Discussion at GWU: Make the `info.json` always available, with links to login, logout and perhaps to degraded versions also. The client would be able to detect that it is not authz either by knowing that it has not sent the user to the giving login URI and/or that it does not have access to images. Could then see whether there is a link to a degraded `info.json` (which would also be public). There could be more than one degraded link, put in order of preference. User can be directed to login service.

Discussion of whether the `info.json` information for degraded image could be included in the `info.json` for the full image? Consensus that the idea of recursive `info.json` is not a good approach and breaks that atomic notion of image+info.

**Comment by azaroth42** [comment]
Closing, after agreement on 2015-05-13 call to instead go with #464 approach.
