### ISSUE TITLE
Collection requirements location is inconsistent with Range/Layer

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#469]
The requirements for Range and Layer are presented in section 4, along with the main resources.  However Collections, having been added in 2.0, have their requirements specified in 8.3.  This is inconsistent -- either the Range and Layer requirements should be in section 8 (which would be hard to justify, given there are some that apply *only* to Ranges) or Collection should be part of 4.

Proposal: Add Collection to the requirements blocks in section 4 and remove from 8.3

**Comment by jpstroop** [comment]
Yup, +1. It took me a second to understand what you meant, but basically most of the Collections MUST ..., Collections SHOULD..., and Collections MAY...  bullet lists near the end of [8.3](http://iiif.io/api/presentation/2.0/#collections) should be integrated into [4](http://iiif.io/api/presentation/2.0/#presentation-resource-properties). Correct?

**Comment by azaroth42** [comment]
Sorry, was quickly throwing in an issue while working on the other ones so I didn't forget it.  And yes, you're correct ... move the requirements from 8.3 into 4.

Also related to #468 ... will fix both at once if there's agreement.

**Comment by zimeon** [comment]
+1 to integrating rules for collections into [4](http://iiif.io/api/presentation/2.0/#presentation-resource-properties)

**Comment by jpstroop** [comment]
Closed by 1e98bf04f588026309cee0b05ed5f61b4e4eccc1
