### ISSUE TITLE
[Meta] Clarify understanding of SemVer requirements

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#470]
From #425, we need to be clearer in our understanding of the Semantic Versioning requirements, with respect to what is a backwards incompatible (breaking) change.

In particular, the question has arisen as to whether a new requirement at a minor level is a breaking change, because a server that was (e.g.) level 2 compliant and does not implement the new requirement, suddenly is not level 2 compliant.  This may be an unintended side effect of levels only being versioned at the major level.

**Comment by zimeon** [comment]
I think that in going from x.y to x.(y+1) we expect that any x.y client will work with any x.y or x.(y+1) server. I think this is what our statement "MINOR version increment indicates addition of functionality in a backwards-compatible manner" means. Any addition of functionality means that a client assuming/needing the new functionality will not work with an older server.

In this model, adding a requirement for support of the new feature doesn't seem breaking, but somehow the notion of changing the compliance levels perhaps still is...? It seems only the compliance levels that cause a problem.

**Comment by azaroth42** [comment]
Agree with your definition, propose that we include it in the semver note.

That compliance docs only get major versions means that we can't distinguish between a 2.0 level 2 compliant server and a 2.1 level 2 compliant server. So if we update level 2 to add a required feature at version 2.y, a 2.(y-1) server will not be correct in referencing that profile.  This seems like an issue to be solved... but not sure how other than either changing what we said (and 2.y refers to a 2.y compliance doc, making it hard to figure out the general case) or having minor profiles (first must be 2.0, second must be the highest minor version of the same level).

**Comment by jpstroop** [comment]
I agree...basing the compliance levels on the major version only is a problem, but doing anything else is worse.

**Comment by azaroth42** [comment]
Options:
  1. ~~Introduce minor level compliance docs like 2.1/level2.json~~
  2. Edit major only docs and earlier minor versions will just be wrong
  3. Introduce additional profiles that record minor level versions
  4. Don't introduce any new requirements at any level before a new major version

Others? Thoughts?

**Comment by jpstroop** [comment]
Make breaking changes like the square case optional in the current major revision, with a note that it will be required for level _n_ compliance in the next major revision. Sort of the opposite of how I imagine we'd handle a deprecation.

**Comment by zimeon** [comment]
I think @jpstroop is essentially arguing for "4. Don't introduce any new requirements at any level before a new major version" and additionally "document the set of requirements changes queued for the next major version". This is clear and concrete.

One could almost do this as a DRAFT (x+1) compliance document? Could one then have an x.y server compliant at x level n, and (for the forward looking) also compliant with DRAFT (x+1) level n? This might be the thing that makes us change major version sooner than we currently imagine.

**Comment by azaroth42** [comment]
I'm fine with 4 + documentation.  I think I'd prefer to keep a separate doc of new major version changes than potentially litter the 2.y documents with them.  If we (for example) got to 2.10, there'd be notes everywhere. Something like annex/notes/scheduledChanges ?

Not keen on draft version x+1 documentation being available that look official.  It not only pushes us editors to want to rev early, it gives the impression to the rest of the world that we're going to rev... which could hinder adoption unnecessarily.  Also it could be wasted effort as we might re-factor everything in a new major version.

**Comment by zimeon** [comment]
On reflection I agree that a document with planned changes is better than a draft x+1 document. I'm not convinced that a separate document outide of the versioning and separate from the image/prezi split is the right way to go. I think I'd prefer to add a section at the end of the compliance document itself which will (I think) be easier to maintain and give better visibility to the planned changes.

**Comment by azaroth42** [comment]
We don't have a compliance doc for Prezi though, as we don't have levels.
I think the options are a separate non version specific doc, or the
change-logs that accumulate them over time.  Change-logs likely don't have
the visibility that a separate document would, potentially.
