### ISSUE TITLE
Should Auth use OAuth's camel or IIIF's snake?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#474]
I started the auth draft with camelCase following our decision for 2.0 ... but then changed to snake_case when we added the token patterns from OAuth to follow it more closely.

e.g. see:
    https://tools.ietf.org/html/rfc6749#section-4.1.4

For the OAuth access token response.  We're not claiming to be OAuth so it's not like we *have* to use exactly the same representation. So it's who we want to be consistent with.

**Comment by zimeon** [comment]
I don't know what is best here, but I propose that we leave this as camelCase until at least the end of OR2015 ;-)

**Comment by tomcrane** [comment]
OAuth2 inspired, but if it looks too much like it and not like the rest of
the API then people might assume it is OAuth2, or otherwise get confused.

**Comment by jpstroop** [comment]
+1. It isn't OAuth, so better to follow our own convention I think

**Comment by azaroth42** [comment]
(Resolved, no need to keep this open, nothing to review)
