### ISSUE TITLE
Issues with Annotation framing

### ISSUE THREAD

**Issue by glenrobson** [IIIF/iiif.io#475]
I’ve been playing with loading json-ld annotations to JENA and getting them back out again and I think I’ve found a couple of issues with the context.json and annotation_frame.json but I'm very much learning about JSON-LD and JENA so I may have misunderstood. To get the framing to work I had to change the annotation frame from:

http://iiif.io/api/presentation/2/annotation_frame.json

to
```
{
    "@context" : "http://iiif.io/api/presentation/2/context.json",
    "@type": "oa:Annotation",
    "resource" : {
        "@embed" : true
    },
    "on" : {
        "@embed" : true
    }
}
```
i.e. I added 'resource'  to get it to show. Also had to change embed to true in ‘on’ to make it show (otherwise it did:
```
 "on" : "_:b1”
```
). Also changed everything to objects rather than arrays as it appears you define it as a list in the context rather than the frame according to:

https://github.com/digitalbazaar/jsonld.js/issues/61

So changed the following two lines in a local copy of http://iiif.io/api/presentation/2/context.json:
```
"motivation":  {"@type":"@id", "@id":"oa:motivatedBy","@container": "@set"}, 
 "resource":    {"@type":"@id", "@id":"oa:hasBody","@container": "@set"}, 	       
``` 
Only thing now is the blank node ids which look related to an issue Rob raised in 2013:

https://github.com/json-ld/json-ld.org/issues/293

For reference the JSONLD input from mirador:
```
{
    "@context": "http://iiif.io/api/presentation/2/context.json",
    "@type": "oa:Annotation",
    "motivation": ["oa:commenting"],
    "resource": [{
        "@type": "dctypes:Text",
        "format": "text/html",
        "chars": "<p>este<\/p>"
    }],
    "on": {
        "@type": "oa:SpecificResource",
        "full": "http://oculus-dev.harvardx.harvard.edu/manifests/drs:14033171/canvas/canvas-14033925.json",
        "selector": {
            "@type": "oa:FragmentSelector",
            "value": "xywh=212,801,146,80"
        },
        "scope": {
            "@context": "http://www.harvard.edu/catch/oa.json",
            "@type": "catch:Viewport",
            "value": "xywh=-358,214,2420,1234"
        }
    },
    "@id": "http://dev.llgc.org.uk/annotation/1433532904891"
}
```
and the JSONLD output after going into JENA (note scope is lost due to it not being in the context.json):
```
{
  "@id" : "http://dev.llgc.org.uk/annotation/1433532904891",
  "@type" : "oa:Annotation",
  "resource" : [ {
    "@id" : "_:b0",
    "@type" : "dctypes:Text",
    "format" : "text/html",
    "chars" : "<p>este</p>"
  } ],
  "on" : {
    "@id" : "_:b1",
    "@type" : "oa:SpecificResource",
    "selector" : {
      "@id" : "_:b2",
      "@type" : "oa:FragmentSelector",
      "value" : "xywh=212,801,146,80"
    },
    "full" : "http://oculus-dev.harvardx.harvard.edu/manifests/drs:14033171/canvas/canvas-14033925.json"
  },
  "motivation" : [ "oa:commenting" ],
  "@context" : "http://iiif.io/api/presentation/2/context.json"
}
```
Thanks

Glen

**Comment by azaroth42** [comment]
Thanks Glen!

Agree that the published annotation_frame is broken, and yours is correct. I'll make a PR to fix it this afternoon.

I disagree that @set is needed in the context.  The Mirador output is not wrong, just has an unnecessary array.  Stripping the array (such that motivation has a single string as its value) would be better, as per examples in the spec: http://iiif.io/api/presentation/2.0/#advanced-association-features
If Mirador requires those arrays that's a bug in Mirador (or other client).

The blank node ids ... yeah, I asked for at least an option to strip them automatically but nothing came of it.  For now we could strip them by hand, or just leave them on the grounds that they're not harmful, just worthless.

**Comment by glenrobson** [comment]
Hi Rob,

Thanks for your message. I haven't tested the lack of arrays in Mirador for motivation and resource yet just trying to make the outputs match. Ill remove the @set changes I made and see how it goes. 

Ill also leave the blank node ids and see if I hit problems.

Thanks for your help.

Cheers

Glen
