### ISSUE TITLE
Clarify language in 3.3 (login window has to have a URL bar)

### ISSUE THREAD

**Issue by jpstroop** [IIIF/iiif.io#480]
The client must present this URL to the user in a separate window with a URL bar to help prevent spoofing attacks. It should not be in an iframe or otherwise imported into the client user interface.

to 

... with a URL bar, not in an iFrame or otherwise imported into the client user interface, in order to help prevent spoofing attacks

**Comment by zimeon** [comment]
+1 to proposed change

**Comment by azaroth42** [comment]
:+1: from eds.
