### ISSUE TITLE
Extract Auth to separate API

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#494]
As it can work with both presentation and image APIs, it should be separate and is currently part of image:
`/api/auth/0.9/`
(Also demonstrates that version numbers are not actually tied together)

The Image and Prezi APIs should then reference it, and keep the specific details in their own documents.

**Comment by zimeon** [comment]
+1 for separate.

Re. numberering: Is it 0.9 now and we release as 1.0 after tidy and review by community? Or do we imagine releasing as 0.9 with an intended move to 1.0 after some real-life implementations (first half of 2016, hopefully with few changes)? I lean toward the latter.

**Comment by azaroth42** [comment]
The latter for me too

**Comment by jpstroop** [comment]
Definitely the latter, otherwise we risk being pushed to 2.0(.0) before there are production impl.

**Comment by zimeon** [comment]
I think we have agreed on this and moved ahead (http://auth.iiif.io/api/auth/1.0/ announced to today's community call) so I propose that we can close this issue.

I guess the boat has also sailed on the 0.9 vs 1.0-draft issue. For the record, I think it would have been better to have the draft as 0.9, even if that meant some duplication.

**Comment by azaroth42** [comment]
Need to update profile links to auth/0 and numbers to 0.9

**Comment by azaroth42** [comment]
:+1: from eds
