### ISSUE TITLE
Downgrade logout service to SHOULD?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#495]
As discovered by @azaroth42 and @zimeon at OR2015, getting basic auth to successfully log the user out is not actually all that easy.  It might be difficult or even impossible for other authentication systems too.  

The current auth spec requires a logout service (http://image-auth.iiif.io/api/image/2.1/authentication.html#logout-service).  As this may be hard or impossible, and the value of the service is not that great, I propose downgrading this to SHOULD from MUST.

**Comment by zimeon** [comment]
+1 to SHOULD

**Comment by azaroth42** [comment]
:+1: from eds
