### ISSUE TITLE
Change sc:AnnotationList model to WAWG List model

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#496]
Replace current super-basic annotation list construct with whatever comes out of the Web Annotation Working Group.  At the same time, update to the WAWG annotation model/serialization/protocol as well.

Annotation List issue:
- https://github.com/w3c/web-annotation/issues/50

**Comment by azaroth42** [comment]
We should confirm that we're doing this to avoid future discussion.
My vote:  :+1:

**Comment by jpstroop** [comment]
:+1:

**Comment by zimeon** [comment]
:+1:

**Comment by tomcrane** [comment]
👍

**Comment by tomcrane** [comment]
Related - for vNext:

`otherContent` gives you a list (or lists) of annos on the resource for which it is asserted. Need something to convey "here is an anno container, and it's writeable" for a resource, to invite new annotations. Whether the client has the ability/permission to write to it is another matter, but useful for crowdsourcing scenarios. E.g., a canvas might have `otherContent` that gives transcriptions and *moderated* comments; the canvas also offers a container for new content that maybe takes a while to appear in the `otherContent` list(s). 

@glenrobson might be interested. This is probably a new issue.

**Comment by mikeapp** [comment]
👍

**Comment by azaroth42** [comment]
Discussion on call 8/2/17:  Do implementations intend to do this? Actually very few changes, very easy to do. More likely to have implementations by following the W3C standard than going our own way -- already more implementations of the backend server and clients in the last 6 months than we have for IIIF in 6 years.

Consensus, closing.
