### ISSUE TITLE
Structure of target of search results?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#502]
Should the search results give information about the structure beyond the target of their annotations? 

Some use cases:

 * Results target a canvas that is only present in one of multiple sequences, and it happens to not be the one currently being viewed. Knowing the sequence the canvas is part of would be useful?
 * Results target some non-canvas (possible in 2.1) such as a range of two canvases representing an opening.  Knowing the canvases that are part of the range would be useful? [But doesn't scale well for long ranges, and is already known from the manifest]
 * Searching content within a collection, rather than a manifest, is out of scope? If not, then knowing the manifest(s) that a targeted canvas is part of would be important.
 * For canvases that are part of multiple manifests, even if the search occurred from one of them in particular, it could be valuable to know the others.

We could document the optional ability to include 'within' on the target, eg:

```json
{
  "resource": {"chars" : "..."}, 
  "on": {"@id" : "uri-of-canvas", "within": "uri-of-manifest"}
}
```

**Comment by tomcrane** [comment]
"Searching content within a collection, rather than a manifest"

if not in scope right now, this is still a compelling use case. I search the whole library and together "uri-of-canvas?xywh=XXXX" and "uri-of-manifest" let me jump straight to the result with no further lookups. +1 for this.

**Comment by azaroth42** [comment]
I'm also :+1: to describing the ability. It seems like we already have the ability (things can be within other things), we just need to document and let people make use of it.  

I think this is, otoh, NOT something that we need to do in the main Presentation API, as you don't end up at an annotation outside of an AnnotationList referenced from the manifest.

**Comment by azaroth42** [comment]
Eds agree that it should be available and optional.
