### ISSUE TITLE
Is "within" actually MVP?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#504]
To date, services have been related to individual objects in the model without any inheritance.  For example, an image has an image service, rather than a manifest having an image service that client queries for image identifiers.

The scope of the query resolution could follow the same approach, rather than requiring the URI of the resource to be in the query params in within.  In this case, the identifier for the resource would be in the path to the service, rather than the parameters passed to the service and thus would be invisible to the client.

The feature that would not be possible with this approach is searching within a bounding box on a single canvas, for example for annotations on the current viewport of a large object like a scroll.  

In trying to describe within, it seems to me that:
 * You wouldn't know whether the bounding box search feature is available, and wouldn't want to keep trying it every time the user repositions their viewport if it's not going to work
 * Conversely, if there is a search service associated with a canvas, it seems likely that this would be supported (or otherwise why bother with the service at that level)
 * It's not a minimum viable product feature, it's a nice to have for a small subset of objects
 * within is overkill for this feature, it could be a separate parameter just for canvas bounding boxes

Other rationale for making services per-resource:
 * For other scopes (searching within a range, layer, etc) the client should know whether there is a service that resolves at that scope.  The only way to know that is to associate the service with the resource... even if it points to the same code that handles other levels too.
 * Autocomplete would also need to know which scope it is generating a termlist for, and would thus also need within with the same values and potential for errors
 * If the scope isn't supported, we would need machine readable error conditions.  Compared to simply not having a link to a service
 * In REST terms search is always hard to think about, but the best I've seen is that the resource is the set of indexed terms. Thus within is part of the identity of the resource (and hence URI path), not the query params that filter the resource.  

So my proposal is:

The search service should be associated with whatever resource in the model is being searched, typically the Manifest, but also for Range, Sequence, Layer, Canvas or anything else.  The vast majority of use cases only require Manifest scoped searches, so the overhead is minimal.

**Comment by mikeapp** [comment]
You might include the search service at the Canvas level if the canvas is being reused in another Manifest.  Rather than assume a Canvas-level search service can provide a bounding box search, this capability could be advertised as an iiif:Feature per #505 if search service URI is per-Canvas.

**Comment by azaroth42** [comment]
Eds agree.
