### ISSUE TITLE
Autocomplete is not independent from Search

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#506]
If there are multiple search services associated with a single resource, each with an autocomplete service to return term lists, there is no way to align the pairs of services.

For example:
```json
"service": [ 
  {"@id": "search-service-1"}, 
  {"@id": "search-service-2"}, 
  {"@id": "autocomplete-service-x"}
]
```

Does the autocomplete work with service 1's index or service 2?   While this might not be an issue today, we shouldn't paint ourselves into a corner and have to have a major version revision to fix the issue.

Given that the autocomplete service is worthless without the search service, I propose nested services:

```json
"service": [
  {
    "@id": "search-service-1",
    "service": { "@id": "autocomplete-service-x" }
  },
  {"@id": "search-service-2"}
]
```

**Comment by tomcrane** [comment]
For searching the OCRed text, the autocomplete makes sense as a service of the search service. Would there ever be an autocomplete service that stands alone? Would it matter if there was?

**Comment by azaroth42** [comment]
I don't think there'd be an autocomplete service without search -- there's nothing you could do with the information.  Or is there a use case here  ... we can canvas (ha) the community for them?
And, regardless, it wouldn't matter if there was, you could still add it to the list of services for the resource.

**Comment by tomcrane** [comment]
An autocomplete service that supplies the pool of allowed tags, in some crowdsourcing project?

**Comment by mikeapp** [comment]
+1 on autocomplete for user-entered tags

**Comment by zimeon** [comment]
Maybe a more general solution is to have all services at the same level but to provide a way to link between them, e.g.:

"service": [ 
  {"@id": "search-service-1"}, 
  {"@id": "search-service-2"}, 
  {"@id": "autocomplete-service-x",
   "forSearch": "search-service-1" }
]

**Comment by zimeon** [comment]
Having discussed this model with auth, and decided to go with related services nested inside the login service description, I now agree with nesting auto-complete inside the search service description it applies to because it would follow the same pattern.

**Comment by azaroth42** [comment]
Eds agree.
