### ISSUE TITLE
Consider server-determined page size with next/prev links

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#508]
Instead of requiring the client to do math, and the server to support arbitrary page sizes, the server could simply enforce whatever page size it prefers, and provide next and prev links to the next and previous pages.

This would simplify the API (no `n` or `offset`), improve caching (everyone gets the same page size) which improves performance, and allow the client to simply follow a link rather than constructing a URI (as the links are embedded in the representation HATEOAS style).

Thus if #504 is accepted, and this is accepted, the list of params would be:
 * q  -- the actual query, free text ; default to no terms iff there is at least one uri
 * motivation -- "painting" / "commenting" / "non-painting" / default: "all"
 * date -- date range for creation of annotation  (actually mvp?) default: any date
 * uri -- URI(s) to filter for (e.g. user, resource, semantic tag, etc.) default: no URIs to filter by

And potentially the same for autocomplete (e.g. to allow autocomplete to derive the same term set for the query ... no good having autocomplete only work with all annotations, and then have there be zero results on the search when you limit it by only painting motivation)

**Comment by tomcrane** [comment]
Agreed, easier for client and server and also helps prevents abuse.

**Comment by azaroth42** [comment]
:+1: from @aeschylus and @mikeapp discussing client <--> server interactions.  If the first page is always warm in cache, clients can quickly present the total number of annotations on a particular resource without over-burdening the server in creating arbitrarily-sized pages

**Comment by azaroth42** [comment]
Eds agree.
