### ISSUE TITLE
Semantics of Semantic Tag URI and query terms?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#510]
If there is a request like:
> `http://.../search?q=fish&uri=uri:sem-tag-1`

that searches for both textual content and a semantic tag, what are the semantics?  It seems like it will never actually produce results without multiple bodies (which we don't support in IIIF).

What was the rationale against just putting the URI for the tag (or other body URI) in q?

**Comment by mikeapp** [comment]
In the case of a URI I think you'd want treat it differently when searching: don't tokenize the value and search for an exact match.   The service implementation would have to make the determination if it wasn't made explicit in the request.

**Comment by azaroth42** [comment]
The two issues I see:
  * When all of the params have to be optional, because two have overlapping semantics (e.g.  search for text tags in q, and URI tags in uri), it seems like we have an opportunity to simplify by being consistent where search terms of any type are sent.
  * It seems like a bonus if the URI being searched for was referenced in a comment's text, that the comment would be retrieved in a search for the URI.  On the other hand, there's a difference between searching the structure of the graphs for URIs, versus searching within text for tokens that happen to be URIs.

**Comment by zimeon** [comment]
My sense was that URI search was intended to be for mentions (of those resources) in the graph and not matching on comment text.  This seems sufficiently different to me to keep them separate, I think conflation would lead to less consistency.

**Comment by azaroth42** [comment]
Now all in q and implementation can sort it out as needed.
