### ISSUE TITLE
Reporting consistent page size adds no value

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#512]
Currently pagesize is a property of the layer, implying that it's always true for that layer ... and hence for all pages of that layer.  Is this actually valuable information, as you can simply count the number of annotations in the current response?  If the page size isn't consistent, then you couldn't put it on the layer anyway (global open world graph, and all that).

Proposal:  dump it.

**Comment by mikeapp** [comment]
+1 to removing it

**Comment by zimeon** [comment]
Seems only valuable if one wants to be able to compute the page number to get a a particular result number. For a particular page being examined one can simply count the items, for the last page the number will be <= `pagesize` anyway. Agree drop since we have `prev` and `next` paging scheme.

**Comment by azaroth42** [comment]
Eds agree.
