### ISSUE TITLE
Do we need a token validation service?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#516]
Which would let us validate whether the 4xx error was from a broken token, or for some other reason?

**Comment by tomcrane** [comment]
Isn't the token service its own validation service? Or rather, if you're going to spend an HTTP request validating a token, just call the token service instead and get another one - it's the best way of determining what the token represents, which is that the user has the cookies to get the pixels. It also offers a way of keeping a token session alive, the implementation can renew the token.

@edsilv has been implementing a switchable pessimistic/optimistic strategy in the UV that determines how much it trusts its own token store.

**Comment by azaroth42** [comment]
:+1: to asking for a new token. Won't Fix.
