### ISSUE TITLE
Publish discovery data on iiif.io somehow

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#517]
In order to promote usage of IIIF data, we should have an easy to use way to explore the manifests and collections somewhere on iiif.io.  Both human and machine readable ways, along with appropriate web infrastructure to use it directly from systems (ACAO etc)

**Comment by mekarpeles** [comment]
One interim option is, we could create a file within https://github.com/IIIF/iiif.io/tree/master/source/ called `collections.html` which explains what institutions are available through the "api" and for now have a corresponding file `catalog.json` which is updated directly via pull requests on the iiif.io repo (rather than ingesting via a 3rd party).

Alternatively, we can ingest from here: https://raw.githubusercontent.com/ryanfb/iiif-universe/gh-pages/iiif-universe.json or https://graph.global/static/data/universes/iiif/universe.json.

**Comment by beaudet** [comment]
Having an aggregated source still works because there are a limited number of IIIF resources, but I'm wondering if it makes sense to establish micro format standards for IIIF resources and / or to embed a Mirador specific GUID in manifest links that would be indexed by search engines, making it possible to constrain search results only to relevant materials.

**Comment by azaroth42** [comment]
@beaudet Would that differ from what #557 is suggesting? If so, can you expand ... probably in that issue?

**Comment by beaudet** [comment]
Yup, much more aligned to #557. I commented there.

**Comment by mekarpeles** [comment]
Is there any progress on this?

Here's a spreadsheet w/ ~15 IIIF Service URLs:
https://docs.google.com/spreadsheets/d/1apQKFkfBV89BvycaBPN6v-LjeaKaVVMaMUsY6L4KRJo/edit#gid=0

**Comment by zimeon** [comment]
IMO we don't want to be making and updating a list on the website, but I think could/should be quite liberal (at least for now) about what separately maintained list or lists we link to. Could link to this spreadsheet for example...

**Comment by jpstroop** [comment]
I agree with @zimeon. It's nice to see folks taking a lead on this, and I think trying several approaches until a clear pattern emerges is the way to go.

**Comment by acdha** [comment]
I'd definitely like to focus on #557 so the discovery tools could be as simple as crawling a site or checking sitemap/feed entries for declared manifests.

**Comment by zimeon** [comment]
A [thread on IIF Discuss](https://groups.google.com/forum/#!topic/iiif-discuss/ZdxZx0tFBSY) points out work on a machine readable endpoint at <https://github.com/ryanfb/iiif-universe/blob/gh-pages/iiif-universe.json>

**Comment by benwbrum** [comment]
The Stanford, Biblissima, and e-codices collection endpoints on https://github.com/ryanfb/iiif-universe/blob/gh-pages/iiif-universe.json are all hosted on https://graph.global .  Unfortunately, graph.global has an SSL security certificate that expired on April 15, so none of these are easily machine-readable.

Should I open up a new ticket on this, and--if so--where?

**Comment by azaroth42** [comment]
Neither of which are IIIF managed and hence we have no direct control or ability to improve. This underscores the point of /this/ issue, which is that there should be something central on iiif.io that is maintained by the community as a whole, not individuals that come and go.

**Comment by ryanfb** [comment]
I'm happy to transfer [ryanfb/iiif-universe](https://github.com/ryanfb/iiif-universe) (https://help.github.com/articles/about-repository-transfers/) to the IIIF GitHub organization, if that's desirable.

**Comment by benwbrum** [comment]
I'm happy to send a pull request to iiif-universe (whereever it's located) with new top-level URLs if I can get them.

**Comment by mekarpeles** [comment]
I'll update the SSL for graph.global, thanks!

**Comment by mekarpeles** [comment]
Cert is updated. I believe both the universe and this repo are slightly behind 
https://docs.google.com/spreadsheets/d/1apQKFkfBV89BvycaBPN6v-LjeaKaVVMaMUsY6L4KRJo/edit#gid=0

Will try to submit a PR today.

re: "there should be something central on iiif.io" -- can someone please outline the challenge here? Can we do this today. cc: @azaroth42

**Comment by mekarpeles** [comment]
I think @ryanfb's suggestion is the best approach for the interim, having IIIF maintain a catalog.

**Comment by zimeon** [comment]
This is no under the remit of the [Discovery TSG](http://iiif.io/community/groups/discovery/) and we aren't going to do something systematic before that groups makes recommendations. Closing.
