### ISSUE TITLE
Make requirements rfc2119, not just shouty

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#519]
The key words "must", "must not", "required", "shall", "shall not", "should", "should not", "recommended", "may", and "optional" in this document are to be interpreted as described in [rfc2119].

[rfc2119]
S. Bradner. Key words for use in RFCs to Indicate Requirement Levels. March 1997. Best Current Practice. URL: https://tools.ietf.org/html/rfc2119

**Comment by jpstroop** [comment]
Closed for the image api in b6f24a2b8fe52a7d5e8867f179d1adf676031a8e

**Comment by azaroth42** [comment]
Closed for Prezi, Auth and Search.
