### ISSUE TITLE
Update image service example to use auth

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#524]
... once we have a more solid auth spec.

**Comment by azaroth42** [comment]
Include merging 8.1 into 8. unless there's additional structure needed.

**Comment by zimeon** [comment]
Perhaps greatest clarity would be to add another service example, using the auth service, into section 8. 

+1 to merging 8.1 into 8

**Comment by jpstroop** [comment]
+1

**Comment by azaroth42** [comment]
Blocked by #570.
