### ISSUE TITLE
Are IIIF docs now published by the Consortium?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#525]
And should that link to something that explains what the consortium is? Like the press release  ... but that doesn't seem good long term.

Tagging @tomcramer to verify / discuss

**Comment by azaroth42** [comment]
Don't change anything. Consortium is not a legal entity. Things have been going fine till now, so no need to change :)

**Comment by zimeon** [comment]
My take on it is not so much the legal aspect but whether we wish to recognize/publicize the IIIFC as the governing body for IIIF work (and saying that something is published by a framework in kinda silly). I still think the minimal change is IIIF - > IIIFC and link it to something.

**Comment by azaroth42** [comment]
Propose close wontfix

**Comment by zimeon** [comment]
Hmmm.... I'd still vote for IIIF -> IIIFC where that is linked to a description of IIIFC. Others?

**Comment by jpstroop** [comment]
I tend to agree w/ @zimeon. I don't think it's so much about IIIFC being a legal entity as it is about IIIFC sponsoring the work.

**Comment by azaroth42** [comment]
Thus the text should be:

`Published by the IIIF Consortium under the CC-BY license.` 

Yes?

**Comment by zimeon** [comment]
:+1: and linked [IIIF Consortium](http://iiif.io/news/2015/06/17/iiif-consortium/) until there is a page <http://iiif.io/iiif-consortium/>?

**Comment by azaroth42** [comment]
I think we should wait until there's a stable iiif.io/consortium (or whereever it ends up)

**Comment by zimeon** [comment]
I'm OK to compromise on the link ;-)
