### ISSUE TITLE
How to validate server implementations of auth?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#529]
When it requires a user to type in credentials in a new window.

**Comment by azaroth42** [comment]
Ideas:
* Reference implementations for server and client
* Command line client that sends the right requests at the right times
* A null login service that just returns okay without requiring any interaction

**Comment by zimeon** [comment]
2016-09-21 Eds call - agree that we should discuss validation and reference implementation @ The Hague

**Comment by zimeon** [comment]
Discussion at the Hague: We don't know how to make sensible/feasible validators for client or server. Won't try, close.
