### ISSUE TITLE
Warranty of fitness disclaimer?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#531]
Should there be some disclaimer, especially for authentication, to avoid legal situations?  We are doing due diligence as to what the possible security implications, and hence legal implications, are.

For example, do we need something like:
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THIS SPECIFICATION.
(based on MIT license)

Tagging @tomcramer and IIIF-C types.

**Comment by azaroth42** [comment]
IIIF isn't a legal entity and hence can't be sued. Find out what W3C have done with their security specs. 
Publish a disclaimer note?

**Comment by azaroth42** [comment]
Proposal:  Write and publish api/notes/disclaimer.html with disclaimers similar to the W3C set: http://www.w3.org/Consortium/Legal/2015/doc-license

Removing auth as it's for any spec, just that auth is likely the worst case for getting it wrong.

**Comment by jpstroop** [comment]
Does this conflict w/ our CC-BY claim on the specs at all?

**Comment by azaroth42** [comment]
I think we replace the License section with CC-BY, and keep the Disclaimer section as is from the W3C doc?

**Comment by azaroth42** [comment]
I can make a PR to discuss in more detail?

**Comment by jpstroop** [comment]
:ok_hand:, that's a good place to start. Are we going to need legal review at some point?

**Comment by zimeon** [comment]
+1 to using the w3c disclaimer section.

I'm not sure we need the license section at all because we have CC-BY on each spec (and that is good IMO)

**Comment by azaroth42** [comment]
I put the license section in, just in case there's some document that doesn't get an explicit CC-BY added.

**Comment by azaroth42** [comment]
See: http://disclaimer.iiif.io/api/annex/notes/disclaimer.html

**Comment by zimeon** [comment]
I think some people may be more familiar with the short name than the full license name so I added "(CC-BY)" after "Creative Commons Attribution Required". Otherwise, page looks great.

**Comment by azaroth42** [comment]
:+1: to @zimeon's addition. Other +1s?

**Comment by mikeapp** [comment]
+1

**Comment by jpstroop** [comment]
:+1: to this, though should we then follow through and change e.g.:

> Copyright © 2012-2014 Editors and contributors. Published by the IIIF under the CC-BY license.

In each of the to something that references the note? W3C does:

> Copyright © 2015 W3C® (MIT, ERCIM, Keio, Beihang). W3C liability, trademark and document use rules apply.

Which is more than we have, but something like: 

Copyright © 2012-2015 [IIIF-C](#). W3C [license](/api/annex/notes/disclaimer.html#license) and [document use](/api/annex/notes/disclaimer.html#disclaimers) rules apply.

maybe?

**Comment by zimeon** [comment]
I think we should keep the license on each document, why add the extra level of indirection? And why mention W3C? Perhaps:

> Copyright © 2012-2015 Editors and contributors. Published by the IIIF Consortium under the [CC-BY](http://creativecommons.org/licenses/by/4.0/) license, see [disclaimer](http://disclaimer.iiif.io/api/annex/notes/disclaimer.html).

(see #525 for discussion of IIIF Consortium language)

**Comment by azaroth42** [comment]
:+1: to Simeon's version. It also means we can change the disclaimer at will.

**Comment by jpstroop** [comment]
:+1:

**Comment by tomcramer** [comment]
+1

- Tom





On Nov 11, 2015, at 7:28 AM, Simeon Warner <notifications@github.com<mailto:notifications@github.com>> wrote:


I think we should keep the license on each document, why add the extra level of indirection? And why mention W3C? Perhaps:

Copyright © 2012-2015 Editors and contributors. Published by the IIIF Consortium under the CC-BY<http://creativecommons.org/licenses/by/4.0/> license, see disclaimer<http://disclaimer.iiif.io/api/annex/notes/disclaimer.html>.

(see #525<https://github.com/IIIF/iiif.io/issues/525> for discussion of IIIF Consortium language)

**Comment by tomcramer** [comment]
This section of the disclaimer seems at odds with CC-BY:

The name and trademarks of copyright holders may NOT be used in advertising or publicity pertaining to this document or its contents without specific, written prior permission. Title to copyright in this document will at all times remain with copyright holders.

(CC-BY says we want people to attribute the creators. But then we ask them to ask us if it’s ok to use our names?)

I suggest we completely drop the whole stanza, then ask for legal review, starting with Stanford’s counsel.

- Tom





On Nov 10, 2015, at 2:24 PM, Rob Sanderson <notifications@github.com<mailto:notifications@github.com>> wrote:


See: http://disclaimer.iiif.io/api/annex/notes/disclaimer.html

**Comment by azaroth42** [comment]
The restriction is to prevent the use of the names of organizations in promoting products that are completely unrelated, other than as partial implementations of a specification.  Stanford, Cornell, Princeton, etc do not endorse some random product that happens to implement IIIF, and advertising the product with reference to our institutions is not allowed.

The CC-BY is, on the other hand, related to the reuse of the document, and does not relate to implementations of the specification described by the document.  Anyone can copy the Image API doc somewhere, make derivatives or anything else, but they have to refer back to the original following the CC license:

> You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.

So ... I think the second sentence actually fulfills the requirement that the W3C license has the additional sentence to cover.  And thus :+1: on removing the sentence from the disclaimer.

**Comment by azaroth42** [comment]
Updated the PR to reference from all of the specs, and remove the lowercase clause

**Comment by azaroth42** [comment]
@tomcramer has put it on the queue for Stanford general counsel to consider. Thus this issue is Blocked until we get that feedback.
