### ISSUE TITLE
Ignored Parameters for autocomplete?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#536]
We should report the parameters that are ignored by the autocomplete service in the same way as the search service does.  However we don't have a layer to put `ignored` on, as it's otherwise unnecessary (no total search results, no paging needed).

Proposal to put it on the response directly, as per:
  http://search.iiif.io/api/search/0.9/#response-1

**Comment by azaroth42** [comment]
Objections? Otherwise Ready?

**Comment by jpstroop** [comment]
I like the simplicity of this. Do we need to include the values of the parameters for any reason? This would make it possible to re-create the original request from the response. I don't have a use case, just sayin'.

**Comment by tomcrane** [comment]
I don't think I have a use case. Also want to avoid implying that the server ignored the specific value of the parameter, which is not the case - we're not saying "I'm not searching for that!"

**Comment by azaroth42** [comment]
I think we /are/ saying that the server ignored the parameter value, because it doesn't implement that sort of search?

> Servers must implement the q parameter, and should implement the motivation parameter, the others are optional to support. Parameters that are received in a request but not implemented must be ignored, and should be included in the ignored property of the Layer in the response, described in the next section.

**Comment by zimeon** [comment]
I think what @tomcrane was saying is that we aren't implementing the case where a _particular value_ of a particular parameter is ignored. Ie. an implementer might feel that a search for `motivation=oa:sarcasm` should not be supported because it is the lowest form of wit, whereas they might support `motivation=oa:praise` because their stuff is awesome.

Assuming we do not have a use case for the above then I agree that the value need not be in the response, just the parameter name.

**Comment by jpstroop** [comment]
:+1:

**Comment by azaroth42** [comment]
Ahh, I follow now! I don't have a use case for it. Could entertain it as optional if there is one?

**Comment by tomcrane** [comment]
Simeon has provided an example of what I was trying to say!

**Comment by jpstroop** [comment]
I'm just going on instinct. When we implemented the PUDL >8-9 yrs ago we found it easier to pass all of the params and values back to support, e.g., paging and error handling. Otherwise the server has to keep state in sessions, and things just generally have the potential to get ugly.

**Comment by jpstroop** [comment]
...but those may not be use cases for autocomplete.

**Comment by azaroth42** [comment]
As did we in SRW/SRU ... but that seems not to be the way things work now (provide link to follow nose, or nothing) and not convinced there's a requirement in autocomplete in particular

**Comment by azaroth42** [comment]
So ... good to go?
See latest text version:  http://search.iiif.io/api/search/0.9/

**Comment by jpstroop** [comment]
There is a typo in the second json example under 4.2: `"label": "bird"},` ...

**Comment by jpstroop** [comment]
Sorry,  not a typo, just need a newline and ident.

**Comment by azaroth42** [comment]
Fixed in search branch, will issue PR

**Comment by jpstroop** [comment]
:+1:
