### ISSUE TITLE
rel=canonical for degraded image?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#538]
We asked ourselves, in February:
    Is it useful to have a rel="canonical" header for degraded versions of images?

But didn't come to an answer. I think the answer is that it should point to the canonical degraded image, not the full image.

From: https://github.com/IIIF/auth/issues/8

**Comment by zimeon** [comment]
Two sentences from [RFC 6596]https://tools.ietf.org/html/rfc6596) to motivate discussion:

  * _The canonical link relation specifies the preferred IRI from resources with duplicative content._ [sec1](https://tools.ietf.org/html/rfc6596#section-1)
  * _The target (canonical) IRI MUST identify content that is either duplicative or a superset of the content at the context (referring) IRI._ [sec3](https://tools.ietf.org/html/rfc6596#section-3)

and it seems the key motivation is really search engine based _"index the canonical in place of this resource"_. Depending on the form of degraded image the semantics of the full non-degraded image being a superset seem plausible.  However, the point is to index the canonical one so it seems pointless to rel="canonical" to something that has restricted access. There is a warning that

 *  _\[the target should not be] an IRI that returns an error code, such as a 4xx response in HTTP._ [p3](https://tools.ietf.org/html/rfc6596#page-3)

I'm thus inclined to agree with Rob that if there is a canonical link then it should stick to the normal semantics of canonical URI for the particular request on the degraded image

**Comment by jpstroop** [comment]
Agree.

**Comment by azaroth42** [comment]
Close, no action?

**Comment by mikeapp** [comment]
Agree.

**Comment by zimeon** [comment]
Seems that we have agreement to close this issue, no change.
