### ISSUE TITLE
Update 2.0 example (at end of docs page) to include layers?

### ISSUE THREAD

**Issue by aeschylus** [IIIF/iiif.io#539]
The example response at the end of the documentation doesn't include layers in the manifest.

Where do layers go? 

Are they supposed to be dereferenced from `otherContent: [ ]` on the manifest? Or is there a `layers` property on the manifest itself. The spec is unclear on where they go and how they are retrieved.

If they _are_ on the manifest, they should be added to the example response.

**Comment by aeschylus** [comment]
If layers _aren't_ supposed to be top-level properties, then perhaps the manifest example can have an otherContent field on it, showing layers being referenced.

**Comment by azaroth42** [comment]
As only AnnotationLists go in Layers, and AnnotationLists are external to
the Manifest, there should be no reference from a Manifest to Layer, only
via the AnnotationLists.

On Mon, Aug 3, 2015 at 8:44 AM, aeschylus <notifications@github.com> wrote:

> If layers *aren't* supposed to be top-level properties, then perhaps the
> manifest example can have an otherContent field on it, showing layers being
> referenced.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IIIF/iiif.io/issues/539#issuecomment-127282621>.
>



-- 
Rob Sanderson
Information Standards Advocate
Digital Library Systems and Services
Stanford, CA 94305

**Comment by zimeon** [comment]
Additional text in 7.2 looks good, and changes to example in section 9. :+1:
