### ISSUE TITLE
Validation can only be at major version level?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#546]
Without introspection, validation can only happen at the major version number level.  We can't distinguish between a 2.1 basic manifest and a 2.0 basic manifest, as there would be (intentionally) no difference.  So ... should implementations try to keep 2.1 additions to the specifications separate from 2.0?

For Image API, this is logo/attribution/license.
For Presentation API, there are new hint values, rendering, navDate, etc.

**Comment by azaroth42** [comment]
Propose:  Close WontFIx. The Validators have a version setting already, which can turn tests on or off.

**Comment by jpstroop** [comment]
:+1:
