### ISSUE TITLE
/api/metadata/1.0 should state that the latest version is prezi 2.0

### ISSUE THREAD

**Issue by jpstroop** [IIIF/iiif.io#548]
Someone just sent me a reference to the metadata API without realizing that it is an earlier version of the prezi API.

**Comment by zimeon** [comment]
I was concerned with this sort of thing with the OAI specs and added a floating banner to specs as they were replaced with newer ones. See, for example, <http://www.openarchives.org/rs/0.2/format_investigation>.

**Comment by azaroth42** [comment]
+1.  At least it should have a nice red .warning block, floating or not.  Can fix this along with the styling.

**Comment by zimeon** [comment]
+1. Looks good at <http://quick-updates.iiif.io/api/metadata/1.0/>
