### ISSUE TITLE
Clarify @context can be array

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#554]
To allow extensions to actually be semantic, rather than implementations dropping the information when they're not resolved by the context.  The specification currently suggests that it needs to be in the encapsulating object, but this doesn't take into account that the extension may be at the Manifest level.

Action is to update the contexts section with more coherent description:
http://iiif.io/api/presentation/2.0/#linked-data-context-and-extensions

**Comment by zimeon** [comment]
Example of array at end of 4.3.5 is missing closing square bracket, and closing brace is italics

**Comment by zimeon** [comment]
Otherwise, :+1: for text

**Comment by azaroth42** [comment]
Fixed ] in https://github.com/IIIF/iiif.io/commit/97a24e64784265f623911e7f956db0f2b8ed61f6

**Comment by zimeon** [comment]
:+1:
