### ISSUE TITLE
Solve the identifier with slashes problem

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#555]
To allow implementations to parse from the right, and if prefix is known use the rest as the identifier.
Most implementations do it already somehow anyway, so we should bless and normalize the behavior.

**Comment by azaroth42** [comment]
Proposal: Implementation Note that states that implementations that have a fixed prefix SHOULD parse from the right and treat the remaining string as the identifier, regardless of slashes in the path or not.

**Comment by zimeon** [comment]
Need to be clear that this is _server_ implementations. Agree to putting in <http://iiif.io/api/image/2.1/#a-implementation-notes>

**Comment by mikeapp** [comment]
+1

**Comment by zimeon** [comment]
Revised proposal:
  * Image API server implementations may rely on components or frameworks that always unescape the URI path (e.g. WSGI, *other example*). In such situations, request URIs for a given prefix may be parsed from the right in order to handle identifiers possibly containing slashes.

**Comment by jpstroop** [comment]
The real challenge is in section 2:

> When the base URI is dereferenced, the interaction should result in the Image Information document.

If my URI comes in un-escaped, how can I distinguish between a bad request (400) and a bad identifier that happens to have slashes (404)?

**Comment by azaroth42** [comment]
I don't think you can determine other than with explicit implementation dependent logic. If you're resolving slashes based on a file system, then you could (for example) check the directory structure to see if the directory is there but not the image file?  

That said the effects of responding with 400 vs 404 are almost zero -- it's still an error, and there's no machine processable way to recover.  And neither (bad id, broken request) results in an info.json, so section 2 seems fine?

**Comment by jpstroop** [comment]
>If you're resolving slashes based on a file system, then you could (for example) check the directory structure to see if the directory is there but not the image file?

This is exactly what Loris does, and it's not a big deal for the file system resolver. For the HTTP resolver it's a bit more complicated, and at best you're making a HEAD request for every single request to make sure you've parsed the URI, and at worse actually having to hit an image for every request.

**Comment by azaroth42** [comment]
R4R at http://555_slashnote.iiif.io/api/image/2.1/#a-implementation-notes
