### ISSUE TITLE
Clarify context link header for info.json

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#556]
That it should be returned whenever the application/json media type is used, not when the ld+json media type is requested in Accept.

**Comment by jpstroop** [comment]
[JSON LD Spec 6.8](http://www.w3.org/TR/json-ld/#interpreting-json-as-json-ld):
> Please note that JSON-LD documents served with the application/ld+json media type must have all context information, including references to external contexts, within the body of the document. Contexts linked via a http://www.w3.org/ns/json-ld#context HTTP Link Header must be ignored for such documents.

**Comment by azaroth42** [comment]
Delete: If the regular JSON content-type is returned, then it is recommended that the server provide a link header to the context document. The syntax for the link header is below, and further described in section 6.8 of the JSON-LD specification. If the client requests “application/ld+json”, the link header may still be included but must be ignored. The entity body is identical regardless of the content-type, including the @context field.

From 5.1

**Comment by azaroth42** [comment]
Validator to warn if context is different from context link in the doc.

**Comment by zimeon** [comment]
But validator happy if: context link header not present, or if context link header present and matches `@context` in doc
