### ISSUE TITLE
[OSD] Work without tiles

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#562]
Raised this issue on OSD to support tile-less IIIF:
    https://github.com/openseadragon/openseadragon/issues/737

We should track and contribute.

**Comment by azaroth42** [comment]
Blocked by #544

**Comment by tomcrane** [comment]
Pull Request: https://github.com/openseadragon/openseadragon/pull/816

**Comment by iangilman** [comment]
Merged!

**Comment by azaroth42** [comment]
Woop woop! Thanks @iangilman and @tomcrane! :)  Closing here too
