### ISSUE TITLE
Kill Image API section 8.1

### ISSUE THREAD

**Issue by jpstroop** [IIIF/iiif.io#564]
[It's just 8.](http://image-21.iiif.io/api/image/2.1/#introduction-1)

**Comment by zimeon** [comment]
+1

**Comment by azaroth42** [comment]
+1

**Comment by mikeapp** [comment]
+1

**Comment by tomcrane** [comment]
+1

**Comment by azaroth42** [comment]
Rewrite section 8 to say that auth is a new API, link to /api/auth/ . Get rid of totally worthless sub-bullet. Happy to stick with /auth/ for EVAR.
