### ISSUE TITLE
URI template parameters table should mention both host and port?

### ISSUE THREAD

**Issue by jronallo** [IIIF/iiif.io#565]
Maybe the table that lists some of the parameters for the URI template should mention that the server parameter can include both host and port? Small clarification.

https://github.com/IIIF/iiif.io/blob/ca22d7fd669e7bc1ef4c56e24d829eb58255ac9b/source/api/image/2.0/index.md#2-uri-syntax

**Comment by zimeon** [comment]
Agree, change:

_The host server on which the service resides._

to something like

_The host server on which the service resides. May also include the port._

**Comment by jpstroop** [comment]
:+1:

**Comment by azaroth42** [comment]
:+1:

**Comment by azaroth42** [comment]
(Editors agree on above)
