### ISSUE TITLE
Use full URI template instead of base_url parameter

### ISSUE THREAD

**Issue by jronallo** [IIIF/iiif.io#566]
It would be clearer if the spec used the full URI template instead of using a "base_url" parameter in: "The full URL for an image with “default” quality in “jpg” format would be: {base_url}/{identifier}/full/{width},{height}/0/default.jpg"

This appears to be the only place base_url is used and it does not seem to be defined anywhere.

https://github.com/IIIF/iiif.io/blob/ca22d7fd669e7bc1ef4c56e24d829eb58255ac9b/source/api/image/2.0/index.md#51-image-information

**Comment by mikeapp** [comment]
+1  There's a definition of the Base URI in section 2 but that's not what's intended here.

**Comment by azaroth42** [comment]
+1 to spelling out server/prefix.
And in 2.1 it is: http://image-21.iiif.io/api/image/2.1/#technical-properties

Thanks Jason!

**Comment by zimeon** [comment]
Instances of the phrase "base URI" should consistently not capitalize the B of base.

**Comment by azaroth42** [comment]
Section 2.0 Server entry in table, add May include a port number

**Comment by jronallo** [comment]
While 2.1 does include a definition of base URI, the parameter "base_url" is only used in one place and is not defined like other template parameters.

**Comment by azaroth42** [comment]
Editors agree:  Replace "Base URI" with "base URI" and use the full URI pattern in the text of 5.2
