### ISSUE TITLE
Prezi recommends context link header incorrectly

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#578]
As per image discussion, the presentation API should not recommend returning the context in the link header, as it MUST be ignored anyway due to potential for conflict with @context in the representation.

Proposal: Delete from "If the regular " down to the end of the following example from section 4.2

**Comment by zimeon** [comment]
Corresponding change in image api was discussed in #556 in changed commit 87571a8. Agree change for this issue is good.
