### ISSUE TITLE
Travis should check JSON syntax?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#582]
Or did we think that this was a bad idea, due to not valid comments in the examples?

**Comment by jpstroop** [comment]
> Or did we think that this was a bad idea, due to not valid comments in the examples?

Yes, that. I think I wrote a terribly complex spec once that tried to parse them as javascript, and then gave up.

**Comment by jpstroop** [comment]
[This](https://github.com/IIIF/iiif.io/blob/master/spec/source/syntax_spec.rb#L15-L18) might even catch syntax errors as we're trying to style them as code.

**Comment by azaroth42** [comment]
Close wontfix?
