### ISSUE TITLE
Recommend against fragment URIs for Canvas

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#591]
As we recommend using #xywh= to identify a region of a Canvas, we should recommend against fragment URIs for Canvases.  Otherwise, you would end up with nonsense like:

`http://example.org/iiif/book1/manifest.json#canvas1#xywh=1,2,3,4`

**Comment by azaroth42** [comment]
Closing, in master :)

**Comment by zimeon** [comment]
Change in 9269382 looks good, agree done
