### ISSUE TITLE
Link to search from autocomplete?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#597]
The autocomplete could generate a link from the term/terms [ref: #535] to the appropriate search to run. This would be more REST/HATEOAS friendly than making the client construct the url by copying the match content into the q param of the search URL.

Example:  http://search.iiif.io/api/search/0.9/#response-1

(Was #535, before we coopted it into multi-term discussion)

**Comment by azaroth42** [comment]
Close won't fix?

**Comment by jpstroop** [comment]
Seems like #536 has us headed in that direction, right?

**Comment by azaroth42** [comment]
I think so. Would like confirmation / discussion. If it's not going to be consistently available then clients need to be able to construct the URL anyway, so if we're not willing to make it at least SHOULD if not MUST, then we should ignore it IMO.

**Comment by jpstroop** [comment]
Yeah, it should at least be SHOULD if we're going to do it at all.

**Comment by azaroth42** [comment]
:+1:s to close wontfix?

**Comment by jpstroop** [comment]
I'd like to discuss more. I'm leaning toward a _MUST_ do.

**Comment by mikeapp** [comment]
:+1: MUST

**Comment by tomcrane** [comment]
:+1: MUST

**Comment by azaroth42** [comment]
:+1: to MUST

**Comment by jpstroop** [comment]
:+1: to my leanings

**Comment by zimeon** [comment]
:+1: and agree on _MUST_ (of little value if optional)

**Comment by azaroth42** [comment]
Sorry, I rewrote autocomplete and did this at the same time as #535.  PR is #694.
