### ISSUE TITLE
Move Search motivated rels to Presentation

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#598]
Currently the search API adds the following relationships/properties:
* first: The first annotation list in a layer
* last: The last annotation list in a layer 
* next: The annotation list that follows the current one
* prev: The annotation list that precedes the current one
* total: The total number of annotations in a layer
* startIndex: The index in the total of the first annotation in the list

Which seem like they are not search specific, and if there was a set of static annotation lists within a layer, the properties would be valuable in general.

Thus I propose to instead add the above to the Presentation 2.1 spec, rather than in Search. 

This does not get rid of the need for a search context however, as there are also some search specific things like:
* ignored
* hits and all below
* all of the autocomplete response

**Comment by edsu** [comment]
:+1: It seems like these would be useful in collection paging as well.

**Comment by zimeon** [comment]
Agree with moving this to prezi 2.1

**Comment by azaroth42** [comment]
Branch:  http://paging_rels.iiif.io/api/presentation/2.1/
