### ISSUE TITLE
Context for Search/Presentation

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#599]
Currently search has its own context.  However, as the search response can include a huge amount of information from the Presentation API, this is going to provide a challenge in inter-api versioning.  For example, anything from Layer, AnnotationList, Annotation, Manifest and Canvas could legitimately be included in the search response. The Manifest features would be from `within` on the target canvas (see 3.3.3).

Proposal:

The search context should define *only* the explicit search features, and the response should have both the used Presentation API context and the Search context.  2.1 is explicit that multiple contexts are allowed, so we should use this feature.

**Comment by azaroth42** [comment]
Depends on #598

**Comment by azaroth42** [comment]
Implemented across paging_rels and search branches.

Specs:
http://search.iiif.io/api/search/0.9/
http://paging_rels.iiif.io/api/presentation/2.1/

Contexts:
http://paging_rels.iiif.io/api/presentation/2/context.json
http://search.iiif.io/api/search/0/context.json

**Comment by jpstroop** [comment]
> In some situations it may be too expensive to generate a complete set of annotations within a single annotation list, or manifests within a collection. This is especially likely to occur when the responses are dynamically generated. When an operation is too expensive is left entirely to the discretion of the server, however the server should also take care not to generate overly long responses that would be difficult for clients to process. In these situations the server may break up the response using [paging properties][paging].

 1. Broken Markdown at the end. Is it a relic? Looks like it's supposed to refer to this section.
 2. "When an operation is too expensive is left entirely" read like a typo to me at first pass. 

Proposal: 

In some situations, annotation lists or the list of manifests in a collection may be very long or expensive to create. The latter case is especially likely to occur when responses are generated dynamically. In these situations the server may break up the response using paging properties. The ideal length of a response is left to the server's discretion, but the server should take care not to produce overly long responses that would be difficult for clients to process.

**Comment by jpstroop** [comment]
Ahh, I see now that the markdown link should point to 3.5, #paging-properties

**Comment by azaroth42** [comment]
Closed in #652
