### ISSUE TITLE
Change URIs to HTTPS

### ISSUE THREAD

**Issue by jpstroop** [IIIF/iiif.io#601]
Breaking change for 3.x.x Image and Prezi API series.

**Comment by azaroth42** [comment]
Given this:  https://www.w3.org/blog/2016/05/https-and-the-semantic-weblinked-data/
(which I participated in some of the discussions towards)

I propose un-`defer` and close `wontfix`

Also for #604

**Comment by azaroth42** [comment]
Decision at the Hague is that all of our human readable documents (specs, website, etc) will be HTTPS, and all identifiers used by machines will remain HTTP (context, namespace, predicates, etc).

Thus this issue is closed, wontfix.
