### ISSUE TITLE
Use https or http URIs for new identifiers?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#604]
Assuming that #417 is addressed, should we create URIs that use the HTTPS or HTTP scheme/protocol for identifiers?  For example, should the context for auth 1.0 be:
- http://iiif.io/api/auth/1/context.json
- http<b>s</b>://iiif.io/api/auth/1/context.json

If HTTP is the decision, this would invalidate #601.  If HTTPS is the decision, the current changes are for Auth 1.0 and Search 1.0.  It would affect any future specifications as well, of course.

**Comment by azaroth42** [comment]
My intuition is for currently keeping http for the following reasons:

  * Having some contexts (or other identifiers) be https and some http would make for difficult to detect and debug issues.  Most clients would end up having to check for http://* and https://* which defeats the point of a _unique_ identifier.
  * We don't know about http2 yet, which has the potential of requiring TLS and thus http2 would be only https. Some clients and servers have already implemented it, so this may not be too far down the line. One would expect that http2's scheme would be http, not https.
  * We have already declared that http://iiif.io/api/image/ is the _unchanging_ protocol URI which we can't undo. Or we could but it would be definitely :blush:, and doubly so if http2 drops the s and we have to change it back. 
  * We haven't actually addressed #417 yet. 
  * I don't believe there's a mixed [passive or active] content issue here?

So my proposal is to at least defer this along with #601, and prefer to close both wontfix.

**Comment by zimeon** [comment]
Perhaps on the call you can say more about http2. I certainly agree that we should do #417 with highest priority, both this and #601 are less urgent.

**Comment by azaroth42** [comment]
Strike the http2 issue. An update since I last checked adds back http over clear text, whereas previously it was all TLS: https://tools.ietf.org/html/rfc7540#section-3.1

**Comment by azaroth42** [comment]
Propose close wontfix, continue to use http.

**Comment by jpstroop** [comment]
:+1: to wontfix; we certainly can't require HTTPS

**Comment by zimeon** [comment]
How about defer to 3.0 instead of wondtfix? We should perhaps consider again in a bit

**Comment by jpstroop** [comment]
+1 to defer

**Comment by tomcrane** [comment]
:+1: to defer

**Comment by azaroth42** [comment]
:+1: to defer

On Fri, Dec 11, 2015 at 8:12 AM, Tom Crane <notifications@github.com> wrote:

> [image: :+1:] to defer
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IIIF/iiif.io/issues/604#issuecomment-163861238>.
>



-- 
Rob Sanderson
Information Standards Advocate
Digital Library Systems and Services
Stanford, CA 94305

**Comment by sdellis** [comment]
Does deferring this prevent the Auth spec from coming out of draft?

**Comment by jpstroop** [comment]
I think we can keep HTTPS in examples in the auth spec where it wouldn't make sense to do anything else, but stay silent otherwise.

**Comment by azaroth42** [comment]
This issue is only about iiif minted uris, not implementations. Auth implementations not using https should reconsider their understanding of security ;)

**Comment by azaroth42** [comment]
W3C has recently discussed this and the decision was:
 * All documents MUST be https
 * All namespaces and other identifiers remain as http

The rationale is that the identifiers often already exist, and don't need to be dereferenced in real time. Best practice is to ALSO provide whatever representations of the resources using https, but it's on the client to try https first.

For example: https://github.com/w3c/web-annotation/issues/347

Eds on 2016-09-21 call propose that this be closed with the decision of stick with HTTP

**Comment by azaroth42** [comment]
And thus propose close wontfix, we'll keep using HTTP URIs.

**Comment by jpstroop** [comment]
:+1:

**Comment by zimeon** [comment]
:+1: to close wontfix -- looks like we agreed a while ago and should just do it?

**Comment by azaroth42** [comment]
Yep. Re-open if anyone disagrees.
