### ISSUE TITLE
Hotspot linking

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#611]
A use case from National Library of Norway: There are areas in the canvas that should be linked to either other canvases or external documents.  For example, linking from "continued on page 5" to the region on page 5 where the article is continued, or linking a reference to something to a description of it.

Open Annotation has a "linking" motivation that seems appropriate and could be added as a subsection in section 6 of prezi/2.1

```
{
  "@id":"http://www.example.org/iiif/book1/annotation/anno1",
  "@type":"oa:Annotation",
  "motivation":"oa:linking",
  "resource": {
    "@id":"http://www.example.org/page-to-go-to.html",
    "@type":"dctypes:Text",
    "format":"text/html"
  },
  "on":"http://www.example.org/iiif/book1/canvas/p1#xywh=500,500,150,30"
}
```

**Comment by jpstroop** [comment]
I hesitate to say it :sweat_smile:, but this seems straightforward, and I agree, `oa:linking` seems appropriate. :+1:

**Comment by zimeon** [comment]
It does seem like the OA folks may have baked in a solution for us already, +1

BTW, since it was mentioned recently I am reminded that we should be better at recording use cases in <https://github.com/IIIF/iiif-stories/issues> and linking to them from discussions...

**Comment by azaroth42** [comment]
Good on those OA folks :smile_cat: Seems like they actually thought about what people use Annotations for. :pat_self_on_back:

Ahem. And yes, getting use case descriptions and linking them would be good. Perhaps some hacking / documenting time in Ghent to solve #64 (two digit issue!)?

**Comment by azaroth42** [comment]
See: http://prezi_issues.iiif.io/api/presentation/2.1/#hotspot-linking

**Comment by zimeon** [comment]
:+1: after minor typo fix (a04b120)

**Comment by jpstroop** [comment]
Content is fine, I think style is inconsistent. "Annotation" is capitalized throughout this new section, and not elsewhere.

**Comment by mikeapp** [comment]
👍 Looks good.
