### ISSUE TITLE
Change Log for Image API release

### ISSUE THREAD

**Issue by jpstroop** [IIIF/iiif.io#614]
I can start to work on this while everyone else is en route to Ghent :cry:. For Image API so far I have:

 * Added `square` region
 * Removed recommend about JSON-LD context link header (I think--was it wrong)?
 * Added optional Rights and Licensing properties to info
 * Added a warning about inconsistency the sizes list and the canonical URI syntax
 * Misc editorial fixes and clarifications

**Comment by azaroth42** [comment]
That looks correct to me.  And yes the context link header was wrong -- it should only be included if there isn't `@context`, not if content-type isn't `application/ld+json`.

**Comment by jpstroop** [comment]
Do after #642 is merged

**Comment by zimeon** [comment]
#642 has been merged, would be good to get this up to date as we head toward 2.1

**Comment by jpstroop** [comment]
Incomplete, based on 22 March LDCX session:

 * square
 * max area / w / h
 * "Full" size deprecation
 * canonical
 * attribution

**Comment by azaroth42** [comment]
* sizeByForcedWh
