### ISSUE TITLE
Change Log for Prezi API 2.1 release

### ISSUE THREAD

**Issue by jpstroop** [IIIF/iiif.io#618]
We need one

**Comment by jpstroop** [comment]
Incomplete, based on 22 March LDCX session:

 * Total Reorg or spec
 * Paging
 * "facing pages" viewing hint (two up)
 * "multi-part" viewing hint (distinguish multi-vol work from actual collection)
 * Clarify "continuous" viewing hint
 * "rendering" for, e.g., linking to PDF, HTML, epub, etc.
 * members
 * multiple logos
 * navDate
 * Ranges can link to Layers (contentLayer)
 * Hotspot linking

**Comment by azaroth42** [comment]
Done (along with setting of milestones and labels on all the issues)

**Comment by zimeon** [comment]
ref: #803
