### ISSUE TITLE
editorial: explain relation of Image Information request vs Image Information service

### ISSUE THREAD

**Issue by VladimirAlexiev** [IIIF/iiif.io#624]
http://iiif.io/api/annex/services/#services says that the Image Information service should not be used in the Image API and can only be used in the Presentation API.
I find this very confusing, since this returns exactly the same info as the Image Information request of the Image API (http://iiif.io/api/image/2.0/#image-information).

Please add a note in the table explaining that the Image API already includes such request (provide link), and that's the reason why it shouldn't be used as a "plugin" or "extension" service in the Image API.
Or have I misunderstood the whole idea?

**Comment by azaroth42** [comment]
In 2.1 it's actually possible to embed info.json inside another info.json, for access to an image service providing a logo.  So N/A is actually just wrong, it should be OPTIONAL.

Fix Branch: http://friday_issues.iiif.io/api/annex/services/

**Comment by zimeon** [comment]
This needs a bit more work. Should say inclusion of `logo` not `icon`, and there is a non-backticked `info.json`. I wonder how we should deal with the reference to "version 2.1"? I think this should certainly be explicit and say Image API but perhaps make it suggest future versions too with

> With the `logo` property added to the Image Information description in version 2.1 of the Image API, it is possible and reasonable for one `info.json` response to embed another using this pattern. In this case, the second service is related to the logo that should be displayed when a client renders the image described by the main response.

Finally, as 2.1 is not yet released, is it appropriate to add this note about logo to the services document yet?

**Comment by azaroth42** [comment]
Added changes from @zimeon as above. I think it's reasonable to refer to a just-about-to-be-released version?

**Comment by jpstroop** [comment]
I added a conditional that inserts " (forthcoming)" until we change to 2.1. :smile:

**Comment by jpstroop** [comment]
:+1: otherwise

**Comment by VladimirAlexiev** [comment]
Should explain the OPTIONAL icon.

Add after the table: 
Using the [Image Information](http://friday_issues.iiif.io/api/annex/services/#image-information) service 
inside the [Image API](http://iiif.io/api/image/2.0/) is only needed for the case of nested info.json (see next section). For the normal case, use the [Image Information](http://iiif.io/api/image/2.0/#image-information) request that is natively available in the Image API.

IMHO, change "embedded" to "nested".

3.1 says that `@context` is mandatory. But the nested info.json (last example) is missing this key. I understand there's no need to repeat it (it's on top), but on the surface it doesn't meet the requirement.

You got double slashes in the last example:
`"@context" : "http://iiif.io/api/image//context.json"`
and here:
`"profile": "http://iiif.io/api/image//2/level2.json"`
