### ISSUE TITLE
Fix segments example aspect ratio

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#627]
The aspect ratio of the image segments should be the same as on the canvas.  Explicitly say that they _can_ be different if necessary. 

Fix the examples in 2.1 section 6.1: http://iiif.io/api/presentation/2.1/#segments

**Comment by aeschylus** [comment]
:+1: 

Is the client expected to stretch it to fit, or is any behaviour acceptable?

**Comment by azaroth42** [comment]
SHOULD scale to fit, but it seems super edge case. 

Fix branch: http://friday_issues.iiif.io/api/presentation/2.1/#segments

**Comment by zimeon** [comment]
+1

**Comment by jpstroop** [comment]
:+1:

**Comment by mikeapp** [comment]
:+1:
