### ISSUE TITLE
Should seeAlso map to foaf:page?

### ISSUE THREAD

**Issue by zimeon** [IIIF/iiif.io#638]
In the [presentation API context](http://iiif.io/api/presentation/2/context.json), maps to [foaf:page](http://xmlns.com/foaf/spec/#term_page) which is defined as:

> The page property relates a thing to a document about that thing.
>
> As such it is an inverse of the topic property, which relates a document to a thing that the document is about.

**Comment by jpstroop** [comment]
I feel like we discussed this during the Voodoo Bunny sessions, and decided against it. Can't remember why though,

**Comment by azaroth42** [comment]
Seems a very strange mapping, given the description in Prezi of seeAlso:
> A link to a machine readable document that semantically describes the resource with the seeAlso property, such as an XML or RDF description. 

I am :+1: to changing it, but don't have a proposal for a new term yet.

**Comment by azaroth42** [comment]
How about just `rdfs:seeAlso` ?
> https://www.w3.org/TR/rdf-schema/#ch_seealso

**Comment by jpstroop** [comment]
> `rdfs:seeAlso` is an instance of `rdf:Property` that is used to indicate a resource that might provide additional information about the subject resource.

Works for me :+1:

**Comment by zimeon** [comment]
:+1: to `rdfs:seeAlso`. It has the essence of additional information/description but does not imply anything else
