### ISSUE TITLE
Change example of canonical link header to be something other the /full/full/0

### ISSUE THREAD

**Issue by zimeon** [IIIF/iiif.io#639]
Currently we have

> Link: <http://iiif.example.com/server/full/full/0/default.jpg>;rel="canonical"

and since we are pointing out that /full/full/0/ might not be available, we should not use this in the example.

**Comment by jpstroop** [comment]
See also #620, #621

**Comment by azaroth42** [comment]
:+1: to changing the example

**Comment by jpstroop** [comment]
:+1: (as stated on the PR)
