### ISSUE TITLE
Allow link between Range and Layer

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#645]
Some content types, such as newspapers, have both physical and very different logical/textual structures.  Articles can start on some part of the first page (canvas1) and continue on some part of the fifth page (canvas5).  

Presentation Use Cases:
  * A viewer might wish to display all of the OCR'd / transcribed text of the article, regardless of which canvas is in the primary view. 
  * A viewer might wish to synchronize the display of the image with the text that is being scrolled, and hence jump from canvas1 to canvas5
  * For articles that are part of the same canvas, but split between columns, the viewer may wish to synchronize the display and refocus within the same canvas when the article text is scrolled across the columns
  * For export, it would be valuable to associate the metadata of the article (range1) and the content (the annotations), for example in an export to PDF

Modeling requirements:

A page is a canvas, an article is a range (that can span canvases), and the content is linked via annotations.  Those annotations can be in one or more annotation lists.

Issue:

There is currently no way to associate the content (annotations) with the article (range), other than a lot of math to calculate the overlap of all annotations that target the canvas with the area of the canvas that is part of the range.  This is not necessarily actually correct, as there may be commentary or other annotations that are NOT part of the article. It would be impossibly expensive to do this in the client at run time.

Proposal:

Allow a link between the Range that represents the article, and a Layer that collects together one or more AnnotationLists, where each AnnotationList contains the annotations that target a particular canvas, or contiguous region within the canvas.  This would allow the UA to follow the link from the article to the layer to the annotationlists to the annotations without complicated math. 

Thus, we add a range specific relationship (name TBD) to point to the layer.

![newspaper-iiif-model](https://cloud.githubusercontent.com/assets/871868/11714732/8909fa50-9f3c-11e5-9644-0d7533e0e3a1.png)

**Comment by jpstroop** [comment]
It hadn't occurred to be before today that Ranges could not include Layers...this seems like an obvious thing to me.

**Comment by azaroth42** [comment]
Is this 2.1 or 2.2?  If we can come up with a name, I'm motivated to put it in 2.1 as it seems like an easy win.

**Comment by tomcrane** [comment]
+1 to 2.1, it gets the Newspaper IG up and running!

**Comment by azaroth42** [comment]
I propose the name `contentLayer` for JSON, and `iiif:hasContentLayer` for RDF.  This captures the intent of the link, rather than a vanilla `layer` or `hasLayer`

**Comment by glenrobson** [comment]
We are working with Europeana at the moment to look at harvesting our Newspapers which would include this property so if it could make it into 2.1 it would be good for us.

**Comment by glenrobson** [comment]
Hi,

I'm just looking to implement this into our Newspapers but I was wonder what do layers look like? Can you list them at the end of the manifest like ranges? e.g.

```
"layers":[
  

{
  "@context":"http://iiif.io/api/presentation/2/context.json",
  "@id":"http://www.example.org/iiif/book1/layer/transcription",
  "@type":"sc:Layer",
  "label":"Diplomatic Transcription",
  // Other properties here ...

  "otherContent": [
    "http://www.example.org/iiif/book1/list/l1",
    "http://www.example.org/iiif/book1/list/l2",
    "http://www.example.org/iiif/book1/list/l3",
    "http://www.example.org/iiif/book1/list/l4",
    // More AnnotationLists here ...
  ]
}
]
```

or do they need to be external from the manifest like AnnotationLists with de-referenceable URIs?

Is it also true that the only link to a layer is through the within property on the AnnotationList?

**Comment by glenrobson** [comment]
I've had a go at this with external Layers and a manifest can be seen at:

http://dams.llgc.org.uk/iiif/newspaper/issue/3100021/manifest.json

an example range (article) is as follows:

```
{
    "@id": "http://dams.llgc.org.uk/iiif/3100021/article/ART12",
    "@type": "sc:Range",
    "label": "PEMBROKESHIRE FARMER'S CLUB.",
    "metadata": 
   [
       {
           "label": "Article Category",
           "value": "News"
       }
   ],
   "description": "—A quarterly meeting of this club took place at the Castle Hotel last Friday. when about 40 of the members dined. Mr Mathias, of Lamphey, presided. The implement raffled for was a grubber, which was won by Mr John Jones, of Bolton",
   "canvases": 
   [
       "http://dams.llgc.org.uk/iiif/3100021/canvas/3100023#xywh=1059,16272,3162,1206"
   ],
   "contentLayer": 
   [{
            "@id": "http://dams.llgc.org.uk/iiif/3100021/annotation/layer/ART12.json",
            "@type": "sc:Layer",
            "label": "OCR Article Text"
    }]
},
```
There is quite a lot of duplication as currently in the example a layer only ever contains the annotations for that article so there is a one to one relationship.
