### ISSUE TITLE
Change to run on travis container infrastructure

### ISSUE THREAD

**Issue by zimeon** [IIIF/iiif.io#658]
Since we don't have any `sudo` in our `.travis.yml` I think migrating (which will get us faster startup time) is as simple as adding `sudo: false`. See <https://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade>. I'll make a PR...

**Comment by jpstroop** [comment]
:+1: I just changed Loris to do this. The only thing that was weird was that the test suite was always exiting w/ `0` even when there were failures. I had to change my tests to executed w/ a Bash script, and that seemed to solve it.

Script:
https://github.com/loris-imageserver/loris/blob/development/test.sh

.travis.yml:
https://github.com/loris-imageserver/loris/blob/development/.travis.yml

**Comment by zimeon** [comment]
Hmmm...while setting this up for iiif-prezi I got an error from `py.test` on the container infrastructure that worked OK (see <https://travis-ci.org/zimeon/iiif-prezi/jobs/96792156>)
