### ISSUE TITLE
Need logic to make /api/search redirect to current version

### ISSUE THREAD

**Issue by zimeon** [IIIF/iiif.io#660]
Having merged the search branch (#652) we now have <http://iiif.io/api/search/0.9/> live but <http://iiif.io/api/search> shows a directory listing.

**Comment by azaroth42** [comment]
The redirects are at the apache layer, so I'll add when I get VPN'd in

**Comment by zimeon** [comment]
BTW, you could fix the other ones to be cleaner:

<http://iiif.io/api/image> -> <http://iiif.io/api/image/2.0/> (instead of http://iiif.io/api/image/2.0/index.html)

<http://iiif.io/api/presentation> -> <http://iiif.io/api/presentation/2.0/) (instead of http://iiif.io/api/presentation/2.0/index.html)

**Comment by azaroth42** [comment]
Done!

**Comment by zimeon** [comment]
All looks good. :+1:
