### ISSUE TITLE
Even if ugly, the "Technical Details" page needs to link to all spec versions (including old and draft)

### ISSUE THREAD

**Issue by zimeon** [IIIF/iiif.io#661]
Currently <http://iiif.io/technical-details.html> just shows 2.0 image and prezi APIs

**Comment by zimeon** [comment]
Instead of adding a list of all spec to the technical details page, I propose with 7a12b49
 adding just a third button "All IIIF Specifications" which then links to an index page /api/ that lists current, draft and old specs

**Comment by azaroth42** [comment]
I guess there's no automation possible. Seems a pain to have to remember to update it when we have the site level variables, but as it lists /everything/ we don't have all the info anywhere machine readable.
So ... :+1:

**Comment by tomcrane** [comment]
:+1: - with the current versions highlighted in some way (usually the second-to-last in the table I guess)

**Comment by jpstroop** [comment]
> I guess there's no automation possible.

We could probably find a way with a data file, but I don't think it would be worth the trouble.

**Comment by jpstroop** [comment]
(Oh, and :+1: )

**Comment by zimeon** [comment]
Please see and approve PR #669
