### ISSUE TITLE
Multiple logos?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#664]
Currently Prezi says that: 

> Any resource may have exactly one logo associated with it.

Is there a use case for allowing multiple logos? How about the manifest that refers to canvases from multiple institutions, or has metadata contributions from multiple institutions?  Should we instead say one or more?

**Comment by mattmcgrattan** [comment]
We have this use case. In production manifests with multiple source institutions. Also, if we build authoring tools, this is one of the primary use cases that the authoring tools will support.

**Comment by blalbrit** [comment]
Another use-case: for Parker images hosted by Stanford, we would like to include both the Parker Library and the Stanford logo.

**Comment by azaroth42** [comment]
Good enough for me. Will fix :)

**Comment by zimeon** [comment]
My concern about multiple logos is the viewer requirement. Currently we say:

> The logo _MUST_ be clearly rendered when the resource is displayed or used, without cropping, rotating or otherwise distorting the image.

Does the new requirement become:

> The logo or logos _MUST_ be clearly rendered when the resource is displayed or used, without cropping, rotating or otherwise distorting the image.

and is that going to be crazy for viewers if there are 2, 3, 4, or 10 logos? Can we or do we need to soften the display requirement? @tomcrane @aeschylus thoughts?

**Comment by sdellis** [comment]
I would like to add a different use case for multiple logos here.  Many organizations have specific requirements about the margins and padding around logos, sizing of logos, and different logos for different contexts.  Some variations may be for light rendering on a dark background (or vice versa), square vs. horizontal marks, etc.  See the [Knight Foundation's guidelines](http://www.knightfoundation.org/media/uploads/media_pdfs/knightstyleguide_October2012.pdf) for examples.  In this case, a single organization may have several different logos to use depending on the context.

**Comment by jpstroop** [comment]
This is a breaking change for clients, no?

**Comment by mattmcgrattan** [comment]
Purely in terms of client UI, I was imagining more that the relevant logo be displayed when a particular canvas has focus. So if we have a manifest with BnF, Bodleian, and Stanford content, the relevant logo be displayed when the relevant canvas is selected [in thumbnail view, or whatever] or when a particular image is open in a panning/zooming view.

I wasn't imagining that multiple concurrent logos would be up at once.

**Comment by sdellis** [comment]
The use case that @mattmcgrattan mentions is already covered in the spec, correct?  Each resource would contain its respective logo (only one each currently).  This also supports multiple logos being displayed at once to represent the manifest based on the content it contains, so this may also cover the use case @blalbrit describes. However, it doesn't support the use of multiple logos for dark vs. light backgrounds in my example.

**Comment by tomcrane** [comment]
If a manifest has a huge attribution notice AND multiple logos AND you're viewing on a phone or tablet, the viewer will have a hard time fulfilling its obligation to display the mandatory elements without totally obscuring the digitised object. This has been a real concern for the Wellcome Library, whose objects often get embedded in blog posts or newspaper articles with narrow columns. There is a tension between UX and institutional branding/attribution requirements. In the UV the logo is available in the more info panel but is not necessarily on screen when it loads - you might need to scroll:

http://universalviewer.io/examples/?manifest=http://www.wdl.org/en/item/14291/iiif/manifest.json

@jennpb can steer this conversation towards user experience concerns.

**Comment by tomcrane** [comment]
What I was getting at is that there may need to be an element of "best endeavour" in a client's attempt to fulfil its obligations to display the mandatory content.

**Comment by sdellis** [comment]
Google Cultural Institute [hides the logo behind "Details"](https://www.google.com/culturalinstitute/asset-viewer/beech-grove-i/9wFd3kwcmKrGVA?projectId=art-project) as @tomcrane describes in the UV.  Does anyone see a problem with this?  

It's not up to the API to determine how to display a logo in a viewer, but it should be able to supply data to the client so it can make that decision given the context.  In that sense, some additional information would be necessary if a single institution could provide multiple versions of their logo (dimensions, light/dark versions, display requirements, etc).

**Comment by azaroth42** [comment]
Multiple logos to choose from for a single institution would require a lot of information about how to make that choice.  That seems far beyond the scope of this discussion which is just whether or not to allow multiple logos.

Perhaps we can clarify that the viewer can display the logos and attribution somewhere appropriate, not necessarily visible without some user interaction. The slide out info panel seems quite reasonable to me.

**Comment by sdellis** [comment]
If we allow multiple logos (whether from the same institution or not) that may be displayed on the same background (unless they come with their own background) then you could easily get mixed light and dark logos.  IIIF could require that a background be supplied so that it doesn't matter whether the background is light or dark.  But it would be a concern if a logo could not be read or looked obviously worse than others.

**Comment by sdellis** [comment]
Come to think of it, background is a concern even for a single logo as we have no idea what the background of the viewer will be.  I'm particularly sensitive to this issue as I've had to "normalize" scores of Code4Lib sponsor logos recently for display on the web and it has involved more human intervention than should be necessary.  Not a IIIF use case per se, but related. 

At the very least, I could see either a viewingHint on the logo or require a background to ensure proper contrast and legibility.

**Comment by sdellis** [comment]
So, you are correct, @azaroth42, the discussion around logo display concerns should be a separate issue.  To tie the discussion back to this issue, displaying multiple logos is already possible for resources if the viewer aggregates them from their "child" resources.  The original question is whether a single resource should be able to contain more than one logo.  I can't personally think of a use case that would justify that at the moment.

**Comment by blalbrit** [comment]
@sdellis I think the Parker use-case mentioned above might stretch to the multi-logo per resource requirement: the resources "belong" to a library in Cambridge (which wants its logo displayed) and are being served by Stanford (who also want their logo displayed).

**Comment by jpstroop** [comment]
If we're talking about `logo` becoming an array this has to wait for 3.0, right?

**Comment by azaroth42** [comment]
The cardinality in 2.0 is not specified, so I don't think this is a breaking change.
See: http://iiif.io/api/presentation/2.0/#rights-and-licensing-properties

**Comment by sdellis** [comment]
@blalbrit Perhaps we need to be clear about the term "resource".  If my understanding of the term is correct, the Parker case would be covered by the existing spec since the Cambridge logo would be on the resource called "resource" and the Stanford logo would be on the "service" resource it contains.  Both logos could be displayed in aggregate "higher up the chain" on parent resources (i.e., on the image, canvas, manifest) depending on the needs of the viewing context.

**Comment by blalbrit** [comment]
@sdellis Makes sense, Sean - thanks for that.

**Comment by azaroth42** [comment]
@sdellis That works _iff_ you have a manifest. `logo` is also available in just the Image API, and there there's only one resource.  So in order to have both Parker and Stanford logos on a use of the _image_, you would need to have multiple in the info.json. 

(tagging image 2.1 as well!)

**Comment by azaroth42** [comment]
http://664_logos.iiif.io/api/presentation/2.1/#rights-and-licensing-properties
http://664_logos.iiif.io/api/image/2.1/#rights-and-licensing-properties

**Comment by jpstroop** [comment]
> Any resource may have a logo associated with it.

"a" seems to say least softly specify the cardinality.

**Comment by sdellis** [comment]
@azaroth42 I'm not sure I understand. It appears that even without a manifest, one could place a logo on the image and a logo on the service used to deliver the image in an info.json.  This is consistent with approach I described for the Parker example and still allows only one logo per resource.

**Comment by azaroth42** [comment]
@jpstroop Then we're in trouble, because many of the other descriptions use that pattern and we need to specify 0..n cardinality. e.g. 
> A manifest must have a label, ...
> A manifest should have a description, ...
> Any resource may have a license, ...

So it seems to me that either it's all breaking or multiple logos aren't breaking. I prefer the latter interpretation :)

**Comment by jpstroop** [comment]
I'm not trying to be difficult. As long as we all agree then I'm :+1:

**Comment by sdellis** [comment]
If there are multiple logos on an Image API resource, how would a viewer (or user) distinguish between attribution given to the content and that given to the service that's providing the content, as in the Parker example?  Should there be any distinction?
