### ISSUE TITLE
rendering and navDate need predicates

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#666]
The new 2.1 properties `navDate` and `rendering` do not currently have RDF predicates and hence can't be in the context until they do.  If they're in our own namespace (hopefully not) then we also need to include them in the ontology.

I think that `rendering` could be `dcterms:hasFormat`:

> A related resource that is substantially the same as the pre-existing described resource, but in another format.

The semantics of navDate (being not semantic but just about navigation) I think mean we should probably just include it in shared canvas. Otherwise dc:date is pretty vague and might cover it:

> A point or period of time associated with an event in the lifecycle of the resource.

**Comment by jpstroop** [comment]
:metal:

**Comment by jpstroop** [comment]
hasFormat seems straightforward. Also agree that navDate belongs in sc; while dc date isn't wrong, I don't think it's in the spirit of our intentions

**Comment by azaroth42** [comment]
Okay, will make a PR for `dcterms:hasFormat` and `sc:presentationDate`

**Comment by zimeon** [comment]
Yet again I failed to link up the PR with all the +1s correctly... it was #670
