### ISSUE TITLE
Let's link editor names to ORCID iDs in the specs

### ISSUE THREAD

**Issue by zimeon** [IIIF/iiif.io#674]
I think we should link editor names to ORCID iDs in the specs. This provides a future-proof way for us to provide descriptions of ourselves and links to other ids. See, for example, <http://www.openarchives.org/ore/0.9/jsonld>. I see 3 out of 5 of us have ORCID iDs already.

**Comment by azaroth42** [comment]
:+1:

**Comment by jpstroop** [comment]
Fine with me.

-Js

Sent via mobile. Please excuse typos, brevity, etc.

**Comment by mikeapp** [comment]
:+1: Just registered.

**Comment by mikeapp** [comment]
If @tomcrane registers, I can put together a PR over the break.

**Comment by azaroth42** [comment]
Is this a case for making an editors include, or we'll just tweak all of the specs to add the links?

**Comment by jpstroop** [comment]
Probably, and a data file

**Comment by tomcrane** [comment]
I have now registered: http://orcid.org/0000-0003-1881-243X

**Comment by azaroth42** [comment]
Data file fields:
```
name: Robert Sanderson
nameUrl: http://www.stanford.edu/~azaroth/
institution: Stanford University
institutionUrl: http://www.stanford.edu/
email: azaroth42@gmail.com
orcid: 0000-0003-4441-6852
```

s/t like that, to produce:

[Robert Sanderson](http://www.stanford.edu/~azaroth/), _[Stanford University](http://www.stanford.edu/)_
&nbsp;&nbsp;[azaroth42@gmail.com](mailto:azaroth42@gmail.com), ORCID: [0000-0003-4441-6852](http://orcid.org/0000-0003-4441-6852)

**Comment by jpstroop** [comment]
Sure. I don't really have a nameUrl these days, so as long as that one is optional...

**Comment by azaroth42** [comment]
nameUrl, institution, institutionURL, email and orcid should all be optional I think?

**Comment by mikeapp** [comment]
I wanted to ask what should happen if an editor changes institution, should the change apply globally (and hence retroactively if they worked on earlier specs)?

**Comment by jpstroop** [comment]
You can only change institutions with major revisions :smile:

**Comment by zimeon** [comment]
I think nameURL is the ORCID link, I don't think we need to have the ORCID iD show. I would not put an email and I don't really care about an institutionUrl (if you can't find Cornell. Stanford etc. then all hope is lost anyway). So I'd have simply:

[Simeon Warner](https://orcid.org/0000-0002-7970-7855), Cornell University

And given this, I would not use any fancy data file but instead just code the list of authors in each spec which addresses any change of institution issue which the ORCID link provides an up-to-date way to find the author.

**Comment by azaroth42** [comment]
Digirati is much less obvious, however. And future editors/institutions might also be less obvious.

Also, while I'm a fan of ORCID, I have many other identifiers listed on my homepage.  
I can see the point of dropping email addresses, if you want to have it on your home page then that's fine ... so how about: 

> [name](nameUrl), [institution](institutionURL) ([orcid][orcidUrl])

**Comment by mikeapp** [comment]
I agree with Simeon that we shouldn't use a data file, I think we shouldn't obliterate the institutional affiliation of the individual at the time the spec was authored.  An include might be best.   I'm fine with the format suggested by Rob and will implement if there aren't any objections.
