### ISSUE TITLE
Replace front page demo with carousel of showcase tiles

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#676]
The try it demo on the front page is horribly out of date (v1.1) and while it was great when IIIF was more technically focused, we've outgrown it as a community.

As a replacement, I propose a carousel of the showcase tiles.  We should also link to showcase.iiif.io in the header navigation bar, and solicit more tiles.

**Comment by jpstroop** [comment]
:+1:

**Comment by azaroth42** [comment]
Thoughts on: http://676_frontpage.iiif.io/ ?

**Comment by jpstroop** [comment]
"Highlights of IIIF" looks like it's missing css or in a different font? And it sounds awkward to me. Maybe just call it "Implementation Demos"?

**Comment by azaroth42** [comment]
It should be the same CSS as the announcement block.  It thought about Demos or similar, but wanted a bit less tech-y and more marketing-y.  How about just "Highlights"?

**Comment by jpstroop** [comment]
I think the font and background should be the same as this:

![screenshot from 2015-12-22 17-27-51](https://cloud.githubusercontent.com/assets/999701/11967509/7500d198-a8d1-11e5-99b4-20b4cc57d0d2.png)

**Comment by jpstroop** [comment]
(oops)

**Comment by azaroth42** [comment]
Updated...

**Comment by zimeon** [comment]
Perhaps redundant as I commented on the PR, but very strongly agree with getting the old Image API off the front page and replacing with showcase tiles.
