### ISSUE TITLE
sizeAboveFull is a security risk

### ISSUE THREAD

**Issue by jpstroop** [IIIF/iiif.io#683]
See this PR on Loris: https://github.com/loris-imageserver/loris/pull/199

As I said there, the new max stuff addresses this from one angle, but we should probably surface the security risk either in [section 10](http://iiif.io/api/image/2.1/#security-considerations) and/or where `sizeAboveFull` is explained.

**Comment by azaroth42** [comment]
:+1: to the solution of using maxFoo to record the largest sizeAboveFull. I would put it where sizeAboveFull is explained. Something like:

> Size of images may be requested larger than the “full” size, up to the size specified by `maxWidth`, `maxHeight`, and/or `maxArea` in the profile. If `sizeAboveFull` is supported, then setting a maximum size is _RECOMMENDED_ to prevent denial of service attacks by asking for huge images.

**Comment by jpstroop** [comment]
Since we have a Security Considerations section, we should probably reiterate there as well.

**Comment by azaroth42** [comment]
Rereading 10, I agree the second sentence should be there in some form.

**Comment by tomcrane** [comment]
At some point in the future we might need some more detailed advice to server implementers about detecting and handling IIIF-specific DOS attacks. For example, if someone is hammering your server with random size requests you could pull up the drawbridge and drop down to level 0 support only for the duration.

**Comment by mikeapp** [comment]
:+1: to adding text in both locations.

**Comment by zimeon** [comment]
:+1: to text in both places (and happy new year)
