### ISSUE TITLE
CFPs to go on

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#692]
The call for proposals for commissioned implementations needs to be easily discoverable on the website.  This goes triple for the CFP for the IIIF Conference, along with the event logistics itself (once finalized).

CFP text:  https://groups.google.com/forum/#!topic/iiif-discuss/T3Yn-o7I7ZI

**Comment by azaroth42** [comment]
Ready for review at http://692_cfp.iiif.io/community/cfp/

**Comment by jpstroop** [comment]
I think this is fine. If we're asking them to contact the team in advance for larger grants, should we include email addresses?
