### ISSUE TITLE
Add IIIF-C MOU to website

### ISSUE THREAD

**Issue by zimeon** [IIIF/iiif.io#704]
We've been meaning to do this for a while. Both a good description of the consortium (that evolves with time) and the MOU should be available. Propose that the root should be <http://iiif.io/consortium/> with then <http://iiif.io/consortium/mou/>

**Comment by azaroth42** [comment]
How about community/consortium/ ?

**Comment by zimeon** [comment]
Hmm... I don't have very strong feelings but I thought consortium deserved a top-level path (and the URIs are shorter this way)

**Comment by jpstroop** [comment]
:+1: to `/community/consortium/`

**Comment by zimeon** [comment]
Moved under /community/ and added a link in the /community/ page
