### ISSUE TITLE
Range range contradiction

### ISSUE THREAD

**Issue by jpstroop** [IIIF/iiif.io#707]
> Ranges _MAY_ include other ranges. This is done in a ranges property within the range. The values within the ranges list _MUST_ be strings giving the URIs of ranges in the list in the manifest.

> Ranges _MAY_ link to a layer...

**Comment by jpstroop** [comment]
We should have an example of a range linking to a layer here as well.

**Comment by azaroth42** [comment]
Clarified text and added example: http://range707.iiif.io/api/presentation/2.1/#range
