### ISSUE TITLE
Ranges MUST have a label

### ISSUE THREAD

**Issue by jpstroop** [IIIF/iiif.io#709]
Per 7.1, but we don't say this in 3.1. Is 3.1 meant to be an exclusive list?

Bigger question:  Should Section 3 be considered non-normative and all of the RFCisms moved to the sections about the individual data structures?

**Comment by azaroth42** [comment]
I would go the other way, per https://github.com/IIIF/iiif.io/issues/703#issuecomment-176293245
and put all of the types into section 3. Putting the usage into the different sections seems like it would be very repetitive.

**Comment by jpstroop** [comment]
:+1:

**Comment by azaroth42** [comment]
Combined to #710, closing this one (given stuck bigger question)

**Comment by jpstroop** [comment]
:+1:
