### ISSUE TITLE
Facilitate deeper links into the specs

### ISSUE THREAD

**Issue by jpstroop** [IIIF/iiif.io#728]
I've wanted to link to viewingHint about twenty times in the past year. Any objections to adding ids to the properties listed in section 3 to make this possible?

There's temptation to think about the difference between the URIs we've minted for our properties and the new hash URIs that would result from this. I don't feel a need to worry about it now...I'd just like to be able to add links to documentation to emails, etc.

**Comment by zimeon** [comment]
:+1: to adding ids from me. Wrt deref of the URIs we've minted -- we could at some stage have them redirect to these hash URIs in the specs, but agree we don't need to worry for now.

**Comment by azaroth42** [comment]
Sounds good to me! :+1: How does one add ids to elements in markdown?

**Comment by jpstroop** [comment]
> How does one add ids to elements in markdown?

Kramdown lets you do it the same way we do CSS classes in the spec now, e.g: `{: #viewingHint }` (we already have them for the deprecation warnings).

**Comment by jpstroop** [comment]
Bah...except it doesn't seem to work with with definition lists! I'll play a little more, but this may be over before it started.

**Comment by sdellis** [comment]
@jpstroop you just need to add ```{::options html_to_native="true" /}``` above your data.  I do this in Kramdown on my personal site.
