### ISSUE TITLE
Fix profile link in annex/services

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#731]
Missing major version expansion in services, from Chad Mills:

While reading through the documentation on http://iiif.io/api/annex/services/ under 3.1 I noticed this profile values which isn't in step with the rest.

```
      "profile": "http://iiif.io/api/image//2/level2.json"
```

**Comment by zimeon** [comment]
Examples used undefined `page.major`, replaced with `site.image_api.latest.major` instead
