### ISSUE TITLE
Prezi and Search are inconsistent re within

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#735]
Presentation says that:
> Each annotation list may be part of one or more layers.

Search says that:
> All of the pages are within a layer that represents the entire resultset of matched annotations.

Thus Prezi is 0..n, and Search is 1..1.  An AnnotationList as the result of a search cannot be within multiple Layers, and any ordering asserted about Lists would make a mess of Prezi's 0..n.

Propose dropping Prezi to 0..1

**Comment by zimeon** [comment]
:+1: - Problem with an annotation list being in more than one layer is that each annotation list that goes to make up a complete list of annotations (as related by prev, next, etc) is implicitly tied to one context. Reuse in another context (layer) with potentially different ordering would make the paging properties nonsensical/contradictory

**Comment by azaroth42** [comment]
Clarified in: http://within735.iiif.io/api/presentation/2.1/#linking-properties
