### ISSUE TITLE
Expected behavior for !w,h & not sizeAbove100

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#752]
Per @tomcrane's comment, it is currently not specified what is expected to happen in the situation where a server gets a request with !w,h for size (e.g. fit inside this box), where w and h are both greater than the image content and greater than 100% images (upsampling) is not supported.

For example, an image that is 600 wide, 400 high, and the requested box is 1200 square ... do you get the 600,400 image, or an error?

The spec says:
> The image content is __scaled for the best fit such that the resulting width and height are less than or equal to the requested width and height__. The exact scaling may be determined by the service provider, based on characteristics including image quality and system performance. The dimensions of the returned image content are calculated to maintain the aspect ratio of the extracted region.

So my proposal is that it is consistent with the letter of the law to return the full size image of 600x400, as the resulting height and width are indeed less than the requested width and height.

**Comment by tomcrane** [comment]
There was a thread on iiif-discuss that is very closely related to this - https://groups.google.com/forum/#!searchin/iiif-discuss/tristan/iiif-discuss/NSG0tGssSUw

**Comment by jpstroop** [comment]
My instinct is that there are plenty of edge case permutations of different params we describe, and we don't need to describe every possible scenario in detail. As @azaroth42 points out, we're technically covered by the language in the current draft, and I think trying to explain this case would only lead to confusion about `!` further down the road.

Using the scenario described above, I guess I would expect the server to upsample (within the boundaries of `max*`) if the server supported upsampling, but I really don't think we need to say anything about it.

**Comment by azaroth42** [comment]
Meaning ... close wontfix? If so, :+1: from me.

**Comment by jpstroop** [comment]
Unless there's a clear use case. Yes. You and I arrived at different conclusions, but unless there's a clear use case :+1: to wontfix

**Comment by zimeon** [comment]
:+1: to wontfix

**Comment by tomcrane** [comment]
I'm OK with wontfix. The spec has the crucial phrase "The exact scaling may be determined by the service provider" so if it's really important to you as a client, work a bit more and make the request for the image you really need. 

I think I would return the exact 600,400 image even if I supported upscaling; it's still confined to the box. I'd reserve upscaling for explicit requests above the original size.

Anyway, :+1:

**Comment by mikeapp** [comment]
:+1: wontifx
