### ISSUE TITLE
Named versions of Specs

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#756]
- [x] Image API 2.1:  Crowned Eagle
- [x] Presentation API 2.1: Hinty McHintface
- [x] Search API 1.0: Lost Summer
- [x] Authentication API 0.9.1: Table Flip
- [x] Authentication API 1.0:  Alchemical Key

**Comment by zimeon** [comment]
I want to have "Lost" in the name of the search API.  We are having a meeting at Stanford now, home of the Rose & Crown, which serves very find Lost Abbey beers so I think "Lost Crown" might be an option.

**Comment by azaroth42** [comment]
Some words we could use:
 * Cruise
 * Cardinal
 * Tree (house)
 * Water (house)
 * (Book) Tower
 * Tea (house)
 * Tap
 * Summer
 * Rose
 * Crown

**Comment by jpstroop** [comment]
Propose Hinty McHintface for prezi 2.1

**Comment by zimeon** [comment]
+1 on Hinty McHintface

**Comment by sdellis** [comment]
Ha! Love it. :)

**Comment by zimeon** [comment]
We have to wait to implement the last two until we have the 1.0 versions:
  * Search API 1.0: Lost Summer
  * Authentication API 1.0: Alchemical Key
others are done
