### ISSUE TITLE
Consider recommendations for use and interpretation of multi-language properties

### ISSUE THREAD

**Issue by zimeon** [IIIF/iiif.io#759]
Based on past discussion in <https://github.com/IIIF/mirador/issues/798>, it was suggested on [IIIF-Discuss]( https://groups.google.com/forum/#!topic/iiif-discuss/GARkC7LXlDU) that the spec should be more prescriptive about use and interpretation of multi-`@language` properties. In particular, at present the spec does not say how to deal with the case of repeated values (with no `@language` tag or the same tag) in conjunction with multiple @language tags. It is not clear how the following should be handled:

```
 {"label": "Published", "value": [
        {"@value": "Paris, circa 1400", "@language": "en"},
        {"@value": "Paris, environ 1400", "@language": "fr"},
        "Paris, c1400",
        "Something else"
      ]
  },
```

From editors discussion, options include:
  1. repeat label for multiple values to be displayed, list represents choice (of 1)
  2. single label but use HTML to express multiple values to be displayed, list represents choice (of 1)
  3. status quo format - all non-tagged values should be displayed _AND_ choose only one tagged value
  4. status quo format with fallback - display only one value, a non-tagged value is a fallback

**Comment by aisaac** [comment]
Here are pragraphs for suggested best practice on controling the number of values per language tag, and using values without language tags as default. I apologize for the verbosity and potential English mistakes...

> This specification does not constrain the number of values that can be present per language tag. However, having a choice of several values per language causes ambiguity: a client can either show all values, or pick one (either random or the first value found in the presentation data). A IIIF viewer could also concatenate all strings in one language in its display. This specification does not enforce any presentation strategy here.
> 
> However, data publishers SHOULD provide at most one value per language tag, and at most one value without language, as in the "Published" example from Appendix C, so as to remove ambiguities.
> 
> We do not specify a preferred recipe to generate one single value per language tag from original data with several values per language. API implementers can opt for the solution that matches best the presentation preferences for their images. For example, instead of having two values in the "Notes" of Appendix C, provider could supply one value that concatenates the two original values, e.g., "Text of note 1\nText of note 2", or by using appropriate HTML mark-up.
> 
> Following this practice enables to define a strategy for specifying default values for the case where presentation data does not include a client's preferred language. Providers CAN supply one (and only one) value without language tag so that the client can use it as default value. When following this practice, providers CAN perfectly re-use one of the language-tagged value as value without language tag, as in the following (derived from the example in appendix C):
> 
>     {"label": "Published", "value": [
>         {"@value": "Paris, circa 1400", "@language": "en"},
>         {"@value": "Paris, environ 14eme siecle", "@language": "fr"},
>         "Paris, circa 1400"
>         ]
>     }

**Comment by aisaac** [comment]
Btw editorial comments:
in http://iiif.io/api/presentation/2.1/#language-of-property-values I'd suggest to move the sentence "Note that RFC 5646 [...]" after the one with "This allows for full internationalization [...]" because it's less important (and I think we should want to encourage people to use sub-tags so much)

in appendix C the French example should probably be "[...]14e siècle" according to https://fr.wikipedia.org/wiki/XIVe_si%C3%A8cle

**Comment by sdellis** [comment]
Propose grouping values for which there's a choice (such as those with @language properties) in an array:
```
{"label": "Published", "value": [
        [{"@value": "Paris, circa 1400", "@language": "en"},
        {"@value": "Paris, environ 1400", "@language": "fr"}],
        "Something else"
      ]
  },
```

**Comment by zimeon** [comment]
@sdellis - It would be clear/useful to have a list of language-varying sets of statements but a two-level structure would be a breaking change and thus is not available as an option in 2.1 per semantic versioning.

**Comment by azaroth42** [comment]
Propose close, fixed by other issues and PRs.

**Comment by azaroth42** [comment]
Closing, duplicate, fixed.
