### ISSUE TITLE
Presentation Compliance?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#76]
Do we need a compliance table for presentation api features?
  Maybe? Can we define what a "level 0" manifest is? Or a level 0 client?

Do we need profile docs to describe the features present?
  No? Too many possibilities?  Too dependent on the individual manifests, and thus easier to introspect?

Do we need the protocol URI somewhere to say "This is IIIF"?
   I think so, given plan for OSD to support multiple collection sources, but then how does it interact with using it to determine IIIF Image API for tile sources?

**Comment by azaroth42** [comment]
Given understanding of semver #470 I think we can't do this until 3.x?

**Comment by azaroth42** [comment]
Given we've discussed this several times with always the thought to defer, I propose we `close` `wontfix`. Rationale:  There aren't clients that consume multiple JSON based presentation API like descriptions and need a simple way to route the query.  We also don't update often enough that the routing will make a difference, especially as you could check @context for something that looks like iiif.io/api/presentation/X/context.json.

**Comment by jpstroop** [comment]
Call on 2 August 2017: agree close.

**Comment by azaroth42** [comment]
Discussion on call of 8/2/17:  Different for different domains or media types, community groups could come to some consensus about how to do it and document their discussions.  This isn't a case of having software gracefully degrade, which is just a software engineering concern.  There are too many optional features that grouping them into levels is impossible. 

Agree to close.
