### ISSUE TITLE
Supporting "q" param should not be a mandatory server requirement in Search API

### ISSUE THREAD

**Issue by tomcrane** [IIIF/iiif.io#765]
The client does not have to supply a q parameter, but currently a service has to support it if supplied.

This precludes a service that is similar to the level 0 Image API, where a functioning and useful image service can be constructed from entirely static resources (e.g., files on disk).

#764 allows a server to return pre-computed annotation lists for a resource by different granularities.
A service could return all the annotations from a particular user, without also having to support text searching over them.

**Comment by azaroth42** [comment]
:+1:  to making it SHOULD

**Comment by zimeon** [comment]
:+1:  to _SHOULD_

**Comment by azaroth42** [comment]
should_q branch is ready to go, after drop_box is merged.

**Comment by jpstroop** [comment]
:+1:
