### ISSUE TITLE
Write language selection implementation note

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#770]
... with many many examples.

**Comment by azaroth42** [comment]
Is this actually needed given the new algorithm text in both specs?

**Comment by zimeon** [comment]
I think the text now in http://iiif.io/api/image/2.1/#rights-and-licensing-properties and http://iiif.io/api/image/2.1/#rights-and-licensing-properties is clear enough that no note is require. Agree close won't-fix.

**Comment by azaroth42** [comment]
Closing. Someone can reopen and write the note if they feel like it would be useful :)
