### ISSUE TITLE
A IIIF or An IIIF?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#772]
We should be consistent. Currently we have 15 "a IIIF" and 11 "an IIIF" in the site.

**Comment by tomcrane** [comment]
Newcomers will read "eye eye eye eff". Old-timers will read "triple-eye eff". Although it will grate more for the old-timers, I vote for "a IIIF" as less of a trip hazard for a newcomer.

**Comment by tomcrane** [comment]
grr... I mean the other way round! -  "an IIIF"

**Comment by tpendragon** [comment]
Best issue ever.

**Comment by zimeon** [comment]
I think I would also go with "an IIIF" as better for newcomers. (It is gonna catch us out though...)

**Comment by jpstroop** [comment]
@tpendragon you must have missed the camel vs. snake issue. #179

**Comment by azaroth42** [comment]
Could we solve the newcomer issue by adding a terminology section, or at
least adding a parenthetical (pronounced "Triple-Eye-Eff") at the top of
the spec?

R

On Fri, Apr 1, 2016 at 2:10 PM, Jon Stroop <notifications@github.com> wrote:

> @tpendragon <https://github.com/tpendragon> you must have missed the
> camel vs. snake issue. #179 <https://github.com/IIIF/iiif.io/issues/179>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/IIIF/iiif.io/issues/772#issuecomment-204498887>
>



-- 
Rob Sanderson
Information Standards Advocate
Digital Library Systems and Services
Stanford, CA 94305

**Comment by tomcrane** [comment]
We could have it as "a IIIF" in 2.1 but with a large and prominent warning that it will be deprecated in favour of "an IIIF" in a future version.

**Comment by tpendragon** [comment]
:+1: to a "pronounced" clause. We don't need another code4lib.

**Comment by tomcrane** [comment]
Until last week I had never read code4lib as anything other than lib rhymes with bib (and that's bib as in bibliographic, not bib as in imbibe...) :beers:

**Comment by jpstroop** [comment]
Yeah, I've never understood code4libe

**Comment by zimeon** [comment]
I think we are heading toward https://www.youtube.com/watch?v=Y6lJGD3Q9Qs ... if it were code4libe it would have ***ing e in it ;-)
