### ISSUE TITLE
Disable link checking for archival site pages

### ISSUE THREAD

**Issue by tomcrane** [IIIF/iiif.io#776]
Some pages on the site are old call notes, events and other archived material.

A broken link in these is not a build error - is there a way to prevent the link checker acting on these pages?

**Comment by azaroth42** [comment]
@jpstroop Did your recent change fix this? Can we close?

**Comment by jpstroop** [comment]
Yes. There is a rake task to check external links, but it's not being run by CI. CI is only checking our links.

Closing.
