### ISSUE TITLE
Rename Box to something less spatial

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#780]
Thinking forwards to annotations of time based media, it would be good to rename box to be less spatial (e.g. segment) to allow for searching within the time stream of audio.

**Comment by mikeapp** [comment]
Or should we follow media fragments (xywh= , t=)?

**Comment by azaroth42** [comment]
:+1: to rename box to xywh= to foreshadow additional t= param in the future.

**Comment by azaroth42** [comment]
Or take out box completely until we have a better handle on A/V and 3d?

**Comment by tomcrane** [comment]
We will need xyzwhd too, and combinations of regions over time (need some way of grouping sets of space and time params)

**Comment by mikeapp** [comment]
I'm in favor of dropping `box` until we have a better handle on AV & 3D.

**Comment by azaroth42** [comment]
Plus `xyr` for circular, and `xyzr` for spherical search :smile_cat:

**Comment by azaroth42** [comment]
xyr1r2 for oval, xyzr1r2r3 for ovoid ... :+1: to dropping box ;)

**Comment by mikeapp** [comment]
At a minimum we'd need:
x,y,z 
w,h,d 
t_start, t_stop

**Comment by tomcrane** [comment]
?xywh=10,10,10,10&t=npt:10,20 is one search, how do I send more than one?
