### ISSUE TITLE
Annotations on Sequence, Manifest, Layer, Annotation, and Range

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#80]
We don't have a slot for annotating the object; eg with provenance, commentary, geo, etc.

**Comment by azaroth42** [comment]
Request to be able to associate annotations with Ranges as well:
https://groups.google.com/forum/?hl=en#!searchin/iiif-discuss/range$20annotation/iiif-discuss/pFZ6MIlY1rI/UeRnFXJY6dwJ

**Comment by azaroth42** [comment]
Somewhat radical proposal:

Allow images and otherContent on Manifest, Sequence, Range and Canvas.
This would enable associating PDFs of the sequence or range, as well as comments about them in a way that's consistent with existing usage.

**Comment by zimeon** [comment]
Issue of association of PDFs spit off into separate issue, now ruled out-of-scope on this one.

**Comment by jpstroop** [comment]
Refinement: only allow `otherContent` (i.e. not `image`) on these types.

**Comment by jpstroop** [comment]
:+1: from GW tech group (and OK for 2.1)

**Comment by azaroth42** [comment]
As these *only* refer to comment annotations, and not painting, I propose to add this into section 7.7, with a second example of a link from a Range to an AnnotationList.

**Comment by jpstroop** [comment]
Closed by 669bce55f69a8630a1a82649c801807cefbcab45
