### ISSUE TITLE
A/V extensions for Presentation API

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#807]
The use cases for A/V resulted in the following ideas for the Presentation API:
- Allow a time dimension
- Make height and width optional [breaking change] for audio only manifests
- Allow a z dimension (for 3d)
- Allow Zones
- "gap" or "empty" viewingHint for intentionally non-content bearing canvases.
- Use of track media fragments as well as timed in annotations

(Some of the above could be Presentation 2.2)

**Comment by azaroth42** [comment]
Updated thinking:
 * Don't do 3d at the same time as AV
 * Zones are just canvases

Should be split into separate issues tagged Presentation and AV ... un`defer`ing so we can split and then close.

**Comment by tomcrane** [comment]
Split issue - https://github.com/IIIF/iiif.io/issues/1069

**Comment by azaroth42** [comment]
Existing issues:
* Time = #1069 
* H/W Optional = #1069 
* Zones = #42, replaced by #1191 

Set aside:
* Z index for 3d -- Not going to do 3d at the same time as AV
* Explicit gaps -- No need to have a hint, just no content on a canvas w/ duration
* Track fragments -- Channel (left/right) use case discussed, but no way to determine what to put in the track parameter of a media fragment without explicit format level information. Defer until there's some real implementations/requirements.

**Comment by zimeon** [comment]
Have added #1234 for the track fragments issue, closing this issue in favor of the more detailed ones.
