### ISSUE TITLE
Short circuit token service?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#810]
Can we postMessage() from the result of the login service with the token to use directly, rather than requiring a separate interaction?  The window could still auto-close after the message is posted.
We need to get a cookie for the non XHR interactions, but that's still possible.

From discussion with @nickstenning re Hypothes.is auth interaction pattern

**Comment by mikeapp** [comment]
We would still need a way to renew tickets.   Also a plus to have a pattern that easily extends to non-browser access.

**Comment by azaroth42** [comment]
Non-browser should work okay if the response from the auth system was the JSON that we currently get from the token service? Could be distinguished by giving an id param or not (re https://github.com/IIIF/iiif.io/issues/795#issuecomment-208814229)

**Comment by azaroth42** [comment]
Login service is UI (in a new window), Token service is Data (not in a new window). So should keep separate.
