### ISSUE TITLE
What should go into the sitemap for http://iiif.io/?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#824]
I propose _only_ putting in the current specs to the sitemap. Then googlers will come to the right place, rather than ending up at the metadata 0.9 API and thinking it's somehow current.

Meaning the sitemap look at the site level variables to determine what "current" is, rather than having to re-flag each page? (Not that that's a big deal given rate of spec change)

**Comment by jpstroop** [comment]
> I propose only putting in the current specs to the sitemap. Then googlers will come to the right place, rather than ending up at the metadata 0.9 API and thinking it's somehow current.

Yes. This is how it's currently set up.

>Meaning the sitemap look at the site level variables to determine what "current" is, rather than having to re-flag each page? (Not that that's a big deal given rate of spec change)

Much easier to just use the sitemap plugin, I think.

**Comment by jpstroop** [comment]
Oh, one amendment/clarification: I think beta specs and latest stable should both be in the sitemap (as it is now), e.g.:
``` xml
<url>
  <loc>/api/presentation/2.0/</loc>
</url>
<url>
  <loc>/api/presentation/2.1/</loc>
</url>
```

**Comment by mikeapp** [comment]
Would it be worth blocking crawlers from older spec versions via `robots.txt`?  I assume that as links to older versions accumulate they will still be found and indexed by Google.

**Comment by jpstroop** [comment]
Sure. Wonder if we build  the robots.txt w/ grep & awk, looking for `sitemap: false`?

*accepts challenge*

**Comment by azaroth42** [comment]
Close no-one-cares?

**Comment by zimeon** [comment]
I think close-done, we have implemented control with Jekyll settings and, IMO, the discoverability is fine:

```
> grep -r sitemap: source
source/api/image/1.0/compliance.html:sitemap: false
source/api/image/1.0/index.html:sitemap: false
source/api/image/1.0/rotation_calc.html:sitemap: false
source/api/image/1.1/change-log.html:sitemap: false
source/api/image/1.1/compliance.html:sitemap: false
source/api/image/1.1/index.html:sitemap: false
source/api/image/2.0/change-log.md:sitemap: false
source/api/image/2.0/compliance.md:sitemap: false
source/api/image/2.0/index.md:sitemap: false
source/api/metadata/0.9/index.html:sitemap: false
source/api/metadata/1.0/index.html:sitemap: false
source/api/presentation/2.0/change-log.md:sitemap: false
source/api/presentation/2.0/index.md:sitemap: false
source/api/presentation/2.0/zones.md:sitemap: false
source/api/search/0.9/index.md:sitemap: false
```

**Comment by glenrobson** [comment]
No longer relevant after split see new issue: https://github.com/IIIF/iiif-root-website/issues/9
