### ISSUE TITLE
Google notify fails due to Net::HTTP

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#828]
With the following:

```
(Backtrace restricted to imported tasks)
cap aborted!
NameError: uninitialized constant Net::HTTP

Tasks: TOP => notify:google
(See full trace by running task with --trace)
The deploy has failed with an error: uninitialized constant Net::HTTP
```

This happens after the site is built, so we can still deploy, but would be good to fix sooner rather than later.

@barnaclebarnes any ideas?

**Comment by barnaclebarnes** [comment]
Sorry about that. Its looks like it is missing the ruby standard library reference. Try putting this at the top of the `Capfile`

`require 'net/http'`

That should load the proper http library. I couldn't test the full run trough and my `rib` session had that loaded already.

**Comment by azaroth42** [comment]
And now:

> NameError: undefined local variable or method `application' for #<SSHKit::Backend::Local:0x007fa2ed0e8fe8>
Tasks: TOP => notify:google
(See full trace by running task with --trace)
The deploy has failed with an error: undefined local variable or method `application' for #<SSHKit::Backend::Local:0x007fa2ed0e8fe8>

**Comment by barnaclebarnes** [comment]
Apologies. I will try and get this up and running locally with a deploy so I can test properly. In the meantime.change `#{application}` to `#{:application}` on line 34.

**Comment by azaroth42** [comment]
I think we can close this?

**Comment by jpstroop** [comment]
I don't think we're notifying Google right now. Do we want to try?

**Comment by azaroth42** [comment]
Close no longer valid, as we don't do cap based deployment.
