### ISSUE TITLE
Collection structure for choice of manifest

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#842]
If there is a collection of manifests, and the intent is that the UI should prompt the user to choose which of those to view (and thus that there's no need to look at the rest), then there's a question as to how to convey the "choice"ness of that collection.

Some options:
- Nothing: the labels of the Manifests should be sufficiently clear
- Ensure the label of the Collection conveys the choice-ness to the user
- Create a viewingHint for collections to convey the choice-ness

Proposal from Newspaper WG is to try the first two options and see if it's sufficient, and then explore the third if not

**Comment by azaroth42** [comment]
October Meeting:  Seek feedback from Newspaper WG

**Comment by azaroth42** [comment]
@kestlund @glenrobson Any work in Newspapers around this? Can we move it forwards or close?

**Comment by azaroth42** [comment]
Ping @kestlund @glenrobson. Can we close wontfix at this stage?

**Comment by glenrobson** [comment]
I'm happy for it to be close wontfix. Option 1 in the description seems to be a solution until someone raises a use case which it wont work for.

**Comment by azaroth42** [comment]
Discussion on 8/2/17:  Works okay for NLW.  Closing.
