### ISSUE TITLE
Update code of conduct to cover all interactions

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#847]
Be they in person at events, online in slack or via email.

Tagging this as normative given the "rules" nature of the change... but social rather than technical.

**Comment by azaroth42** [comment]
Temporary link for proposed new version:
  http://conduct.iiif.io/event/conduct/

**Comment by zimeon** [comment]
Good start though I think we could tweak the wording in a few places. Title still has "event":

> IIIF -Event- Code of Conduct

and perhaps delete "social" in subtitle:

> All IIIF events and -social- interactions are covered by the following Code of Conduct.

The first 1.5 sentence seem a bit odd/repetitive to me, perhaps change:

< IIIF is an inclusive, friendly and safe collaboration opportunity. It was conceived and executed as ...

> The IIIF was conceived and executed as ...

The last two paragraphs seem very specific to events. Is it worth having a subsection specific to events or should these be generalized?

**Comment by azaroth42** [comment]
Revised version: http://conduct.iiif.io/event/conduct/

**Comment by zimeon** [comment]
:+1:
