### ISSUE TITLE
Annotation List "within" should be an array?

### ISSUE THREAD

**Issue by tpendragon** [IIIF/iiif.io#850]
`Each annotation list may be part of one or more layers.` and `If the annotation list is part of a layer, then this must be recorded using the within relationship in the annotation list response.` seems to be in conflict with the example annotation list:

```json
{
  "@context": "http://iiif.io/api/presentation/2/context.json",
  "@id": "http://example.org/iiif/book1/list/l1",
  "@type": "sc:AnnotationList",
  "within": {
    "@id": "http://example.org/iiif/book1/layer/transcription",
    "@type": "sc:Layer",
    "label": "Diplomatic Transcription"
  }
}
```

Should this be:

```json
{  
  "@context":"http://iiif.io/api/presentation/2/context.json",
  "@id":"http://example.org/iiif/book1/list/l1",
  "@type":"sc:AnnotationList",
  "within":[  
    {  
      "@id":"http://example.org/iiif/book1/layer/transcription",
      "@type":"sc:Layer",
      "label":"Diplomatic Transcription"
    }
  ]
}
```

?

**Comment by sdellis** [comment]
I suggested a while back that the examples should use arrays for any repeatable resource, even if there's only one object.  This was [rejected](https://groups.google.com/forum/?hl=en#!searchin/iiif-discuss/Are$20all$20resources$20repeatable$3F/iiif-discuss/DmEJE_VGIcI/-kSZGkrjCAAJ), so I think it is intentional, not a mistake.

**Comment by tpendragon** [comment]
:+1:

**Comment by azaroth42** [comment]
No, because the ordering of the withins is unimportant, so a singleton list is more easily expressed as just a link to the resource directly.  It is indeed intentional.
