### ISSUE TITLE
Layer MUST be dereferencable? 

### ISSUE THREAD

**Issue by tpendragon** [IIIF/iiif.io#851]
Spec says `The layer may be able to be dereferenced if it has an HTTP URI.`

But seeing as the layer itself isn't embeddable anywhere in the manifest, it seems pretty useless without that. Is the theory that one could check all the annotation lists referenced by otherContent, build up their within layers, and then generate layers that way?

**Comment by azaroth42** [comment]
It can be embedded in the individual AnnotationLists that are part of the Layer.
Such as the example here:
  * http://iiif.io/api/presentation/2.1/#layer
