### ISSUE TITLE
cap locked to 3.4 ; 3.5 installed

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#853]
[rsanderson@GT26940 iiif.io (master)]$ cap production deploy
(Backtrace restricted to imported tasks)
cap aborted!
Capfile locked at 3.4.0, but 3.5.0 is loaded

After doing bundle install to update from recent gem changes

**Comment by azaroth42** [comment]
Commented out the lock in config/deploy.rb and it works fine with 3.5.  Can we just delete the lock, @jpstroop @eefahy ?

**Comment by jpstroop** [comment]
I think that's OK, but `bundle exec cap production deploy` is the proper way around it.

**Comment by eefahy** [comment]
Yep, that. (RE: @jpstroop 's comment)

**Comment by azaroth42** [comment]
That doesn't work for me either:
```
[rsanderson@GT26940 iiif.io (conduct)]$ bundle exec cap production deploy
(Backtrace restricted to imported tasks)
cap aborted!
Capfile locked at 3.4.0, but 3.5.0 is loaded
```

**Comment by jpstroop** [comment]
You made a change somewhere in the cap config earlier. Change back, then
`bundle install`, and then bundle exec cap.... Really should do it.

-Js

Sent via mobile. Please excuse typos, brevity, etc.

**Comment by azaroth42** [comment]
It really doesn't though :(

```
[rsanderson@GT26940 iiif.io (master)]$ git status
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
[rsanderson@GT26940 iiif.io (master)]$ bundle install
Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
...
[rsanderson@GT26940 iiif.io (master)]$ bundle exec cap production deploy
(Backtrace restricted to imported tasks)
cap aborted!
```

**Comment by jpstroop** [comment]
`gem install bundler` as it suggests?

-Js

Sent via mobile. Please excuse typos, brevity, etc.

**Comment by azaroth42** [comment]
Yeah, tried that. (sorry!) Same error :(

**Comment by jpstroop** [comment]
Hmm. OK. I was seeing this warning:

```bash
$ bundle install
Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
```

Indeed Gemfile.lock says:

```
BUNDLED WITH
   1.12.3
```

But is wasn't breaking anything, just giving me a warning. I ran:

```bash
$ gem install bundler
Fetching: bundler-1.12.5.gem (100%)
Successfully installed bundler-1.12.5
Parsing documentation for bundler-1.12.5
Installing ri documentation for bundler-1.12.5
Done installing documentation for bundler after 4 seconds
1 gem installed
```

and now: 

```bash
$ bundle -v
Bundler version 1.12.5 <-------
```

I made a branch with no changes, and ran `bundle exec cap production deploy` and now I do get your original error:

```bash
$ bundle exec cap production deploy
(Backtrace restricted to imported tasks)
cap aborted!
Capfile locked at 3.4.0, but 3.5.0 is loaded

Tasks: TOP => production
(See full trace by running task with --trace)
jstroop@ltopstroop1:~/workspace/iiif.io (rando)$ cap production deploy
(Backtrace restricted to imported tasks)
cap aborted!
Capfile locked at 3.4.0, but 3.5.0 is loaded

Tasks: TOP => production
(See full trace by running task with --trace)
```

And it config/deploy.rb is locked at 3.4.0, so not surprising, though I'm not sure I ever realizes that Capistrano has it's own locking mechanism. I guess that's useful since not everyone uses it w/ bundler, but...kind of a pain. 

@eefahy: Advice? Do we need to do anything on the server to upgrade cap? Can we use the `>=` syntax (`lock '>=3.4.0'`) and safely avoid this in the future?

**Comment by azaroth42** [comment]
And now...

```
[rsanderson@GT26940 2.0 (master)]$ bundle exec cap production deploy
Stage not set, please call something such as `cap production deploy`, where production is a stage you have defined.
```

:dubious_about_the_benefits_of_this_face:

**Comment by konung** [comment]
Most likely you have two versions of your gem installed as global gem. SOmething like: 
capistrano (3.8.1, 3.8.0)
By default cap command will use the latest version of the capistrano 3.8.1
And your project is locked to the one that is lower version like 3.8.0

2 simple solutions:

1. use `bundle exec cap...` - bundler will use the version that your project is locked to
2. uninstall newer (unused) version of capistrano like so `gem uninstall capistrano`
