### ISSUE TITLE
Document the process and requirements for groups

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#864]
With an initial proposal of:
  http://groups.iiif.io/community/groups/framework/

The process and requirements around groups should be made more explicit.

IIIF-Discuss thread: https://groups.google.com/forum/#!topic/iiif-discuss/QwW0n3TFpd0

**Comment by azaroth42** [comment]
Notes:
  * Should refer to the Code of Conduct.
  * Should record expectations about working modes -- e.g. monthly or biweekly calls, doodle to setup initial times, etc.
  * Shouldn't imply that interest groups don't do "work" ... rename to specification/technical something?
    * The requirement is that there be a separation of groups that work on specifications (e.g. create IIIF branded, normative requirements that the community is prepared to both stand behind and implement), and groups that do not do this sort of work.
    * One suggestion was that WGs are created centrally which could be a cleaner, though less distributed, management approach.

**Comment by zimeon** [comment]
Separate work going on in IIIF-C Coordinating Committee to agree expectations and naming of IIIF community groups which supersedes this github issue. Closing.
