### ISSUE TITLE
Change "license" to map to dct:rights - redux for Image API

### ISSUE THREAD

**Issue by aisaac** [IIIF/iiif.io#868]
While checking the rights/license fields of IIIF, I encountered an oddity: both Image API and Presentation API use "license" in the JSON, as agreed in a previous discussion [1]. But the JSON contexts differ:
- the Image API context [2] maps "license" to dcterms:license
- the Presentation API context [3] maps "license" to dcterms:rights
My understanding of [1] is that the two contexts should have been updated so that "license" is mapped to dcterms:rights in both. If I'm right, the PR [4] was only a partial fix and should be extended to the Image API context [3].
First question is: am I right?

[1] https://github.com/IIIF/iiif.io/issues/636
[2] http://iiif.io/api/image/2/context.json
[3] http://iiif.io/api/presentation/2/context.json
[4] https://github.com/IIIF/iiif.io/pull/657/

**Comment by jpstroop** [comment]
> First question is: am I right?

I'm 99% sure you're correct. If the other eds agree, here's a PR to fix it: https://github.com/IIIF/iiif.io/pull/869

**Comment by azaroth42** [comment]
Oops, good catch @aisaac! Yes, agree that's a bug. They should both be rights.
