### ISSUE TITLE
Should `maxWidth` and `maxHeight` also be listed in `sizes`?

### ISSUE THREAD

**Issue by jpstroop** [IIIF/iiif.io#872]
Seems ugly that we have two places to include this info.

**Comment by azaroth42** [comment]
I would say yes, as it seems equally ugly that you'd have to check in two places for what sizes are available, especially as maxWidth isn't mandatory.  Before we had the max distinction, we included height and width in sizes. 

That said, I agree that its completely redundant.

**Comment by azaroth42** [comment]
Clarify in 2.1.1 ?

**Comment by zimeon** [comment]
Discussion at The Hague: agree that these are not redundant, should review text.

**Comment by zimeon** [comment]
Eds discussion: careful reading of the `sizes` description in http://iiif.io/api/image/2.1/#technical-properties does already make it clear that a server might sensibly include a `w,h` of `maxWidth, maxHeight` _"to let a client know the sizes that are available when the server does not support requests for arbitrary sizes, or simply as a hint that requesting an image of this size may result in a faster response."_. Decision that we won't try changing text.
