### ISSUE TITLE
Clarify viewingHint validity

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#878]
The viewingHint table should be consistent, with each entry starting with the validity.  Currently the canvas hints do not say that they're only valid on canvases.
(From iiif-discuss)

Open question as to whether this is a patch version change, as it makes the intended normative requirement explicit?

 * [x] fixed on 2.1.1 branch
 * [ ] merged to master

**Comment by jpstroop** [comment]
My instinct before I finished reading your comment was that this is just a clarification and could be a patch (2.1.1). Tagging for discussion in New Haven.
