### ISSUE TITLE
What is the canonical form of `max` size in 2.1?

### ISSUE THREAD

**Issue by jpstroop** [IIIF/iiif.io#883]
Presumably it will be `max` in 3.0. The calculated `w,` until then?

 * [x] fixed on 2.1.1 branch
 * [ ] merged to master

**Comment by zimeon** [comment]
In 2.1 I think the canonical form is `full` if that size is allowed, else `w,` if only a smaller size is allowed (my reading of the `size` entry in http://iiif.io/api/image/2.1/#canonical-uri-syntax )

**Comment by jpstroop** [comment]
That's my reading as well. I wonder if we should clarify, as we do with the `square` keyword for region just above it.

**Comment by azaroth42** [comment]
I agree with the reading too. We could clarify in a 2.1.1 but ... has anyone found it unclear in practice?

**Comment by jpstroop** [comment]
> has anyone found it unclear in practice

I questioned it while working on Loris over the weekend, which is why I raised the issue. I also think it's a good idea to be explicit about the canonical form of keywords. `full` is canonical, `square` is not...it gets confusing.

**Comment by jpstroop** [comment]
Time for a 2.1.1 label? Wasn't there something else?

**Comment by jpstroop** [comment]
Eds agreed on 2 Nov.: Add a second sentence to the deprecation warning explaning that w, is canonical for max until 3.0
