### ISSUE TITLE
Canvas @id SHOULD be dereferenceable in Appendix B, but MAY be dereferenceable in text

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#884]
Given that it was MAY in 2.0 before we had the additional table, and the text should trump the summary table, we should fix the icon in 2.1.1

 * [x] fixed on 2.1.1 branch
 * [ ] merged to master

**Comment by azaroth42** [comment]
And discuss what it should be in 3.0

**Comment by mikeapp** [comment]
👍 to fixing the icon

**Comment by zimeon** [comment]
:+1: to fixing icon
