### ISSUE TITLE
Collect IIIF Presentations on website

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#887]
How about the following structure:
- /about/presentations/
  - introduction
    - overview
    - usecases
  - api
    - image
    - presentation
    - search
    - auth
  - software
    - client
    - server
  - content
    - manuscripts
    - newspapers
    - museums
  - model
    - linked-data
    - shared-canvas
    - open-annotation
  - related

Do community groups get a space here, or do they have more fine grained control of their own community/groups/ space, and can put presentations there as desired?  How would one find presentations on newspapers in IIIF, for example?  I've put them here for now but that could be just a symlink or it could be a more finely curated set.

**Comment by azaroth42** [comment]
Also the various Youtube videos from outreach events and other recorded conferences / webinars etc.

**Comment by glenrobson** [comment]
Transferred to https://github.com/IIIF/iiif-root-website/issues/13
