### ISSUE TITLE
confusing phrase: "presentation based metadata"

### ISSUE THREAD

**Issue by kshawkin** [IIIF/iiif.io#889]
At http://iiif.io/technical-details/ , under "step 2", you might change "presentation based metadata" to "structural metadata".  I think that would be clearer.

**Comment by zimeon** [comment]
I agree that "presentation based metadata" isn't good, it doesn't even really make sense. However, "structural metadata" seems too restrictive: we have technical metadata, structural metadata, and additional metadata for presentation such as labels, rights information, etc..

**Comment by kshawkin** [comment]
Hmm, I see. How about "rendering metadata"?

**Comment by azaroth42** [comment]
Moved to new repo: https://github.com/IIIF/iiif-root-website/issues/14
