### ISSUE TITLE
Fix css for interaction ^H^H^H^H profile table in auth

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#894]
first child is backticked

**Comment by zimeon** [comment]
See first table in http://iiif.io/api/auth/0.9/#service-description

**Comment by zimeon** [comment]
There is a bit of a mess in the definitions for `.api-table` in `source/css/main.scss` and `source/css/spec-doc2.scss` -- really it would make sense to rationalize this but I don't want to go messing with too many moving parts so I prefer an additive change that we can be pretty sure won't break up old docs.

**Comment by azaroth42** [comment]
Fixed by #925
