### ISSUE TITLE
Ranges: should one or more `top` be required?

### ISSUE THREAD

**Issue by jpstroop** [IIIF/iiif.io#896]
UV and Mirador developers have both run across the fact that when you have ranges, you don't know where to start, other than by convention (i.e. the first in the list). Requiring would be a breaking change, but tightening up the SHOULD here:

> In order to present a table of the different ranges to allow a user to select one, every range MUST have a label and the top most range in the table SHOULD have a viewingHint with the value “top”.

A MUST seems completely sane to me.

Downstream: https://github.com/UniversalViewer/universalviewer/issues/364

/cc @rsinghal @edsilv @aeschylus

**Comment by azaroth42** [comment]
Breaking, so would be 3.0, but happy to upgrade to MUST at that point.

**Comment by azaroth42** [comment]
+1 to MUST in 3.0

**Comment by azaroth42** [comment]
Discussion 08/30:  This issue becomes meaningless in 3.0 as we have adopted nested ranges, per solution to #1070.  We don't need to require `top` as the top ranges are the ones that are referenced at the top of the manifest's `structures`.
