### ISSUE TITLE
Remove or update list of institutions in manuscript group

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#903]
The list of institutions in the manuscript community group page should be either removed or kept up to date.  Rationale is that it seems like a closed group by listing them in the description and may be off-putting for newcomers.

If the solution is to update the list, it would be good to be bullets at the bottom of the page rather than in the description.

(from #899)

**Comment by blalbrit** [comment]
Hi @azaroth42 - I think @zimeon stubbed that page out, not sure. Will have a look.

**Comment by blalbrit** [comment]
Um - oh yeah. I'll re-write this.

**Comment by zimeon** [comment]
Oh no, I'm implicated, mea culpa (though I'm sure I copied it from somewhere else)

**Comment by blalbrit** [comment]
lol - I'm sure it came from me originally - looks like the Ghent meeting summary.

**Comment by blalbrit** [comment]
https://github.com/IIIF/iiif.io/pull/904

**Comment by blalbrit** [comment]
@azaroth42 or @zimeon - getting a failed travis build on my PR - any idea what I'm doing wrong?

**Comment by azaroth42** [comment]
Nothing :) The test failure is unrelated to your changes. And is fixed by another PR, but could easily have been the link checker too.

**Comment by azaroth42** [comment]
Done! Thanks @blalbrit!
