### ISSUE TITLE
Can someone clarify this error?

### ISSUE THREAD

**Issue by aeschylus** [IIIF/iiif.io#913]
A number of manifests from Stanford and some other places that I've been testing with recently have turned up this error in the validator: 
Validation Error: Unknown resource class dcterms:Image from parent: sc:Manifest

What would need to be changed?

Example: 
http://iiif.io/api/presentation/validator/service/validate?url=https%3A%2F%2Fpurl.stanford.edu%2Fdb896gy7518%2Fiiif%2Fmanifest.json&version=2.0&format=html

**Comment by azaroth42** [comment]
It should be dctypes:Image not dcterms:

**Comment by aeschylus** [comment]
In the presentation API spec, there are some images with dctypes and others with dcterms.

**Comment by aeschylus** [comment]
http://iiif.io/api/presentation/2.0/#image-resources

**Comment by aeschylus** [comment]
Spec says dcterms, example is dctypes

**Comment by azaroth42** [comment]
Fixed in 2.1.  Will fix in the 2.0 text.
