### ISSUE TITLE
Prezi 2.0 says dcterms:Image in the text, should be dctypes

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#914]
Thanks to @aeschylus for pointing it out.

2.1 is not affected.

**Comment by zimeon** [comment]
I honestly don't think we should change old specs like 2.0. We might want to put "deprecation warnings" on the old specs like we have for <http://www.openarchives.org/rs/0.9/resourcesync> etc.

**Comment by azaroth42** [comment]
It's buggy though -- this isn't a change, it's a typo fix in case people are looking at the older documents.

Agree that we should put a warning on the older specs to point to the most recent. Not sure why Drew was looking at 2.0 rather than 2.1

**Comment by jpstroop** [comment]
We already knew about this and fixed it in 2.1 (why are we looking at 2.0???). It wouldn't be tough to push 2.0.1 for those who aren't aiming for 2.1, but I guess I don't really see the point. Maybe just add to the change log?

**Comment by azaroth42** [comment]
Close wontfix ?

**Comment by zimeon** [comment]
I agree, closing
