### ISSUE TITLE
auth implementations SHOULD use https

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#915]
From @nickstenning via email

:+1: from me

**Comment by tomcrane** [comment]
:+1:

**Comment by mikeapp** [comment]
👍

**Comment by jpstroop** [comment]
:+1:

**Comment by zimeon** [comment]
:+1:, I think it is also important to do this upfront rather than the current buried note. We could add to sections 1.2 and 1.3 and point out that because of the way tokens are passed around the entire image service SHOULD be HTTPS.

**Comment by zimeon** [comment]
@nickstenning's comment was "There's a small, easily-ignorable note about HTTPS in one of the appendices. With apologies for mounting the hobby-horse: I'd prefer to see TLS/HTTPS mandated for a spec like this that's passing long-lived credentials around in request bodies." ... so Nick is suggesting _MUST_, whereas we have so far agreed only on _SHOULD_.

**Comment by zimeon** [comment]
I feel a bit awkward that we aren't making HTTPS a _MUST_. I do see that for the Clickthrough pattern it perhaps isn't necessary but I still wonder whether the overhead of demanding HTTPS OK.

**Comment by jpstroop** [comment]
It's practically a _MUST_, but you're right about the clickthrough pattern.  I think _SHOULD IF YOU KNOW WHAT YOU'RE DOING_ would suffice.

**Comment by azaroth42** [comment]
Closed by #921
