### ISSUE TITLE
Clarify Auth spec might need more for REST of description resources

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#923]
Eds are confident that the Auth spec protects content resources (images, audio, video, etc) retrieved via regular HTTP interactions from the browser.  However when REST patterns are established, further issues that we haven't thought of or implemented may come up with authentication of the creation, updating and deletion of description resources.  These issues may result in changes to the Auth specification, however it is anticipated that these changes will be backwards compatible with 1.0.

Something like this should go in the new 1.4.

**Comment by zimeon** [comment]
I think this been dealt with adequately by second para of http://iiif.io/api/auth/0.9/#security -- propose close.

**Comment by azaroth42** [comment]
:+1: to close, fixed.

**Comment by jpstroop** [comment]
Just want to register that I don't feel completely confident that we can guarantee backward compatibility, based on how this has gone so far, but I think the language is loose enough that we're OK. :+1: to closing.

**Comment by tomcrane** [comment]
:+1:
