### ISSUE TITLE
Update Auth API Implementation Notes document

### ISSUE THREAD

**Issue by zimeon** [IIIF/iiif.io#924]
http://iiif.io/api/auth/0.9/implementation is left a bit behind at 0.9.1 and needs update for auth 0.9.3. See also #528

**Comment by zimeon** [comment]
I ripped the following out while stubbing the implementation notes section of the main auth doc (#921). I think these should be covered somewhere in the implementation notes document:

  * Care is required to implement this specification in a way that does not expose credentials thus compromising the security of the resources intended to be protected, or other resources within the same security domain.
  * Implementations must not reuse the access cookie value (or any simple transformation of it) as the access token value. Access token values could be copied across domains if the access token were to be obtained by a malicious client.
  * This specification is modelled after elements of the OAuth2 workflow and the [OAuth2 Security Considerations](https://tools.ietf.org/html/rfc6750#section-5) section provides useful additional guidance regarding threats, mitigations and recommended practices.

**Comment by zimeon** [comment]
I think we should say which version of the spec the Implementation Notes apply to but we should not version the implementation note _per se_, as we may want change it more frequently than the spec itself. I suggest including a change log where we date and comment updates, and point out alignment with minor version releases. Something along the lines of:

| Date | Description |
| --- | --- |
| 2017-01-01 | Comments about new version of Zirconium browser on ZeeOS |
| 2016-10-19 | Release with IIIF Authentication API v1.0 |

and then the **Status of this Document** section at the top should simply say which version of the auth spec it applies to.

**Comment by azaroth42** [comment]
Close?

**Comment by zimeon** [comment]
Agree close, completed with #921, #934 and #943
