### ISSUE TITLE
Auth spec 1.0 release candidate and final review plan (2016-10-05)

### ISSUE THREAD

**Issue by zimeon** [IIIF/iiif.io#926]
* Plan is to have [community review](http://iiif.io/api/annex/notes/editors/#community-review) meeting at The Hague Friday 2016-10-21 9am-10:30am CET (will allow remote participation though this is early (4am!) for US)
  * Freeze of spec must happen 2 weeks in advance: ie. before 2016-10-07 but lets work on 2016-10-05

Actions:
  * Bump version to 0.9.4 and put new log entries in auth spec and implementation notes
  * Announce spec and review session on IIIF-Discuss, IIIF-Announce (and other relevant community email lists?), thank contributors for feedback so far and solicit additional feedback by email

**Comment by zimeon** [comment]
Need to close off remaining other issues for [Auth 1.0 milestone]( https://github.com/IIIF/iiif.io/milestone/13) and then plan website update and announcement on Wednesday.

**Comment by zimeon** [comment]
**IIIF Authentication Specification** or **IIIF Authentication API** ? We have avoid saying the latter in spec., but then we have a URI `http://iiif.io/api/auth/`, talk about 'semantic versioning of APIs', list auth in the [IIIF API Specifications](http://iiif.io/api/) etc. etc.. IMO, we should just give in and avoid confusion by calling it the **IIIF Authentication API**.

Whichever way we so, we need to update the document title as it is currently inconsistent (**IIIF Authentication: Version 0.9.3**), should become

**Comment by azaroth42** [comment]
I'm okay with API.  It's a set of interaction patterns that you use to do authentication from end to end in the IIIF context.

**Comment by jpstroop** [comment]
Agree. API isn't perfect, but anything else might get confusing. I was
entertaining 'protocol', but I could see that giving the wrong impression.

-Js

Sent via mobile. Please excuse typos, brevity, etc.

**Comment by mikeapp** [comment]
I agree with API.

**Comment by zimeon** [comment]
Have made change to "IIIF Authentication API" and bump to 0.9.4 in #943

**Comment by azaroth42** [comment]
All of this is done :) Closing...
