### ISSUE TITLE
Remove link checker from travis tests on commit (or make it check internal links only)

### ISSUE THREAD

**Issue by zimeon** [IIIF/iiif.io#930]
I think it would be valuable to have a periodic link check run on the iiif.io site but in the current form it is either an inordinate waste of time (have to check for bogus failure every build) or, worse, dangerous (one starts to ignore travis failures).

I suspect the best thing would be to have a periodic link check running on the live site (say) weekly that posts status to Slack. But open to other suggestions.

**Comment by jpstroop** [comment]
I was just working on this! They're supposed to cache and only check every four weeks. I'm going to see if that's broken.
