### ISSUE TITLE
Image API 2.1 has wrong physdim @context URI in example

### ISSUE THREAD

**Issue by zimeon** [IIIF/iiif.io#935]
We have in http://iiif.io/api/image/2.1/#complete-response :

```
...
 "service" : [
    {
      "@context": "http://iiif.io/api/annex/service/physdim/1/context.json",
...
```

whereas in http://iiif.io/api/annex/services/#physical-dimensions it is correct as:

```
{
  "service": {
    "@context": "http://iiif.io/api/annex/services/physdim/1/context.json",
...
```

ie. must be `/services/` and not `/service/`. 

 * [x] fixed on 2.1.1 branch
 * [ ] merged to master

**Comment by zimeon** [comment]
& same applies to `profile`

**Comment by azaroth42** [comment]
Ooops :(  Image 2.1.1 ?

**Comment by jpstroop** [comment]
Agree, 2.1.1. There are a few of these, right?

**Comment by zimeon** [comment]
I was at first thinking we just log the change, but I agree it makes sense to use our patch numbering. As far as I can see there are only two cases. (I just checked every use of `@context` in the doc.)
