### ISSUE TITLE
Non-Rectangular reference to Image API unclear

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#941]
There is a reference to the Image API as a method to do non-rectangular areas of a canvas: 
http://iiif.io/api/presentation/2.1/#non-rectangular-segments

The ImageAPISelector (as used in example2 of 6.1) is good for extracting regions of an image, but not useful in selecting areas of a Canvas, which is not an Image.

Propose for 2.1.1 to remove this reference.

 * [x] fixed on 2.1.1 branch
 * [ ] merged to master

**Comment by sdellis** [comment]
Slight correction: it's suggested as an option for rectangular areas of a canvas (not non-rectangular).

**Comment by azaroth42** [comment]
Make "described above" link to the example that has the IIIF selector.
