### ISSUE TITLE
embed public IIIF google calendar on community page

### ISSUE THREAD

**Issue by srabun** [IIIF/iiif.io#945]
Link to calendar: https://calendar.google.com/calendar/embed?src=1hnm5h86n94ore0vnoo188ter8%40group.calendar.google.com&ctz=America/Los_Angeles

Embed code: <iframe src="https://calendar.google.com/calendar/embed?src=1hnm5h86n94ore0vnoo188ter8%40group.calendar.google.com&ctz=America/Los_Angeles" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>

**Comment by zimeon** [comment]
Wasn't this already done with #940 ? I see cal on http://iiif.io/community/groups/

**Comment by srabun** [comment]
Wow, y'all are way ahead of me. Thank you!

**Comment by jpstroop** [comment]
Sorry...I did it during the call yesterday ;-)
