### ISSUE TITLE
"@type": "sc:ViewingHint" prevents correct compaction

### ISSUE THREAD

**Issue by christopher-johnson** [IIIF/iiif.io#946]
I noticed an issue with the terms for sc:viewingHint not compacting.  Initially, I thought that this was the result of the mismatch between the @type for the term ("sc:ViewingHint") and the vocab @id ("sc:viewingHint"). 

For example, 
`"viewingHint": {
      "@id": "sc:viewingHint",
      "@type": "@vocab"
    },`
`"paged": {
      "@id": "sc:pagedHint",
      "@type": "sc:ViewingHint"
    },`

However, even with a matching @type for the term, the @vocab declaration does not work.  

@vocab should expand to a prefix URI, and the way that it is used here, it will expand to http://iiif.io/api/presentation/2#viewingHint.  It seems that sc:pagedHint cannot be associated to "paged" because a URI that looks like "http://iiif.io/api/presentation/2#viewingHinthttp://iiif.io/api/presentation/2#pagedHint" cannot be expanded.

If  "@type": "sc:ViewingHint" is removed, then then sc:pagedHint will compact to "paged" as intended.

See [this issue](https://github.com/json-ld/json-ld.org/issues/400) for reference.

**Comment by azaroth42** [comment]
I think the summary really is "@type": "sc:ViewingHint" prevents correct compaction.  ViewingHint is a class of which paged is an instance.

**Comment by christopher-johnson** [comment]
It seems that the design intent is for sc:viewingHInt to be used as a property for an instance of sc:Sequence.  If sc:pagedHint is intended to be a `subclass` of sc:viewingHint, which I suspect it was, then a new property should be created (e.g.  sc:hasViewingHint).   sc:pagedHint is its own class (not really an `instance`) in the range of sc:Sequence.  sc:pagedHint cannot be both a `subclass` and a `value` of the property sc:viewingHint, which is where the core problem may derive.  There is more than one issue here, and the use of `@vocab` is also a problem as indicated above.

**Comment by azaroth42** [comment]
`pagedHint` is an instance of the class `ViewingHint`, hence the inclusion of @type in the context.

In RDF:
```
_:mfst a sc:Manifest ;
  sc:viewingHint sc:pagedHint .

sc:pagedHint a sc:ViewingHint .
```

**Comment by christopher-johnson** [comment]
Why make sc:pagedHint an instance of sc:viewingHint?  This is probably unnecessary if sc:pagedHint is just a value.

**Comment by christopher-johnson** [comment]
FYI: I found a [test case ](https://github.com/json-ld/tests/blob/master/compact-0061-out.jsonld) that relates to this.  It seems that when `@type: @vocab` is used on a property, the value node is compacted.  If it is not, then  _value_ is returned as is.  So, casting `@vocab` on the active property is the only way to compact "sc:pagedHint" to "paged".  See also, the API spec on [Value Compaction](https://www.w3.org/TR/json-ld-api/#value-compaction) where it says that compaction can only occur if the "value consists of only an `@id` member"...

**Comment by azaroth42** [comment]
Ahha! Thanks for the sleuthing, Christopher :)

**Comment by zimeon** [comment]
:+1:
