### ISSUE TITLE
implementation demo of Stanford Mirador broken

### ISSUE THREAD

**Issue by jronallo** [IIIF/iiif.io#947]
On this page the "Stanford University Libraries - Mirador demo" seems to be broken:
http://iiif.io/apps-demos/

The BL demo in that list also appears to be old and at last partially broken. And the other examples here could probably be better to show the current state of Mirador.

@aeschylus @rsinghal FYI

**Comment by azaroth42** [comment]
I think the issue for iiif is to update the page, incorporating new and more reliable content from the awesome-iiif list.

**Comment by mikeapp** [comment]
Moved to https://github.com/IIIF/iiif-root-website/issues/22
@jronallo
