### ISSUE TITLE
Open Annotation terms missing from Search context

### ISSUE THREAD

**Issue by tomcrane** [IIIF/iiif.io#952]
In the Search example at http://iiif.io/api/search/1.0/#search-term-highlighting, `exact`, `prefix` and `suffix` are missing from the Search context.

Suggestion is to move more or all the other features of Open Annotation into the Presentation context, until we can move to Web Annotation Working Group model throughout.

**Comment by jpstroop** [comment]
We can do this any time right? Since the contexts aren't subject to SemVer?

**Comment by zimeon** [comment]
I agree. Making these changes we won't break anything (just fix things), so we can do it at will.

**Comment by mikeapp** [comment]
👍
