### ISSUE TITLE
otherContent "@embed": false in manifest_frame.json should be "@embed": true

### ISSUE THREAD

**Issue by christopher-johnson** [IIIF/iiif.io#959]
Since the expected serialization of an annotation list node in the manifest includes `@id` and `@type`, this means that the node is embedded.  With the 'false' flag set, the frame will output this:

``` json
 "otherContent": [
                "http://localhost:8080/fcrepo/rest/collection/test/003/list/001"
              ],
```

instead of this:

``` json
"otherContent": [
                {
                  "@id": "http://localhost:8080/fcrepo/rest/collection/test/003/list/001",
                  "@type": "sc:AnnotationList"
                }
              ],
```

**Comment by azaroth42** [comment]
If we just make it `@embed: true`, then it will embed ALL of the data, no? We want `@id` and `@type`, but not the list of Annotations. Not sure this is a fixable problem with frames, as they stand today?

**Comment by azaroth42** [comment]
Solution is to use `@explicit`, thanks to @workergnome.
http://json-ld.org/spec/latest/json-ld-framing/#explicit-inclusion-flag
