### ISSUE TITLE
Use rightsstatements.org for license/rights examples in Presentation API

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#960]
Along with creative commons to demonstrate that they both go in the same slot, and to hopefully promote usage.  Non normative ... 2.1.1 ?

 * [x] fixed on 2.1.1 branch
 * [ ] merged to master

**Comment by jpstroop** [comment]
:+1:

**Comment by zimeon** [comment]
:+1: good to promote, also agree 2.1.1 and will add milestone

**Comment by mikeapp** [comment]
👍

**Comment by zimeon** [comment]
Ed's meeting: for the two examples in the spec, have one as http://rightsstatements.org/page/NoC-NC/1.0/ and the other as https://creativecommons.org/publicdomain/zero/1.0/

**Comment by jpstroop** [comment]
TODO: check that this is done in image 2.1.1 branch as well

**Comment by zimeon** [comment]
Have created separate issue for Image API case #1094, will rename this to say Presentation API

**Comment by aisaac** [comment]
I've got an editorial question, same as at https://github.com/IIIF/iiif.io/issues/1094#issuecomment-293515606 except that the additional clarification could go to http://prezi_211.iiif.io/api/presentation/2.1/#rights-and-licensing-properties
