### ISSUE TITLE
Cookie withCredentials questions

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#966]
Discussion in The Hague and amongst the editors in Berlin following suggested that an HttpOnly cookie using withCredentials, and echoing the origin might be better than the current approach.  The following concerns need investigating before we could make a decision:
- For degraded images, can it still return ACAO: \* if withCredentials is set (allowing it to be cached)?
- If withCredentials is set on an open resource, will the response be cached?  
- When the initial request to the full resource is sent withCredentials, are they sent along on a redirect?
- Does the redirect trigger a pre-flight request, and are the credentials sent on that?
- If the redirect is across domains, we think the credentials won't be sent? Is that an important use case?
- Can we dispense with postMessage() by doing only withCredentials on the token service via XHR, and explaining why ACAO: (echoed) is okay in this scenario?

**Comment by azaroth42** [comment]
Q1: Can it return ACAO:*?
> Important note: when responding to a credentialed request,  server must specify a domain, and cannot use wild carding. The above example would fail if the header was wildcarded as: `Access-Control-Allow-Origin: *`

So no. 

If the resource receives a request with credentials, it MUST NOT respond with *. If the resource is thus ever used as a degraded version, it will have to deal with this.  There could be a switch on whether credentials are supplied and return * or origin.

Every request would need to be tried first without credentials to see if it works, and then again with the credentials if it doesn't.

**Comment by azaroth42** [comment]
Q3/4: Are credentials sent along on a redirect, and on preflights?

I think we're dead in the water with this idea by the redirect and preflight requirements of CORS. We should verify, of course but it seems from:
> https://www.w3.org/TR/cors/#cross-origin-request-with-preflight-0

That redirects that need preflights can't follow redirects at all.

In particular:

>The following request rules are to be observed while making the preflight request:
> * If the response has an HTTP status code that is not in the 2xx range:
>  Apply the network error steps.
> * Whenever the network error steps are applied, *terminate the algorithm* that invoked this set of steps and set the cross-origin request status to network error.

So the redirect will result in termination of the request.

**Comment by azaroth42** [comment]
There's no way for the server (as far as I can tell) to distinguish as the server between a client just requesting the resource withCredentials flag set but no Cookie, and just requesting the resource without the withCredentials flag.  So I think the server always has to set ACAC:true ; ACAO: origin?

**Comment by zimeon** [comment]
Conclusion after investigation is that we'll stick with the token approach. Final discussion in 2017-01-18 community call leading to creation of #1028 to publish auth 1.0 as approved in the The Hague.
